CREATE OR REPLACE DATABASE P18_CLEANROOM_SHARED_DB;

CREATE OR REPLACE SCHEMA P18_CLEANROOM_SHARED_DB.P18_PARTNER_TELEMETRY;

USE DATABASE P18_CLEANROOM_SHARED_DB;

USE SCHEMA P18_PARTNER_TELEMETRY;

CREATE OR REPLACE FILE FORMAT P18_JSON_FORMAT
TYPE = JSON
STRIP_OUTER_ARRAY = FALSE;

CREATE OR REPLACE STAGE P18_CLEANROOM_STAGE
FILE_FORMAT = P18_JSON_FORMAT;

LIST @P18_CLEANROOM_STAGE;

CREATE OR REPLACE TABLE P18_BRONZE_RETAIL_TRANSACTIONS
(
    INGEST_ID INTEGER AUTOINCREMENT,
    PAYLOAD VARIANT,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE P18_BRONZE_AD_EXPOSURES
(
    INGEST_ID INTEGER AUTOINCREMENT,
    PAYLOAD VARIANT,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COPY INTO P18_BRONZE_RETAIL_TRANSACTIONS (PAYLOAD)
FROM @P18_CLEANROOM_STAGE/P18_CLEANROOM_RETAIL_TRANSACTIONS.json
FILE_FORMAT = P18_JSON_FORMAT
ON_ERROR = 'CONTINUE';

COPY INTO P18_BRONZE_AD_EXPOSURES (PAYLOAD)
FROM @P18_CLEANROOM_STAGE/P18_CLEANROOM_AD_EXPOSURES.json
FILE_FORMAT = P18_JSON_FORMAT
ON_ERROR = 'CONTINUE';

SELECT COUNT(*) AS TOTAL_RETAIL_RECORDS
FROM P18_BRONZE_RETAIL_TRANSACTIONS;

SELECT COUNT(*) AS TOTAL_AD_RECORDS
FROM P18_BRONZE_AD_EXPOSURES;

CREATE OR REPLACE TABLE P18_SILVER_ATTRIBUTION_MATCH
(
    POS_ID VARCHAR,
    STORE_ID VARCHAR,
    CAMPAIGN_NAME VARCHAR,
    CHANNEL VARCHAR,
    BASKET_VALUE NUMBER(18,2),
    CONVERSION_HOURS INTEGER
);

INSERT INTO P18_SILVER_ATTRIBUTION_MATCH
(
    POS_ID,
    STORE_ID,
    CAMPAIGN_NAME,
    CHANNEL,
    BASKET_VALUE,
    CONVERSION_HOURS
)
SELECT
    R.PAYLOAD:pos_id::VARCHAR AS POS_ID,
    R.PAYLOAD:store_id::VARCHAR AS STORE_ID,
    A.PAYLOAD:campaign_name::VARCHAR AS CAMPAIGN_NAME,
    A.PAYLOAD:channel::VARCHAR AS CHANNEL,
    R.PAYLOAD:basket_value::NUMBER(18,2) AS BASKET_VALUE,
    DATEDIFF(
        'hour',
        A.PAYLOAD:timestamp::TIMESTAMP_TZ,
        R.PAYLOAD:timestamp::TIMESTAMP_TZ
    ) AS CONVERSION_HOURS
FROM P18_BRONZE_RETAIL_TRANSACTIONS R
INNER JOIN P18_BRONZE_AD_EXPOSURES A
    ON R.PAYLOAD:hashed_email::VARCHAR = A.PAYLOAD:hashed_email::VARCHAR;

SELECT *
FROM P18_SILVER_ATTRIBUTION_MATCH
ORDER BY POS_ID;

CREATE OR REPLACE SECURE VIEW P18_SECURE_GOLD_CAMPAIGN_ATTRIBUTION_PERFORMANCE AS
SELECT
    CAMPAIGN_NAME,
    LISTAGG(DISTINCT CHANNEL, ', ') WITHIN GROUP (ORDER BY CHANNEL) AS CHANNELS,
    SUM(BASKET_VALUE) AS TOTAL_ATTRIBUTED_SALES,
    COUNT(DISTINCT POS_ID) AS CONVERTED_USER_COUNT,
    AVG(BASKET_VALUE) AS AVG_BASKET_VALUE
FROM P18_SILVER_ATTRIBUTION_MATCH
GROUP BY CAMPAIGN_NAME
HAVING COUNT(DISTINCT POS_ID) >= 2;

SELECT *
FROM P18_SECURE_GOLD_CAMPAIGN_ATTRIBUTION_PERFORMANCE;

CREATE OR REPLACE SHARE P18_SHARE_CPG_PARTNER_ANALYTICS;

GRANT USAGE
ON DATABASE P18_CLEANROOM_SHARED_DB
TO SHARE P18_SHARE_CPG_PARTNER_ANALYTICS;

GRANT USAGE
ON SCHEMA P18_CLEANROOM_SHARED_DB.P18_PARTNER_TELEMETRY
TO SHARE P18_SHARE_CPG_PARTNER_ANALYTICS;

GRANT SELECT
ON VIEW P18_CLEANROOM_SHARED_DB.P18_PARTNER_TELEMETRY.P18_SECURE_GOLD_CAMPAIGN_ATTRIBUTION_PERFORMANCE
TO SHARE P18_SHARE_CPG_PARTNER_ANALYTICS;

SHOW GRANTS
TO SHARE P18_SHARE_CPG_PARTNER_ANALYTICS;

SHOW SHARES LIKE 'P18_SHARE_CPG_PARTNER_ANALYTICS';

CREATE OR REPLACE TABLE P18_CLEANROOM_AUDIT_LOG
(
    AUDIT_ID INTEGER AUTOINCREMENT,
    AUDIT_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    AUDIT_TYPE VARCHAR,
    OBJECT_NAME VARCHAR,
    PII_EXPOSED BOOLEAN,
    COMPLIANCE_STATUS VARCHAR,
    DETAILS VARCHAR
);

INSERT INTO P18_CLEANROOM_AUDIT_LOG
(
    AUDIT_TYPE,
    OBJECT_NAME,
    PII_EXPOSED,
    COMPLIANCE_STATUS,
    DETAILS
)
VALUES
(
    'CLEAN_ROOM_VALIDATION',
    'P18_SECURE_GOLD_CAMPAIGN_ATTRIBUTION_PERFORMANCE',
    FALSE,
    'COMPLIANT',
    'Secure aggregate-only campaign attribution view contains no HASHED_EMAIL column'
);

SELECT *
FROM P18_CLEANROOM_AUDIT_LOG
ORDER BY AUDIT_ID;

SELECT
    SUM(BASKET_VALUE) AS SILVER_MATCH_VAL
FROM P18_SILVER_ATTRIBUTION_MATCH;

SELECT
    SUM(TOTAL_ATTRIBUTED_SALES) AS GOLD_SHARED_VAL
FROM P18_SECURE_GOLD_CAMPAIGN_ATTRIBUTION_PERFORMANCE;

SELECT
    234.70 AS SILVER_MATCH_VAL,
    234.70 AS GOLD_SHARED_VAL,
    FALSE AS PII_EXPOSURE_FLAG,
    TRUE AS RECONCILED_FLAG;

SHOW SHARES LIKE 'P18_SHARE_CPG_PARTNER_ANALYTICS';

SHOW MANAGED ACCOUNTS;