CREATE WAREHOUSE IF NOT EXISTS P21A_RETAIL_WH
WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS P21A_RETAIL_DB;

CREATE SCHEMA IF NOT EXISTS P21A_RETAIL_DB.RETAIL_SCHEMA;

USE WAREHOUSE P21A_RETAIL_WH;
USE DATABASE P21A_RETAIL_DB;
USE SCHEMA RETAIL_SCHEMA;

CREATE OR REPLACE FILE FORMAT P21A_CSV_FORMAT
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1;

CREATE OR REPLACE STAGE P21A_RETAIL_STAGE
    FILE_FORMAT = P21A_CSV_FORMAT;

CREATE OR REPLACE TABLE RAW_SALES_STG (
    SALE_ID VARCHAR(50),
    STORE_ID VARCHAR(50),
    PRODUCT_ID VARCHAR(50),
    AMOUNT NUMBER(10,2),
    DATE_KEY INTEGER
);

CREATE OR REPLACE TABLE RAW_INVENTORY_STG (
    SNAPSHOT_ID VARCHAR(50),
    STORE_ID VARCHAR(50),
    PRODUCT_ID VARCHAR(50),
    ON_HAND_QTY INTEGER,
    DATE_KEY INTEGER
);

CREATE OR REPLACE TABLE DIM_STORE (
    STORE_ID VARCHAR(50) PRIMARY KEY,
    STORE_NAME VARCHAR(100),
    REGION VARCHAR(50)
);

CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_ID VARCHAR(50) PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(50)
);

INSERT INTO DIM_STORE (
    STORE_ID,
    STORE_NAME,
    REGION
)
VALUES (
    'STR-10',
    'Downtown Store',
    'East'
);

INSERT INTO DIM_PRODUCT (
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY
)
VALUES (
    'PRD-5',
    'Wireless Mouse',
    'Electronics'
);

INSERT INTO RAW_SALES_STG (
    SALE_ID,
    STORE_ID,
    PRODUCT_ID,
    AMOUNT,
    DATE_KEY
)
VALUES (
    'SL-301',
    'STR-10',
    'PRD-5',
    120.00,
    20260801
);

INSERT INTO RAW_INVENTORY_STG (
    SNAPSHOT_ID,
    STORE_ID,
    PRODUCT_ID,
    ON_HAND_QTY,
    DATE_KEY
)
VALUES (
    'INV-801',
    'STR-10',
    'PRD-5',
    45,
    20260801
);

SELECT
    'POS_SALES' AS DATASET,
    COUNT(*) AS LOADED_ROWS
FROM RAW_SALES_STG

UNION ALL

SELECT
    'INVENTORY',
    COUNT(*)
FROM RAW_INVENTORY_STG;

SELECT
    'Sales Analysis' AS BUSINESS_PROCESS,

    CASE
        WHEN COUNT(DISTINCT S.STORE_ID) =
             COUNT(DISTINCT DS.STORE_ID)
        THEN 'YES'
        ELSE 'NO'
    END AS CONFORMED_STORE,

    CASE
        WHEN COUNT(DISTINCT S.PRODUCT_ID) =
             COUNT(DISTINCT DP.PRODUCT_ID)
        THEN 'YES'
        ELSE 'NO'
    END AS CONFORMED_PRODUCT

FROM RAW_SALES_STG S
JOIN DIM_STORE DS
    ON S.STORE_ID = DS.STORE_ID
JOIN DIM_PRODUCT DP
    ON S.PRODUCT_ID = DP.PRODUCT_ID

UNION ALL

SELECT
    'Inventory Snapshot',

    CASE
        WHEN COUNT(DISTINCT I.STORE_ID) =
             COUNT(DISTINCT DS.STORE_ID)
        THEN 'YES'
        ELSE 'NO'
    END,

    CASE
        WHEN COUNT(DISTINCT I.PRODUCT_ID) =
             COUNT(DISTINCT DP.PRODUCT_ID)
        THEN 'YES'
        ELSE 'NO'
    END

FROM RAW_INVENTORY_STG I
JOIN DIM_STORE DS
    ON I.STORE_ID = DS.STORE_ID
JOIN DIM_PRODUCT DP
    ON I.PRODUCT_ID = DP.PRODUCT_ID;

CREATE OR REPLACE VIEW VIEW_SALES_MART AS
SELECT
    SALE_ID,
    STORE_ID,
    PRODUCT_ID,
    AMOUNT
FROM RAW_SALES_STG;

SELECT *
FROM VIEW_SALES_MART
ORDER BY SALE_ID;

CREATE OR REPLACE VIEW VIEW_INVENTORY_MART AS
SELECT
    SNAPSHOT_ID,
    STORE_ID,
    PRODUCT_ID,
    ON_HAND_QTY
FROM RAW_INVENTORY_STG;

SELECT *
FROM VIEW_INVENTORY_MART
ORDER BY SNAPSHOT_ID;

MERGE INTO DIM_STORE T
USING (
    SELECT
        'STR-10' AS STORE_ID,
        'Downtown Store Flagship' AS STORE_NAME,
        'East' AS REGION
) S
ON T.STORE_ID = S.STORE_ID

WHEN MATCHED THEN
    UPDATE SET
        T.STORE_NAME = S.STORE_NAME,
        T.REGION = S.REGION

WHEN NOT MATCHED THEN
    INSERT (
        STORE_ID,
        STORE_NAME,
        REGION
    )
    VALUES (
        S.STORE_ID,
        S.STORE_NAME,
        S.REGION
    );

SELECT
    "number of rows inserted" AS ROWS_INSERTED,
    "number of rows updated" AS ROWS_UPDATED
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SELECT
    'FACT_DIM_FK_MATCH' AS INTEGRITY_CHECK,

    (
        SELECT COUNT(*)
        FROM RAW_SALES_STG S
        LEFT JOIN DIM_STORE DS
            ON S.STORE_ID = DS.STORE_ID
        LEFT JOIN DIM_PRODUCT DP
            ON S.PRODUCT_ID = DP.PRODUCT_ID
        WHERE DS.STORE_ID IS NULL
           OR DP.PRODUCT_ID IS NULL
    )
    +
    (
        SELECT COUNT(*)
        FROM RAW_INVENTORY_STG I
        LEFT JOIN DIM_STORE DS
            ON I.STORE_ID = DS.STORE_ID
        LEFT JOIN DIM_PRODUCT DP
            ON I.PRODUCT_ID = DP.PRODUCT_ID
        WHERE DS.STORE_ID IS NULL
           OR DP.PRODUCT_ID IS NULL
    ) AS FAILED_RECORDS;

SET P21A_SALES_AUDIT_TIMESTAMP = CURRENT_TIMESTAMP();

SELECT
    SALE_ID,
    AMOUNT
FROM RAW_SALES_STG
AT(TIMESTAMP => $P21A_SALES_AUDIT_TIMESTAMP)
WHERE SALE_ID = 'SL-301';

ALTER TABLE DIM_STORE
CLUSTER BY (STORE_ID);

ALTER TABLE DIM_PRODUCT
CLUSTER BY (PRODUCT_ID);

SELECT
    'STORE_PRODUCT_KEYS' AS CLUSTERING_TARGET,

    CASE
        WHEN
            (
                SELECT CLUSTERING_KEY
                FROM P21A_RETAIL_DB.INFORMATION_SCHEMA.TABLES
                WHERE TABLE_SCHEMA = 'RETAIL_SCHEMA'
                  AND TABLE_NAME = 'DIM_STORE'
            ) IS NOT NULL
        AND
            (
                SELECT CLUSTERING_KEY
                FROM P21A_RETAIL_DB.INFORMATION_SCHEMA.TABLES
                WHERE TABLE_SCHEMA = 'RETAIL_SCHEMA'
                  AND TABLE_NAME = 'DIM_PRODUCT'
            ) IS NOT NULL
        THEN 'COMPLETED'
        ELSE 'NOT COMPLETED'
    END AS STATUS;