-- Project 19C: Enterprise Financial Wire Transfers, Inventory Balances & Coverage Matrix
-- Week 3 - Day 11
-- Topics: M1-M5


-- Task 1: Create database and schema

CREATE DATABASE IF NOT EXISTS P19C_FINANCIAL_DB;

CREATE SCHEMA IF NOT EXISTS P19C_FINANCIAL_DB.FINANCIAL_SCHEMA;


-- Task 2: Create warehouse

CREATE WAREHOUSE IF NOT EXISTS P19C_WH
WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE P19C_WH;

USE DATABASE P19C_FINANCIAL_DB;

USE SCHEMA FINANCIAL_SCHEMA;


-- Task 3: Create CSV file format

CREATE FILE FORMAT IF NOT EXISTS P19C_CSV_FORMAT
TYPE = 'CSV'
SKIP_HEADER = 1
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL', '');


-- Task 4: Create internal stage

CREATE STAGE IF NOT EXISTS P19C_STAGE
FILE_FORMAT = P19C_CSV_FORMAT;


-- Check uploaded files

LIST @P19C_STAGE;


-- Task 5: Create raw wire transfer table

CREATE OR REPLACE TABLE P19C_RAW_WIRE_TRANSFERS (
    TXN_ID VARCHAR(20),
    TXN_DATE DATE,
    SENDER_ACC VARCHAR(20),
    RECEIVER_ACC VARCHAR(20),
    AMOUNT NUMBER(18,2),
    FEE NUMBER(18,2),
    CURRENCY_RATE NUMBER(10,4),
    AUTH_METHOD VARCHAR(30),
    RISK_FLAG VARCHAR(20),
    TRANSFER_TYPE VARCHAR(30)
);


-- Task 6: Create raw vault cash table

CREATE OR REPLACE TABLE P19C_RAW_VAULT_CASH (
    SNAPSHOT_DATE DATE,
    VAULT_ID VARCHAR(20),
    CURRENCY_CODE VARCHAR(10),
    OPENING_BALANCE NUMBER(18,2),
    CLOSING_BALANCE NUMBER(18,2),
    RESERVE_RATIO_PCT NUMBER(8,4)
);


-- Task 7: Create raw credit lifecycle table

CREATE OR REPLACE TABLE P19C_RAW_CREDIT_LIFECYCLES (
    APP_ID VARCHAR(20),
    SUBMISSION_DATE DATE,
    UNDERWRITE_DATE DATE,
    RISK_APPROVAL_DATE DATE,
    DISBURSEMENT_DATE DATE
);


-- Task 8: Create raw audit coverage table

CREATE OR REPLACE TABLE P19C_RAW_AUDIT_COVERAGE (
    AUDIT_YEAR INTEGER,
    QUARTER VARCHAR(10),
    ACCOUNT_ID VARCHAR(20),
    AUDITOR_FIRM VARCHAR(50),
    COMPLIANCE_STATUS VARCHAR(30)
);


-- Task 9: Load raw wire transfers

COPY INTO P19C_RAW_WIRE_TRANSFERS
FROM @P19C_STAGE/P19C_raw_wire_transfers.csv
FILE_FORMAT = P19C_CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';


-- Task 10: Load raw vault cash

COPY INTO P19C_RAW_VAULT_CASH
FROM @P19C_STAGE/P19C_raw_vault_cash.csv
FILE_FORMAT = P19C_CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';


-- Task 11: Load raw credit lifecycles

COPY INTO P19C_RAW_CREDIT_LIFECYCLES
FROM @P19C_STAGE/P19C_raw_credit_lifecycles.csv
FILE_FORMAT = P19C_CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';


-- Task 12: Load raw audit coverage

COPY INTO P19C_RAW_AUDIT_COVERAGE
FROM @P19C_STAGE/P19C_raw_audit_coverage.csv
FILE_FORMAT = P19C_CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';


-- Verify raw wire transfers

SELECT *
FROM P19C_RAW_WIRE_TRANSFERS
ORDER BY TXN_ID;


-- Verify raw vault cash

SELECT *
FROM P19C_RAW_VAULT_CASH
ORDER BY SNAPSHOT_DATE, VAULT_ID;


-- Verify raw credit lifecycles

SELECT *
FROM P19C_RAW_CREDIT_LIFECYCLES
ORDER BY APP_ID;


-- Verify raw audit coverage

SELECT *
FROM P19C_RAW_AUDIT_COVERAGE
ORDER BY AUDIT_YEAR, QUARTER, ACCOUNT_ID;


-- Task 13: Build Junk Dimension

CREATE OR REPLACE TABLE P19C_DIM_WIRE_ATTRIBUTES (
    ATTRIBUTE_SK INTEGER,
    AUTH_METHOD VARCHAR(30),
    RISK_FLAG VARCHAR(20),
    TRANSFER_TYPE VARCHAR(30)
);


-- Task 14: Populate Junk Dimension

INSERT INTO P19C_DIM_WIRE_ATTRIBUTES (
    ATTRIBUTE_SK,
    AUTH_METHOD,
    RISK_FLAG,
    TRANSFER_TYPE
)
SELECT
    ROW_NUMBER() OVER (ORDER BY FIRST_TXN_ID) AS ATTRIBUTE_SK,
    AUTH_METHOD,
    RISK_FLAG,
    TRANSFER_TYPE
FROM (
    SELECT
        AUTH_METHOD,
        RISK_FLAG,
        TRANSFER_TYPE,
        MIN(TXN_ID) AS FIRST_TXN_ID
    FROM P19C_RAW_WIRE_TRANSFERS
    GROUP BY
        AUTH_METHOD,
        RISK_FLAG,
        TRANSFER_TYPE
);


-- Verify Junk Dimension

SELECT
    ATTRIBUTE_SK,
    AUTH_METHOD,
    RISK_FLAG,
    TRANSFER_TYPE
FROM P19C_DIM_WIRE_ATTRIBUTES
ORDER BY ATTRIBUTE_SK;


-- Task 15: Create Transaction Fact Table

CREATE OR REPLACE TABLE P19C_FACT_WIRE_TRANSFERS (
    TXN_ID VARCHAR(20),
    TXN_DATE DATE,
    SENDER_ACC VARCHAR(20),
    RECEIVER_ACC VARCHAR(20),
    ATTRIBUTE_SK INTEGER,
    AMOUNT NUMBER(18,2),
    FEE NUMBER(18,2),
    CURRENCY_RATE NUMBER(10,4),
    BASE_AMOUNT_USD NUMBER(18,2),
    NET_TRANSFER_VAL NUMBER(18,2)
);


-- Task 16: Populate Transaction Fact Table

INSERT INTO P19C_FACT_WIRE_TRANSFERS (
    TXN_ID,
    TXN_DATE,
    SENDER_ACC,
    RECEIVER_ACC,
    ATTRIBUTE_SK,
    AMOUNT,
    FEE,
    CURRENCY_RATE,
    BASE_AMOUNT_USD,
    NET_TRANSFER_VAL
)
SELECT
    W.TXN_ID,
    W.TXN_DATE,
    W.SENDER_ACC,
    W.RECEIVER_ACC,
    D.ATTRIBUTE_SK,
    W.AMOUNT,
    W.FEE,
    W.CURRENCY_RATE,

    W.AMOUNT * W.CURRENCY_RATE AS BASE_AMOUNT_USD,

    (W.AMOUNT * W.CURRENCY_RATE) - W.FEE AS NET_TRANSFER_VAL

FROM P19C_RAW_WIRE_TRANSFERS W
JOIN P19C_DIM_WIRE_ATTRIBUTES D
    ON W.AUTH_METHOD = D.AUTH_METHOD
    AND W.RISK_FLAG = D.RISK_FLAG
    AND W.TRANSFER_TYPE = D.TRANSFER_TYPE;


-- Verify Transaction Fact

SELECT
    TXN_ID,
    SENDER_ACC,
    ATTRIBUTE_SK,
    AMOUNT,
    BASE_AMOUNT_USD AS BASE_VAL_USD,
    NET_TRANSFER_VAL
FROM P19C_FACT_WIRE_TRANSFERS
ORDER BY TXN_ID;


-- Task 17: Create Periodic Vault Snapshot Fact

CREATE OR REPLACE TABLE P19C_FACT_VAULT_CASH_SNAPSHOT (
    SNAPSHOT_DATE DATE,
    VAULT_ID VARCHAR(20),
    CURRENCY_CODE VARCHAR(10),
    OPENING_BALANCE NUMBER(18,2),
    CLOSING_BALANCE NUMBER(18,2),
    RESERVE_RATIO_PCT NUMBER(8,4),
    NET_DAILY_CHANGE NUMBER(18,2)
);


-- Task 18: Populate Periodic Vault Snapshot Fact

INSERT INTO P19C_FACT_VAULT_CASH_SNAPSHOT (
    SNAPSHOT_DATE,
    VAULT_ID,
    CURRENCY_CODE,
    OPENING_BALANCE,
    CLOSING_BALANCE,
    RESERVE_RATIO_PCT,
    NET_DAILY_CHANGE
)
SELECT
    SNAPSHOT_DATE,
    VAULT_ID,
    CURRENCY_CODE,
    OPENING_BALANCE,
    CLOSING_BALANCE,
    RESERVE_RATIO_PCT,

    CLOSING_BALANCE - OPENING_BALANCE AS NET_DAILY_CHANGE

FROM P19C_RAW_VAULT_CASH;


-- Verify Periodic Snapshot Fact

SELECT
    SNAPSHOT_DATE,
    VAULT_ID,
    CURRENCY_CODE,
    OPENING_BALANCE,
    CLOSING_BALANCE,
    RESERVE_RATIO_PCT,
    NET_DAILY_CHANGE
FROM P19C_FACT_VAULT_CASH_SNAPSHOT
ORDER BY SNAPSHOT_DATE, VAULT_ID;


-- Task 19: Group Vault Snapshot by Date

SELECT
    SNAPSHOT_DATE,
    SUM(OPENING_BALANCE) AS TOTAL_OPENING_USD_EQU,
    SUM(CLOSING_BALANCE) AS TOTAL_CLOSING_USD_EQU
FROM P19C_FACT_VAULT_CASH_SNAPSHOT
GROUP BY SNAPSHOT_DATE
ORDER BY SNAPSHOT_DATE;


-- Task 20: Create Accumulating Credit Approval Snapshot

CREATE OR REPLACE TABLE P19C_FACT_CREDIT_APPROVAL_LIFECYCLE (
    APP_ID VARCHAR(20),
    SUBMISSION_DATE DATE,
    UNDERWRITE_DATE DATE,
    RISK_APPROVAL_DATE DATE,
    DISBURSEMENT_DATE DATE,
    UNDERWRITE_DAYS INTEGER,
    RISK_APPROVAL_DAYS INTEGER,
    DISBURSEMENT_DAYS INTEGER,
    TOTAL_CYCLE_DAYS INTEGER
);


-- Task 21: Populate Accumulating Snapshot

INSERT INTO P19C_FACT_CREDIT_APPROVAL_LIFECYCLE (
    APP_ID,
    SUBMISSION_DATE,
    UNDERWRITE_DATE,
    RISK_APPROVAL_DATE,
    DISBURSEMENT_DATE,
    UNDERWRITE_DAYS,
    RISK_APPROVAL_DAYS,
    DISBURSEMENT_DAYS,
    TOTAL_CYCLE_DAYS
)
SELECT
    APP_ID,
    SUBMISSION_DATE,
    UNDERWRITE_DATE,
    RISK_APPROVAL_DATE,
    DISBURSEMENT_DATE,

    CASE
        WHEN UNDERWRITE_DATE IS NOT NULL
        THEN DATEDIFF(
            'day',
            SUBMISSION_DATE,
            UNDERWRITE_DATE
        )
    END AS UNDERWRITE_DAYS,

    CASE
        WHEN RISK_APPROVAL_DATE IS NOT NULL
        THEN DATEDIFF(
            'day',
            UNDERWRITE_DATE,
            RISK_APPROVAL_DATE
        )
    END AS RISK_APPROVAL_DAYS,

    CASE
        WHEN DISBURSEMENT_DATE IS NOT NULL
        THEN DATEDIFF(
            'day',
            RISK_APPROVAL_DATE,
            DISBURSEMENT_DATE
        )
    END AS DISBURSEMENT_DAYS,

    CASE
        WHEN DISBURSEMENT_DATE IS NOT NULL
        THEN DATEDIFF(
            'day',
            SUBMISSION_DATE,
            DISBURSEMENT_DATE
        )
    END AS TOTAL_CYCLE_DAYS

FROM P19C_RAW_CREDIT_LIFECYCLES;


-- Task 22: Verify completed loan applications

SELECT
    APP_ID,
    UNDERWRITE_DAYS,
    RISK_APPROVAL_DAYS,
    DISBURSEMENT_DAYS,
    TOTAL_CYCLE_DAYS
FROM P19C_FACT_CREDIT_APPROVAL_LIFECYCLE
WHERE DISBURSEMENT_DATE IS NOT NULL
ORDER BY APP_ID;


-- Task 23: Identify Credit Pipeline Bottlenecks

SELECT
    APP_ID,
    SUBMISSION_DATE,

    CASE
        WHEN UNDERWRITE_DATE IS NULL
            THEN 'AWAITING_UNDERWRITE'

        WHEN RISK_APPROVAL_DATE IS NULL
            THEN 'AWAITING_RISK_AUTH'

        WHEN DISBURSEMENT_DATE IS NULL
            THEN 'AWAITING_DISBURSAL'

        ELSE 'COMPLETED'
    END AS CURRENT_BOTTLENECK

FROM P19C_FACT_CREDIT_APPROVAL_LIFECYCLE
WHERE DISBURSEMENT_DATE IS NULL
ORDER BY APP_ID;


-- Task 24: Create Factless Compliance Audit Coverage

CREATE OR REPLACE TABLE P19C_FACTLESS_COMPLIANCE_AUDIT_COVERAGE (
    AUDIT_YEAR INTEGER,
    QUARTER VARCHAR(10),
    ACCOUNT_ID VARCHAR(20),
    AUDITOR_FIRM VARCHAR(50),
    COMPLIANCE_STATUS VARCHAR(30)
);


-- Task 25: Populate Factless Compliance Audit Coverage

INSERT INTO P19C_FACTLESS_COMPLIANCE_AUDIT_COVERAGE (
    AUDIT_YEAR,
    QUARTER,
    ACCOUNT_ID,
    AUDITOR_FIRM,
    COMPLIANCE_STATUS
)
SELECT
    AUDIT_YEAR,
    QUARTER,
    ACCOUNT_ID,
    AUDITOR_FIRM,
    COMPLIANCE_STATUS
FROM P19C_RAW_AUDIT_COVERAGE;


-- Verify Factless Audit Coverage

SELECT *
FROM P19C_FACTLESS_COMPLIANCE_AUDIT_COVERAGE
ORDER BY AUDIT_YEAR, QUARTER, ACCOUNT_ID;


-- Task 26: Identify HIGH-RISK accounts that were NEVER audited in 2026

SELECT
    F.SENDER_ACC AS ACCOUNT_ID,
    COUNT(*) AS HIGH_RISK_TXN_COUNT,
    'NEVER_AUDITED' AS COMPLIANCE_STATUS
FROM P19C_FACT_WIRE_TRANSFERS F
JOIN P19C_DIM_WIRE_ATTRIBUTES D
    ON F.ATTRIBUTE_SK = D.ATTRIBUTE_SK
LEFT JOIN (
    SELECT DISTINCT
        ACCOUNT_ID
    FROM P19C_FACTLESS_COMPLIANCE_AUDIT_COVERAGE
    WHERE AUDIT_YEAR = 2026
) A
    ON F.SENDER_ACC = A.ACCOUNT_ID
WHERE D.RISK_FLAG = 'HIGH'
  AND A.ACCOUNT_ID IS NULL
GROUP BY F.SENDER_ACC
ORDER BY F.SENDER_ACC;


-- Task 27: Reconcile the supplied Task 6 expected output

SELECT
    F.SENDER_ACC AS ACCOUNT_ID,
    COUNT(*) AS HIGH_RISK_TXN_COUNT,
    'AUDITED' AS COMPLIANCE_STATUS
FROM P19C_FACT_WIRE_TRANSFERS F
JOIN P19C_DIM_WIRE_ATTRIBUTES D
    ON F.ATTRIBUTE_SK = D.ATTRIBUTE_SK
JOIN (
    SELECT DISTINCT
        ACCOUNT_ID
    FROM P19C_FACTLESS_COMPLIANCE_AUDIT_COVERAGE
    WHERE AUDIT_YEAR = 2026
) A
    ON F.SENDER_ACC = A.ACCOUNT_ID
WHERE D.RISK_FLAG = 'HIGH'
GROUP BY F.SENDER_ACC
ORDER BY F.SENDER_ACC;


-- Task 28: Risk Profile Revenue Cross-Analysis

SELECT
    D.RISK_FLAG,
    D.TRANSFER_TYPE,
    COUNT(F.TXN_ID) AS TOTAL_TXNS,
    SUM(F.FEE) AS TOTAL_FEES,
    SUM(F.BASE_AMOUNT_USD) AS TOTAL_VOLUME_USD
FROM P19C_FACT_WIRE_TRANSFERS F
JOIN P19C_DIM_WIRE_ATTRIBUTES D
    ON F.ATTRIBUTE_SK = D.ATTRIBUTE_SK
GROUP BY
    D.RISK_FLAG,
    D.TRANSFER_TYPE
ORDER BY
    D.RISK_FLAG,
    D.TRANSFER_TYPE;


-- Task 29: Multi-Fact Comprehensive Reconciliation Audit

WITH WIRE_TOTAL AS (
    SELECT
        SUM(BASE_AMOUNT_USD) AS TOTAL_WIRE_VOL_USD
    FROM P19C_FACT_WIRE_TRANSFERS
),

LATEST_VAULT AS (
    SELECT
        SUM(CLOSING_BALANCE) AS VAULT_CLOSING_USD
    FROM P19C_FACT_VAULT_CASH_SNAPSHOT
    WHERE SNAPSHOT_DATE = (
        SELECT MAX(SNAPSHOT_DATE)
        FROM P19C_FACT_VAULT_CASH_SNAPSHOT
    )
),

COMPLETED_LOANS AS (
    SELECT
        COUNT(*) AS COMPLETED_LOAN_APPS
    FROM P19C_FACT_CREDIT_APPROVAL_LIFECYCLE
    WHERE DISBURSEMENT_DATE IS NOT NULL
)

SELECT
    W.TOTAL_WIRE_VOL_USD,
    V.VAULT_CLOSING_USD,
    L.COMPLETED_LOAN_APPS,

    CASE
        WHEN W.TOTAL_WIRE_VOL_USD = 2286500.00
         AND V.VAULT_CLOSING_USD = 16400000.00
         AND L.COMPLETED_LOAN_APPS = 2
        THEN TRUE
        ELSE FALSE
    END AS AUDIT_SANITY_FLAG

FROM WIRE_TOTAL W
CROSS JOIN LATEST_VAULT V
CROSS JOIN COMPLETED_LOANS L;


-- Task 30: Final row-count validation

SELECT
    COUNT(*) AS RAW_WIRE_TRANSFER_COUNT
FROM P19C_RAW_WIRE_TRANSFERS;


SELECT
    COUNT(*) AS RAW_VAULT_CASH_COUNT
FROM P19C_RAW_VAULT_CASH;


SELECT
    COUNT(*) AS RAW_CREDIT_LIFECYCLE_COUNT
FROM P19C_RAW_CREDIT_LIFECYCLES;


SELECT
    COUNT(*) AS RAW_AUDIT_COVERAGE_COUNT
FROM P19C_RAW_AUDIT_COVERAGE;


SELECT
    COUNT(*) AS JUNK_DIMENSION_COUNT
FROM P19C_DIM_WIRE_ATTRIBUTES;


SELECT
    COUNT(*) AS WIRE_TRANSFER_FACT_COUNT
FROM P19C_FACT_WIRE_TRANSFERS;


SELECT
    COUNT(*) AS VAULT_SNAPSHOT_COUNT
FROM P19C_FACT_VAULT_CASH_SNAPSHOT;


SELECT
    COUNT(*) AS CREDIT_LIFECYCLE_COUNT
FROM P19C_FACT_CREDIT_APPROVAL_LIFECYCLE;


SELECT
    COUNT(*) AS AUDIT_COVERAGE_COUNT
FROM P19C_FACTLESS_COMPLIANCE_AUDIT_COVERAGE;