-- Task 1: Create warehouse
CREATE WAREHOUSE IF NOT EXISTS RETAIL8_WH
WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

-- Task 2: Create database
CREATE DATABASE IF NOT EXISTS RETAIL8_DB;

-- Task 3: Create schema
CREATE SCHEMA IF NOT EXISTS RETAIL8_DB.SALES_SCHEMA;

-- Select warehouse
USE WAREHOUSE RETAIL8_WH;

-- Select database
USE DATABASE RETAIL8_DB;

-- Select schema
USE SCHEMA SALES_SCHEMA;

-- Verify current environment
SELECT
    CURRENT_WAREHOUSE(),
    CURRENT_DATABASE(),
    CURRENT_SCHEMA();

-- Task 4: Create CSV file format
CREATE FILE FORMAT IF NOT EXISTS RETAIL8_CSV_FORMAT
TYPE = 'CSV'
SKIP_HEADER = 1
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

-- Task 5: Create internal stage
CREATE STAGE IF NOT EXISTS RETAIL8_STAGE
FILE_FORMAT = RETAIL8_CSV_FORMAT;

-- Check stage
SHOW STAGES;

-- After uploading customers_initial.csv and customer_updates.csv:
LIST @RETAIL8_STAGE;

-- Task 6: Create customer dimension
CREATE TABLE IF NOT EXISTS DIM_CUSTOMER (
    CUSTOMER_KEY INTEGER AUTOINCREMENT,
    CUSTOMER_ID INTEGER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50)
);

-- Task 7: Load initial customer data
COPY INTO DIM_CUSTOMER
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
)
FROM @RETAIL8_STAGE/customers_initial.csv
FILE_FORMAT = RETAIL8_CSV_FORMAT;

-- Verify initial records
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;

-- Check initial customer count
SELECT COUNT(*) AS TOTAL_CUSTOMERS
FROM DIM_CUSTOMER;

-- Task 8: Create staging table for updates
CREATE TABLE IF NOT EXISTS CUSTOMER_UPDATES (
    CUSTOMER_ID INTEGER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50)
);

-- Task 9: Load customer updates
COPY INTO CUSTOMER_UPDATES
FROM @RETAIL8_STAGE/customer_updates.csv
FILE_FORMAT = RETAIL8_CSV_FORMAT;

-- Verify update records
SELECT *
FROM CUSTOMER_UPDATES
ORDER BY CUSTOMER_ID;

-- Count update records
SELECT COUNT(*) AS RECORDS_RECEIVED
FROM CUSTOMER_UPDATES;

-- Task 10: Identify customers whose attributes changed
SELECT
    d.CUSTOMER_ID,
    d.CITY AS OLD_CITY,
    u.CITY AS NEW_CITY,
    d.MEMBERSHIP AS OLD_MEMBERSHIP,
    u.MEMBERSHIP AS NEW_MEMBERSHIP
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE
       d.CITY <> u.CITY
    OR d.STATE <> u.STATE
    OR d.MEMBERSHIP <> u.MEMBERSHIP
    OR d.SEGMENT <> u.SEGMENT
ORDER BY d.CUSTOMER_ID;

-- Task 11: Identify individual attribute changes
SELECT
    d.CUSTOMER_ID,
    'CITY' AS ATTRIBUTE,
    d.CITY AS OLD_VALUE,
    u.CITY AS NEW_VALUE
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.CITY <> u.CITY

UNION ALL

SELECT
    d.CUSTOMER_ID,
    'STATE' AS ATTRIBUTE,
    d.STATE AS OLD_VALUE,
    u.STATE AS NEW_VALUE
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.STATE <> u.STATE

UNION ALL

SELECT
    d.CUSTOMER_ID,
    'MEMBERSHIP' AS ATTRIBUTE,
    d.MEMBERSHIP AS OLD_VALUE,
    u.MEMBERSHIP AS NEW_VALUE
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.MEMBERSHIP <> u.MEMBERSHIP

UNION ALL

SELECT
    d.CUSTOMER_ID,
    'SEGMENT' AS ATTRIBUTE,
    d.SEGMENT AS OLD_VALUE,
    u.SEGMENT AS NEW_VALUE
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.SEGMENT <> u.SEGMENT

ORDER BY CUSTOMER_ID, ATTRIBUTE;

-- Task 12: Demonstrate the SCD problem by overwriting existing rows
UPDATE DIM_CUSTOMER d
SET
    CUSTOMER_NAME = u.CUSTOMER_NAME,
    CITY = u.CITY,
    STATE = u.STATE,
    MEMBERSHIP = u.MEMBERSHIP,
    SEGMENT = u.SEGMENT
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID;

-- Task 13: Display updated dimension
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;

-- Task 14: Check Customer 101 after overwrite
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP
FROM DIM_CUSTOMER
WHERE CUSTOMER_ID = 101;

-- Task 15: Show the original information that was lost
SELECT
    101 AS CUSTOMER_ID,
    'Amit Sharma' AS CUSTOMER_NAME,
    'Hyderabad' AS HISTORICAL_CITY,
    'Telangana' AS HISTORICAL_STATE,
    'Silver' AS HISTORICAL_MEMBERSHIP;

-- Task 16: Business impact demonstration
SELECT
    101 AS CUSTOMER_ID,
    'Amit Sharma' AS CUSTOMER_NAME,
    'Hyderabad' AS ORIGINAL_CITY,
    'Bengaluru' AS CURRENT_CITY,
    'Silver' AS ORIGINAL_MEMBERSHIP,
    'Gold' AS CURRENT_MEMBERSHIP,
    'Historical City, State and Membership LOST after overwrite' AS IMPACT;