CREATE WAREHOUSE IF NOT EXISTS RETAIL13_WH
WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS RETAIL_SCHEMAS_DW;

CREATE SCHEMA IF NOT EXISTS RETAIL_SCHEMAS_DW.SCHEMA_COMPARISON;

USE WAREHOUSE RETAIL13_WH;

USE DATABASE RETAIL_SCHEMAS_DW;

USE SCHEMA SCHEMA_COMPARISON;

SELECT
    CURRENT_DATABASE() AS CURRENT_DATABASE,
    CURRENT_SCHEMA() AS CURRENT_SCHEMA;


CREATE FILE FORMAT IF NOT EXISTS RETAIL13_CSV_FORMAT
TYPE = 'CSV'
SKIP_HEADER = 1
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE STAGE IF NOT EXISTS RETAIL13_STAGE
FILE_FORMAT = RETAIL13_CSV_FORMAT;


CREATE OR REPLACE TABLE SRC_REGIONS_AND_STORES (
    STORE_ID NUMBER,
    STORE_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    REGION_NAME VARCHAR(50),
    REGIONAL_MANAGER VARCHAR(100)
);

CREATE OR REPLACE TABLE SRC_PRODUCT_HIERARCHY (
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    SUBCATEGORY_NAME VARCHAR(50),
    CATEGORY_NAME VARCHAR(50),
    UNIT_PRICE NUMBER(10,2)
);

CREATE OR REPLACE TABLE SRC_CUSTOMERS (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50)
);

CREATE OR REPLACE TABLE SRC_SALES_TRANSACTIONS (
    TRANSACTION_ID VARCHAR(50),
    TRANSACTION_DATE DATE,
    CUSTOMER_ID NUMBER,
    STORE_ID NUMBER,
    PRODUCT_ID NUMBER,
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(10,2)
);


COPY INTO SRC_REGIONS_AND_STORES
FROM @RETAIL13_STAGE/regions_and_stores.csv
FILE_FORMAT = RETAIL13_CSV_FORMAT;

COPY INTO SRC_PRODUCT_HIERARCHY
FROM @RETAIL13_STAGE/product_hierarchy.csv
FILE_FORMAT = RETAIL13_CSV_FORMAT;

COPY INTO SRC_CUSTOMERS
FROM @RETAIL13_STAGE/customers.csv
FILE_FORMAT = RETAIL13_CSV_FORMAT;

COPY INTO SRC_SALES_TRANSACTIONS
FROM @RETAIL13_STAGE/sales_transactions.csv
FILE_FORMAT = RETAIL13_CSV_FORMAT;


CREATE OR REPLACE TABLE STAR_DIM_STORE (
    STORE_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    STORE_ID NUMBER,
    STORE_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    REGION_NAME VARCHAR(50),
    REGIONAL_MANAGER VARCHAR(100)
);

INSERT INTO STAR_DIM_STORE (
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    REGION_NAME,
    REGIONAL_MANAGER
)
SELECT
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    REGION_NAME,
    REGIONAL_MANAGER
FROM SRC_REGIONS_AND_STORES;


CREATE OR REPLACE TABLE STAR_DIM_PRODUCT (
    PRODUCT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    SUBCATEGORY_NAME VARCHAR(50),
    CATEGORY_NAME VARCHAR(50),
    UNIT_PRICE NUMBER(10,2)
);

INSERT INTO STAR_DIM_PRODUCT (
    PRODUCT_ID,
    PRODUCT_NAME,
    SUBCATEGORY_NAME,
    CATEGORY_NAME,
    UNIT_PRICE
)
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    SUBCATEGORY_NAME,
    CATEGORY_NAME,
    UNIT_PRICE
FROM SRC_PRODUCT_HIERARCHY;


CREATE OR REPLACE TABLE STAR_FACT_SALES (
    SALES_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    TRANSACTION_ID VARCHAR(50),
    TRANSACTION_DATE DATE,
    CUSTOMER_ID NUMBER,
    STORE_KEY NUMBER,
    PRODUCT_KEY NUMBER,
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(12,2)
);


INSERT INTO STAR_FACT_SALES (
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_ID,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    TOTAL_AMOUNT
)
SELECT
    S.TRANSACTION_ID,
    S.TRANSACTION_DATE,
    S.CUSTOMER_ID,
    ST.STORE_KEY,
    P.PRODUCT_KEY,
    S.QUANTITY,
    S.QUANTITY * S.UNIT_PRICE
FROM SRC_SALES_TRANSACTIONS S
JOIN STAR_DIM_STORE ST
    ON S.STORE_ID = ST.STORE_ID
JOIN STAR_DIM_PRODUCT P
    ON S.PRODUCT_ID = P.PRODUCT_ID;


CREATE OR REPLACE TABLE SNOW_DIM_REGION (
    REGION_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    REGION_NAME VARCHAR(50),
    REGIONAL_MANAGER VARCHAR(100)
);

CREATE OR REPLACE TABLE SNOW_DIM_STORE (
    STORE_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    STORE_ID NUMBER,
    STORE_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    REGION_KEY NUMBER,
    CONSTRAINT FK_SNOW_STORE_REGION
        FOREIGN KEY (REGION_KEY)
        REFERENCES SNOW_DIM_REGION(REGION_KEY)
);


CREATE OR REPLACE TABLE SNOW_DIM_CATEGORY (
    CATEGORY_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(50)
);

CREATE OR REPLACE TABLE SNOW_DIM_SUBCATEGORY (
    SUBCATEGORY_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    SUBCATEGORY_NAME VARCHAR(50),
    CATEGORY_KEY NUMBER,
    CONSTRAINT FK_SNOW_SUBCATEGORY_CATEGORY
        FOREIGN KEY (CATEGORY_KEY)
        REFERENCES SNOW_DIM_CATEGORY(CATEGORY_KEY)
);

CREATE OR REPLACE TABLE SNOW_DIM_PRODUCT (
    PRODUCT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    UNIT_PRICE NUMBER(10,2),
    SUBCATEGORY_KEY NUMBER,
    CONSTRAINT FK_SNOW_PRODUCT_SUBCATEGORY
        FOREIGN KEY (SUBCATEGORY_KEY)
        REFERENCES SNOW_DIM_SUBCATEGORY(SUBCATEGORY_KEY)
);


INSERT INTO SNOW_DIM_REGION (
    REGION_NAME,
    REGIONAL_MANAGER
)
SELECT DISTINCT
    REGION_NAME,
    REGIONAL_MANAGER
FROM SRC_REGIONS_AND_STORES;


INSERT INTO SNOW_DIM_STORE (
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    REGION_KEY
)
SELECT
    S.STORE_ID,
    S.STORE_NAME,
    S.CITY,
    S.STATE,
    R.REGION_KEY
FROM SRC_REGIONS_AND_STORES S
JOIN SNOW_DIM_REGION R
    ON S.REGION_NAME = R.REGION_NAME
   AND S.REGIONAL_MANAGER = R.REGIONAL_MANAGER;


INSERT INTO SNOW_DIM_CATEGORY (
    CATEGORY_NAME
)
SELECT DISTINCT
    CATEGORY_NAME
FROM SRC_PRODUCT_HIERARCHY;


INSERT INTO SNOW_DIM_SUBCATEGORY (
    SUBCATEGORY_NAME,
    CATEGORY_KEY
)
SELECT DISTINCT
    P.SUBCATEGORY_NAME,
    C.CATEGORY_KEY
FROM SRC_PRODUCT_HIERARCHY P
JOIN SNOW_DIM_CATEGORY C
    ON P.CATEGORY_NAME = C.CATEGORY_NAME;


INSERT INTO SNOW_DIM_PRODUCT (
    PRODUCT_ID,
    PRODUCT_NAME,
    UNIT_PRICE,
    SUBCATEGORY_KEY
)
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.UNIT_PRICE,
    S.SUBCATEGORY_KEY
FROM SRC_PRODUCT_HIERARCHY P
JOIN SNOW_DIM_SUBCATEGORY S
    ON P.SUBCATEGORY_NAME = S.SUBCATEGORY_NAME
JOIN SNOW_DIM_CATEGORY C
    ON S.CATEGORY_KEY = C.CATEGORY_KEY
   AND P.CATEGORY_NAME = C.CATEGORY_NAME;


CREATE OR REPLACE TABLE SNOW_FACT_SALES (
    SALES_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    TRANSACTION_ID VARCHAR(50),
    TRANSACTION_DATE DATE,
    CUSTOMER_ID NUMBER,
    STORE_KEY NUMBER,
    PRODUCT_KEY NUMBER,
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(12,2),
    CONSTRAINT FK_SNOW_FACT_STORE
        FOREIGN KEY (STORE_KEY)
        REFERENCES SNOW_DIM_STORE(STORE_KEY),
    CONSTRAINT FK_SNOW_FACT_PRODUCT
        FOREIGN KEY (PRODUCT_KEY)
        REFERENCES SNOW_DIM_PRODUCT(PRODUCT_KEY)
);


INSERT INTO SNOW_FACT_SALES (
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_ID,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    TOTAL_AMOUNT
)
SELECT
    S.TRANSACTION_ID,
    S.TRANSACTION_DATE,
    S.CUSTOMER_ID,
    ST.STORE_KEY,
    P.PRODUCT_KEY,
    S.QUANTITY,
    S.QUANTITY * S.UNIT_PRICE
FROM SRC_SALES_TRANSACTIONS S
JOIN SNOW_DIM_STORE ST
    ON S.STORE_ID = ST.STORE_ID
JOIN SNOW_DIM_PRODUCT P
    ON S.PRODUCT_ID = P.PRODUCT_ID;


SELECT
    ST.REGION_NAME,
    P.CATEGORY_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM STAR_FACT_SALES F
JOIN STAR_DIM_STORE ST
    ON F.STORE_KEY = ST.STORE_KEY
JOIN STAR_DIM_PRODUCT P
    ON F.PRODUCT_KEY = P.PRODUCT_KEY
GROUP BY
    ST.REGION_NAME,
    P.CATEGORY_NAME
ORDER BY
    ST.REGION_NAME,
    P.CATEGORY_NAME;


SELECT
    R.REGION_NAME,
    C.CATEGORY_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SNOW_FACT_SALES F
JOIN SNOW_DIM_STORE S
    ON F.STORE_KEY = S.STORE_KEY
JOIN SNOW_DIM_REGION R
    ON S.REGION_KEY = R.REGION_KEY
JOIN SNOW_DIM_PRODUCT P
    ON F.PRODUCT_KEY = P.PRODUCT_KEY
JOIN SNOW_DIM_SUBCATEGORY SC
    ON P.SUBCATEGORY_KEY = SC.SUBCATEGORY_KEY
JOIN SNOW_DIM_CATEGORY C
    ON SC.CATEGORY_KEY = C.CATEGORY_KEY
GROUP BY
    R.REGION_NAME,
    C.CATEGORY_NAME
ORDER BY
    R.REGION_NAME,
    C.CATEGORY_NAME;


WITH STAR_DIMENSION_COUNT AS (
    SELECT COUNT(*) AS TOTAL
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = CURRENT_SCHEMA()
      AND TABLE_NAME IN (
          'STAR_DIM_STORE',
          'STAR_DIM_PRODUCT'
      )
),
SNOW_DIMENSION_COUNT AS (
    SELECT COUNT(*) AS TOTAL
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = CURRENT_SCHEMA()
      AND TABLE_NAME IN (
          'SNOW_DIM_REGION',
          'SNOW_DIM_STORE',
          'SNOW_DIM_CATEGORY',
          'SNOW_DIM_SUBCATEGORY',
          'SNOW_DIM_PRODUCT'
      )
)
SELECT
    'Dimension Normalization Level' AS METRIC_FEATURE,
    'Denormalized (Flat)' AS STAR_SCHEMA,
    'Normalized (Hierarchical)' AS SNOWFLAKE_SCHEMA
UNION ALL
SELECT
    'Total Dimension Tables',
    TO_VARCHAR((SELECT TOTAL FROM STAR_DIMENSION_COUNT)) || ' Tables',
    TO_VARCHAR((SELECT TOTAL FROM SNOW_DIMENSION_COUNT)) || ' Tables'
UNION ALL
SELECT
    'Joins for Category Revenue',
    '2 Joins (Fact + 2 Dims)',
    '4 Joins (Fact + 4 Dims)'
UNION ALL
SELECT
    'Data Redundancy',
    'Higher (Repeated text)',
    'Lower (Normalized IDs)'
UNION ALL
SELECT
    'Query Simplicity',
    'High (Simple GROUP BY)',
    'Lower (Requires nested FKs)';


SELECT
    ST.REGIONAL_MANAGER,
    SUM(F.QUANTITY) AS TOTAL_ITEMS_SOLD,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_SALES_AMOUNT
FROM STAR_FACT_SALES F
JOIN STAR_DIM_STORE ST
    ON F.STORE_KEY = ST.STORE_KEY
GROUP BY
    ST.REGIONAL_MANAGER
ORDER BY
    ST.REGIONAL_MANAGER;


SELECT
    'Star Schema' AS SCHEMA_TYPE,
    'STAR_DIM_STORE' AS TABLE_NAME,
    COUNT(*) AS RECORD_COUNT
FROM STAR_DIM_STORE

UNION ALL

SELECT
    'Star Schema',
    'STAR_DIM_PRODUCT',
    COUNT(*)
FROM STAR_DIM_PRODUCT

UNION ALL

SELECT
    'Star Schema',
    'STAR_FACT_SALES',
    COUNT(*)
FROM STAR_FACT_SALES

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_REGION',
    COUNT(*)
FROM SNOW_DIM_REGION

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_STORE',
    COUNT(*)
FROM SNOW_DIM_STORE

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_CATEGORY',
    COUNT(*)
FROM SNOW_DIM_CATEGORY

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_SUBCATEGORY',
    COUNT(*)
FROM SNOW_DIM_SUBCATEGORY

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_PRODUCT',
    COUNT(*)
FROM SNOW_DIM_PRODUCT

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_FACT_SALES',
    COUNT(*)
FROM SNOW_FACT_SALES;