-- Task 1: Create database and schema
CREATE DATABASE IF NOT EXISTS RETAIL9_DB;

CREATE SCHEMA IF NOT EXISTS RETAIL9_DB.SALES_SCHEMA;

-- Select warehouse
CREATE WAREHOUSE IF NOT EXISTS RETAIL9_WH
WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE RETAIL9_WH;
USE DATABASE RETAIL9_DB;
USE SCHEMA SALES_SCHEMA;


-- Task 2: Create SCD Type 1 table
CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE1 (
    CUSTOMER_KEY INTEGER AUTOINCREMENT,
    CUSTOMER_ID INTEGER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30)
);


-- Create CSV file format
CREATE FILE FORMAT IF NOT EXISTS RETAIL9_CSV_FORMAT
TYPE = 'CSV'
SKIP_HEADER = 1
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"';


-- Create internal stage
CREATE STAGE IF NOT EXISTS RETAIL9_STAGE
FILE_FORMAT = RETAIL9_CSV_FORMAT;


-- Check uploaded files
LIST @RETAIL9_STAGE;


-- Task 3: Load initial Type 1 data
COPY INTO DIM_CUSTOMER_TYPE1
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
)
FROM @RETAIL9_STAGE/customers_initial.csv
FILE_FORMAT = RETAIL9_CSV_FORMAT;


-- Verify initial Type 1 records
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER_TYPE1
ORDER BY CUSTOMER_ID;


-- Verify initial customer count
SELECT COUNT(*) AS TOTAL_CUSTOMERS
FROM DIM_CUSTOMER_TYPE1;


-- Create staging table for customer updates
CREATE OR REPLACE TABLE CUSTOMER_UPDATES (
    CUSTOMER_ID INTEGER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE
);


-- Task 5: Load customer updates
COPY INTO CUSTOMER_UPDATES
FROM @RETAIL9_STAGE/customer_updates.csv
FILE_FORMAT = RETAIL9_CSV_FORMAT;


-- Verify customer updates
SELECT *
FROM CUSTOMER_UPDATES
ORDER BY CUSTOMER_ID;


-- Verify update record count
SELECT COUNT(*) AS RECORDS_RECEIVED
FROM CUSTOMER_UPDATES;


-- Task 6: Identify changed customers
SELECT
    d.CUSTOMER_ID,
    d.CITY AS OLD_CITY,
    u.CITY AS NEW_CITY,
    d.MEMBERSHIP AS OLD_MEMBERSHIP,
    u.MEMBERSHIP AS NEW_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE1 d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE
       d.CITY <> u.CITY
    OR d.STATE <> u.STATE
    OR d.MEMBERSHIP <> u.MEMBERSHIP
    OR d.SEGMENT <> u.SEGMENT
ORDER BY d.CUSTOMER_ID;


-- Task 7: Identify attribute changes
SELECT
    d.CUSTOMER_ID,
    'CITY' AS ATTRIBUTE,
    d.CITY AS OLD_VALUE,
    u.CITY AS NEW_VALUE
FROM DIM_CUSTOMER_TYPE1 d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.CITY <> u.CITY

UNION ALL

SELECT
    d.CUSTOMER_ID,
    'STATE' AS ATTRIBUTE,
    d.STATE AS OLD_VALUE,
    u.STATE AS NEW_VALUE
FROM DIM_CUSTOMER_TYPE1 d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.STATE <> u.STATE

UNION ALL

SELECT
    d.CUSTOMER_ID,
    'MEMBERSHIP' AS ATTRIBUTE,
    d.MEMBERSHIP AS OLD_VALUE,
    u.MEMBERSHIP AS NEW_VALUE
FROM DIM_CUSTOMER_TYPE1 d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.MEMBERSHIP <> u.MEMBERSHIP

UNION ALL

SELECT
    d.CUSTOMER_ID,
    'SEGMENT' AS ATTRIBUTE,
    d.SEGMENT AS OLD_VALUE,
    u.SEGMENT AS NEW_VALUE
FROM DIM_CUSTOMER_TYPE1 d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.SEGMENT <> u.SEGMENT

ORDER BY CUSTOMER_ID, ATTRIBUTE;


-- Task 8: Demonstrate SCD Type 1 problem
-- Overwrite the existing dimension records
UPDATE DIM_CUSTOMER_TYPE1 d
SET
    CUSTOMER_NAME = u.CUSTOMER_NAME,
    CITY = u.CITY,
    STATE = u.STATE,
    MEMBERSHIP = u.MEMBERSHIP,
    SEGMENT = u.SEGMENT
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID;


-- Task 9: Display updated Type 1 dimension
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER_TYPE1
ORDER BY CUSTOMER_ID;


-- Task 10: Demonstrate historical data loss
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP
FROM DIM_CUSTOMER_TYPE1
WHERE CUSTOMER_ID = 101;


-- Task 11: Create SCD Type 2 table
CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE2 (
    CUSTOMER_KEY INTEGER AUTOINCREMENT,
    CUSTOMER_ID INTEGER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);


-- Task 12: Load initial Type 2 records
-- Load directly from the original initial CSV
-- Do not load from the already-updated Type 1 table
INSERT INTO DIM_CUSTOMER_TYPE2 (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    '2026-01-01',
    '9999-12-31',
    TRUE
FROM (
    SELECT
        $1::INTEGER AS CUSTOMER_ID,
        $2::VARCHAR AS CUSTOMER_NAME,
        $3::VARCHAR AS CITY,
        $4::VARCHAR AS STATE,
        $5::VARCHAR AS MEMBERSHIP,
        $6::VARCHAR AS SEGMENT
    FROM @RETAIL9_STAGE/customers_initial.csv
    (FILE_FORMAT => 'RETAIL9_CSV_FORMAT')
);


-- Verify initial Type 2 records
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
ORDER BY CUSTOMER_ID;


-- Task 10/11/12: Apply Type 2 changes
-- Step 1: Expire old records
UPDATE DIM_CUSTOMER_TYPE2 d
SET
    EXPIRY_DATE = DATEADD(DAY, -1, u.EFFECTIVE_DATE),
    IS_CURRENT = FALSE
FROM CUSTOMER_UPDATES u
WHERE
    d.CUSTOMER_ID = u.CUSTOMER_ID
    AND d.IS_CURRENT = TRUE
    AND (
           d.CITY <> u.CITY
        OR d.STATE <> u.STATE
        OR d.MEMBERSHIP <> u.MEMBERSHIP
        OR d.SEGMENT <> u.SEGMENT
    );


-- Step 2: Insert new Type 2 records
INSERT INTO DIM_CUSTOMER_TYPE2 (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    u.CUSTOMER_ID,
    u.CUSTOMER_NAME,
    u.CITY,
    u.STATE,
    u.MEMBERSHIP,
    u.SEGMENT,
    u.EFFECTIVE_DATE,
    '9999-12-31',
    TRUE
FROM CUSTOMER_UPDATES u;


-- Task 14: Display complete Type 2 history
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;


-- Task 15: Display current customer records
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER_TYPE2
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;


-- Task 16: Historical customer analysis
-- Find Customer 101's information on March 15, 2026
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    MEMBERSHIP,
    CITY,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 101
  AND '2026-03-15' BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;


-- Task 17: Compare Type 1 and Type 2
SELECT
    'SCD TYPE 1' AS SCD_TYPE,
    'No' AS OLD_VALUE_PRESERVED,
    'No' AS NEW_ROW_CREATED,
    'No' AS HISTORICAL_ANALYSIS

UNION ALL

SELECT
    'SCD TYPE 2',
    'Yes',
    'Yes',
    'Yes';


-- Task 18: Final validation
-- Type 1 record count
SELECT
    COUNT(*) AS SCD_TYPE_1_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE1;


-- Type 2 record count
SELECT
    COUNT(*) AS SCD_TYPE_2_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE2;


-- Type 2 current record count
SELECT
    COUNT(*) AS SCD_TYPE_2_CURRENT_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE2
WHERE IS_CURRENT = TRUE;


-- Type 2 historical record count
SELECT
    COUNT(*) AS SCD_TYPE_2_HISTORICAL_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE2
WHERE IS_CURRENT = FALSE;