-- -- Task 1: Create database and schema

-- CREATE DATABASE IF NOT EXISTS FINTECH_MEDALLION_DW;

-- CREATE SCHEMA IF NOT EXISTS FINTECH_MEDALLION_DW.SCHEMA_MEDALLION_14B;

-- USE DATABASE FINTECH_MEDALLION_DW;

-- USE SCHEMA SCHEMA_MEDALLION_14B;


-- -- Task 1: Create CSV/JSON file format

-- CREATE OR REPLACE FILE FORMAT FINTECH_JSON_FORMAT_14B
-- TYPE = JSON;


-- -- Task 1: Create stage

-- CREATE OR REPLACE STAGE STAGE_MEDALLION_14B
-- FILE_FORMAT = FINTECH_JSON_FORMAT_14B;


-- -- Task 1: Create Bronze table

-- CREATE OR REPLACE TABLE BRONZE_PAYMENT_PAYLOADS (
--     RAW_PAYLOAD VARIANT
-- );




-- Task 1: Load Bronze data

COPY INTO BRONZE_PAYMENT_PAYLOADS
FROM @STAGE_MEDALLION_14B/PROJECT_14B_BRONZE_PAYMENT_PAYLOADS.json
FILE_FORMAT = FINTECH_JSON_FORMAT_14B;


-- Task 1: Verify Bronze records

SELECT COUNT(*) AS TOTAL_BRONZE_RECORDS_CT
FROM BRONZE_PAYMENT_PAYLOADS;


-- Task 2: Create Silver table

CREATE OR REPLACE TABLE SILVER_CLEANED_TRANSACTIONS (
    TXN_ID VARCHAR(50),
    TXN_TIME TIMESTAMP_TZ,
    MERCHANT_ID NUMBER,
    MERCHANT_NAME VARCHAR(100),
    MASKED_CARD VARCHAR(19),
    GROSS_AMOUNT NUMBER(12,2),
    FEE_PCT NUMBER(5,2),
    PROCESSING_FEE NUMBER(12,2),
    NET_SETTLEMENT_AMOUNT NUMBER(12,2),
    STATUS VARCHAR(20)
);


-- Task 2: Populate Silver table

INSERT INTO SILVER_CLEANED_TRANSACTIONS
(
    TXN_ID,
    TXN_TIME,
    MERCHANT_ID,
    MERCHANT_NAME,
    MASKED_CARD,
    GROSS_AMOUNT,
    FEE_PCT,
    PROCESSING_FEE,
    NET_SETTLEMENT_AMOUNT,
    STATUS
)
SELECT
    RAW_PAYLOAD:txn_id::VARCHAR,
    RAW_PAYLOAD:txn_time::TIMESTAMP_TZ,
    RAW_PAYLOAD:merchant_id::NUMBER,
    RAW_PAYLOAD:merchant_name::VARCHAR,
    'XXXX-XXXX-XXXX-' || RIGHT(RAW_PAYLOAD:card_number::VARCHAR, 4),
    RAW_PAYLOAD:amount::NUMBER(12,2),
    RAW_PAYLOAD:fee_pct::NUMBER(5,2),
    RAW_PAYLOAD:amount::NUMBER(12,2)
        * (RAW_PAYLOAD:fee_pct::NUMBER(5,2) / 100),
    RAW_PAYLOAD:amount::NUMBER(12,2)
        - (
            RAW_PAYLOAD:amount::NUMBER(12,2)
            * (RAW_PAYLOAD:fee_pct::NUMBER(5,2) / 100)
          ),
    RAW_PAYLOAD:status::VARCHAR
FROM BRONZE_PAYMENT_PAYLOADS;


-- Task 2: Display Silver records

SELECT
    TXN_ID,
    MERCHANT_ID,
    MERCHANT_NAME,
    MASKED_CARD,
    GROSS_AMOUNT AS GROSS,
    PROCESSING_FEE,
    NET_SETTLEMENT_AMOUNT,
    STATUS
FROM SILVER_CLEANED_TRANSACTIONS
ORDER BY TXN_ID;


-- Task 3: Create Gold table

CREATE OR REPLACE TABLE GOLD_MERCHANT_SETTLEMENTS AS
SELECT
    MERCHANT_ID,
    MERCHANT_NAME,
    SUM(GROSS_AMOUNT) AS TOTAL_APPROVED_GROSS,
    SUM(PROCESSING_FEE) AS TOTAL_GATEWAY_FEES,
    SUM(NET_SETTLEMENT_AMOUNT) AS TOTAL_NET_PAYOUT,
    COUNT(*) AS APPROVED_COUNT
FROM SILVER_CLEANED_TRANSACTIONS
WHERE STATUS = 'APPROVED'
GROUP BY
    MERCHANT_ID,
    MERCHANT_NAME;


-- Task 3: Display Gold results

SELECT
    MERCHANT_ID,
    MERCHANT_NAME,
    TOTAL_APPROVED_GROSS,
    TOTAL_GATEWAY_FEES,
    TOTAL_NET_PAYOUT,
    APPROVED_COUNT
FROM GOLD_MERCHANT_SETTLEMENTS
ORDER BY MERCHANT_ID;


-- Task 4: Corrupt TechZone approved records

UPDATE SILVER_CLEANED_TRANSACTIONS
SET STATUS = 'REFUNDED'
WHERE MERCHANT_NAME = 'TechZone'
  AND STATUS = 'APPROVED';


-- Task 4: Save corruption statement ID

SET CORRUPTION_QUERY_ID = LAST_QUERY_ID();


-- Task 4: Inspect data before corruption using Time Travel

SELECT
    TXN_ID,
    MERCHANT_NAME,
    GROSS_AMOUNT AS GROSS,
    STATUS
FROM SILVER_CLEANED_TRANSACTIONS
BEFORE (STATEMENT => $CORRUPTION_QUERY_ID)
WHERE MERCHANT_NAME = 'TechZone'
  AND STATUS = 'APPROVED'
ORDER BY TXN_ID;


-- Task 5: Recover corrupted records using Time Travel data

UPDATE SILVER_CLEANED_TRANSACTIONS AS CURRENT_DATA
SET STATUS = HISTORICAL_DATA.STATUS
FROM (
    SELECT
        TXN_ID,
        STATUS
    FROM SILVER_CLEANED_TRANSACTIONS
    BEFORE (STATEMENT => $CORRUPTION_QUERY_ID)
    WHERE MERCHANT_NAME = 'TechZone'
) AS HISTORICAL_DATA
WHERE CURRENT_DATA.TXN_ID = HISTORICAL_DATA.TXN_ID;


-- Task 5: Validate recovery

SELECT
    MERCHANT_NAME,
    COUNT_IF(STATUS = 'APPROVED') AS APPROVED_COUNT,
    COUNT_IF(STATUS = 'REFUNDED') AS REFUNDED_COUNT
FROM SILVER_CLEANED_TRANSACTIONS
WHERE MERCHANT_NAME = 'TechZone'
GROUP BY MERCHANT_NAME;


-- Task 6: Reconciliation audit

SELECT
    (
        SELECT SUM(RAW_PAYLOAD:amount::NUMBER(12,2))
        FROM BRONZE_PAYMENT_PAYLOADS
    ) AS BRONZE_GROSS_SUM,

    (
        SELECT SUM(GROSS_AMOUNT)
        FROM SILVER_CLEANED_TRANSACTIONS
    ) AS SILVER_GROSS_SUM,

    (
        SELECT SUM(TOTAL_APPROVED_GROSS)
        FROM GOLD_MERCHANT_SETTLEMENTS
    ) AS GOLD_GROSS_SUM,

    CASE
        WHEN
            (
                SELECT SUM(RAW_PAYLOAD:amount::NUMBER(12,2))
                FROM BRONZE_PAYMENT_PAYLOADS
            )
            =
            (
                SELECT SUM(GROSS_AMOUNT)
                FROM SILVER_CLEANED_TRANSACTIONS
            )
            + 0
        AND
            (
                SELECT SUM(TOTAL_APPROVED_GROSS)
                FROM GOLD_MERCHANT_SETTLEMENTS
            ) = 223700.00
        THEN TRUE
        ELSE FALSE
    END AS DATA_MATCH_FLAG;