CREATE WAREHOUSE IF NOT EXISTS RETAIL10_WH
WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS RETAIL10_DB;

CREATE SCHEMA IF NOT EXISTS RETAIL10_DB.SALES_SCHEMA;

USE WAREHOUSE RETAIL10_WH;
USE DATABASE RETAIL10_DB;
USE SCHEMA SALES_SCHEMA;

SELECT
    CURRENT_WAREHOUSE(),
    CURRENT_DATABASE(),
    CURRENT_SCHEMA();

CREATE FILE FORMAT IF NOT EXISTS RETAIL10_CSV_FORMAT
TYPE = 'CSV'
SKIP_HEADER = 1
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE STAGE IF NOT EXISTS RETAIL10_STAGE
FILE_FORMAT = RETAIL10_CSV_FORMAT;

LIST @RETAIL10_STAGE;

CREATE OR REPLACE TABLE CUSTOMER_UPDATES (
    CUSTOMER_ID INTEGER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE
);

COPY INTO CUSTOMER_UPDATES
FROM @RETAIL10_STAGE/customer_updates_project10.csv
FILE_FORMAT = RETAIL10_CSV_FORMAT;

SELECT COUNT(*) AS UPDATE_RECORDS
FROM CUSTOMER_UPDATES;


CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE3 (
    CUSTOMER_KEY INTEGER AUTOINCREMENT,
    CUSTOMER_ID INTEGER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    CURRENT_MEMBERSHIP VARCHAR(30),
    PREVIOUS_MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30)
);

COPY INTO DIM_CUSTOMER_TYPE3
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    SEGMENT
)
FROM (
    SELECT
        $1::INTEGER,
        $2::VARCHAR,
        $3::VARCHAR,
        $4::VARCHAR,
        $5::VARCHAR,
        NULL,
        $6::VARCHAR
    FROM @RETAIL10_STAGE/customers_initial_project10.csv
)
FILE_FORMAT = RETAIL10_CSV_FORMAT;

SELECT
    COUNT(*) AS TOTAL_CUSTOMERS
FROM DIM_CUSTOMER_TYPE3;


SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE3
ORDER BY CUSTOMER_ID;


UPDATE DIM_CUSTOMER_TYPE3 d
SET
    PREVIOUS_MEMBERSHIP = d.CURRENT_MEMBERSHIP,
    CURRENT_MEMBERSHIP = u.MEMBERSHIP,
    CITY = u.CITY,
    STATE = u.STATE,
    SEGMENT = u.SEGMENT
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND d.CURRENT_MEMBERSHIP <> u.MEMBERSHIP;


SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE3
ORDER BY CUSTOMER_ID;


SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE3
WHERE CUSTOMER_ID = 101;


CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE6 (
    CUSTOMER_KEY INTEGER AUTOINCREMENT,
    CUSTOMER_ID INTEGER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    CURRENT_MEMBERSHIP VARCHAR(30),
    PREVIOUS_MEMBERSHIP VARCHAR(30),
    HISTORICAL_MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);

INSERT INTO DIM_CUSTOMER_TYPE6
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    $1::INTEGER,
    $2::VARCHAR,
    $3::VARCHAR,
    $4::VARCHAR,
    $5::VARCHAR,
    NULL,
    $5::VARCHAR,
    $6::VARCHAR,
    '2026-01-01'::DATE,
    '9999-12-31'::DATE,
    TRUE
FROM @RETAIL10_STAGE/customers_initial_project10.csv
(
    FILE_FORMAT => RETAIL10_CSV_FORMAT
);


SELECT
    COUNT(*) AS TOTAL_RECORDS,
    COUNT_IF(IS_CURRENT = TRUE) AS CURRENT_RECORDS
FROM DIM_CUSTOMER_TYPE6;


UPDATE DIM_CUSTOMER_TYPE6 d
SET
    EXPIRY_DATE = DATEADD(DAY, -1, u.EFFECTIVE_DATE),
    IS_CURRENT = FALSE
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND d.IS_CURRENT = TRUE;


INSERT INTO DIM_CUSTOMER_TYPE6
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    u.CUSTOMER_ID,
    u.CUSTOMER_NAME,
    u.CITY,
    u.STATE,
    u.MEMBERSHIP,
    d.CURRENT_MEMBERSHIP,
    d.HISTORICAL_MEMBERSHIP,
    u.SEGMENT,
    u.EFFECTIVE_DATE,
    '9999-12-31'::DATE,
    TRUE
FROM CUSTOMER_UPDATES u
JOIN DIM_CUSTOMER_TYPE6 d
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.EFFECTIVE_DATE = '2026-01-01'
  AND d.IS_CURRENT = FALSE;


SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE6
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;


SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE6
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;


SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER_TYPE6
WHERE CUSTOMER_ID = 101
  AND '2026-03-15'::DATE
      BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;


SELECT
    COUNT(*) AS SCD_TYPE_3_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE3;

SELECT
    COUNT(*) AS SCD_TYPE_6_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE6;

SELECT
    COUNT(*) AS SCD_TYPE_6_CURRENT_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE6
WHERE IS_CURRENT = TRUE;

SELECT
    COUNT(*) AS SCD_TYPE_6_HISTORICAL_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE6
WHERE IS_CURRENT = FALSE;