-- Create warehouse

CREATE WAREHOUSE IF NOT EXISTS RETAIL12_WH
WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;


-- Create database

CREATE DATABASE IF NOT EXISTS RETAIL12_DB;


-- Create schema

CREATE SCHEMA IF NOT EXISTS RETAIL12_DB.RETAIL12_SCHEMA;


-- Use warehouse

USE WAREHOUSE RETAIL12_WH;


-- Use database

USE DATABASE RETAIL12_DB;


-- Use schema

USE SCHEMA RETAIL12_SCHEMA;


-- Check current context

SELECT
    CURRENT_WAREHOUSE(),
    CURRENT_DATABASE(),
    CURRENT_SCHEMA();


-- Create CSV file format

CREATE FILE FORMAT IF NOT EXISTS RETAIL12_CSV_FORMAT
TYPE = 'CSV'
SKIP_HEADER = 1
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"';


-- Create internal stage

CREATE STAGE IF NOT EXISTS RETAIL12_STAGE
FILE_FORMAT = RETAIL12_CSV_FORMAT;


-- Create store staging table

CREATE OR REPLACE TABLE RETAIL12_STG_STORES (
    STORE_ID NUMBER,
    STORE_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    STORE_MANAGER VARCHAR(100)
);


-- Create product staging table

CREATE OR REPLACE TABLE RETAIL12_STG_PRODUCTS (
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(50),
    UNIT_PRICE NUMBER(10,2)
);


-- Create initial customer staging table

CREATE OR REPLACE TABLE RETAIL12_STG_CUSTOMERS_INITIAL (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30)
);


-- Create customer update staging table

CREATE OR REPLACE TABLE RETAIL12_STG_CUSTOMER_UPDATES (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE
);


-- Load stores.csv

COPY INTO RETAIL12_STG_STORES
FROM @RETAIL12_STAGE/stores.csv
FILE_FORMAT = RETAIL12_CSV_FORMAT;


-- Load products.csv

COPY INTO RETAIL12_STG_PRODUCTS
FROM @RETAIL12_STAGE/products.csv
FILE_FORMAT = RETAIL12_CSV_FORMAT;


-- Load customers_initial.csv

COPY INTO RETAIL12_STG_CUSTOMERS_INITIAL
FROM @RETAIL12_STAGE/customers_initial.csv
FILE_FORMAT = RETAIL12_CSV_FORMAT;


-- Load customer_updates.csv

COPY INTO RETAIL12_STG_CUSTOMER_UPDATES
FROM @RETAIL12_STAGE/customer_updates.csv
FILE_FORMAT = RETAIL12_CSV_FORMAT;


-- Create Store dimension

CREATE OR REPLACE TABLE RETAIL12_DIM_STORE (
    STORE_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    STORE_ID NUMBER,
    STORE_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    STORE_MANAGER VARCHAR(100)
);


-- Create Product dimension

CREATE OR REPLACE TABLE RETAIL12_DIM_PRODUCT (
    PRODUCT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(50),
    UNIT_PRICE NUMBER(10,2)
);


-- Create Hybrid Customer dimension

CREATE OR REPLACE TABLE RETAIL12_DIM_CUSTOMER_HYBRID (
    CUSTOMER_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    PREVIOUS_CITY VARCHAR(50),
    STATE VARCHAR(50),
    CURRENT_MEMBERSHIP VARCHAR(30),
    PREVIOUS_MEMBERSHIP VARCHAR(30),
    HISTORICAL_MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);


-- Load Store dimension

INSERT INTO RETAIL12_DIM_STORE (
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    STORE_MANAGER
)
SELECT
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    STORE_MANAGER
FROM RETAIL12_STG_STORES;


-- Load Product dimension

INSERT INTO RETAIL12_DIM_PRODUCT (
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    UNIT_PRICE
)
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    UNIT_PRICE
FROM RETAIL12_STG_PRODUCTS;


-- Load initial Customer dimension

INSERT INTO RETAIL12_DIM_CUSTOMER_HYBRID (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    NULL,
    STATE,
    MEMBERSHIP,
    NULL,
    MEMBERSHIP,
    SEGMENT,
    '2026-01-01',
    '9999-12-31',
    TRUE
FROM RETAIL12_STG_CUSTOMERS_INITIAL;


-- Create Sales fact table

CREATE OR REPLACE TABLE RETAIL12_FACT_SALES (
    SALES_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    TRANSACTION_ID VARCHAR(50),
    TRANSACTION_DATE DATE,
    CUSTOMER_KEY NUMBER,
    STORE_KEY NUMBER,
    PRODUCT_KEY NUMBER,
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(10,2),
    TOTAL_AMOUNT NUMBER(12,2),
    FOREIGN KEY (CUSTOMER_KEY)
        REFERENCES RETAIL12_DIM_CUSTOMER_HYBRID(CUSTOMER_KEY),
    FOREIGN KEY (STORE_KEY)
        REFERENCES RETAIL12_DIM_STORE(STORE_KEY),
    FOREIGN KEY (PRODUCT_KEY)
        REFERENCES RETAIL12_DIM_PRODUCT(PRODUCT_KEY)
);


-- Insert TXN-1001

INSERT INTO RETAIL12_FACT_SALES (
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_KEY,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
)
SELECT
    'TXN-1001',
    '2026-02-15',
    C.CUSTOMER_KEY,
    S.STORE_KEY,
    P.PRODUCT_KEY,
    1,
    P.UNIT_PRICE,
    1 * P.UNIT_PRICE
FROM RETAIL12_DIM_CUSTOMER_HYBRID C
JOIN RETAIL12_DIM_STORE S
    ON S.STORE_ID = 201
JOIN RETAIL12_DIM_PRODUCT P
    ON P.PRODUCT_ID = 501
WHERE C.CUSTOMER_ID = 101
  AND C.IS_CURRENT = TRUE;


-- Insert TXN-1002

INSERT INTO RETAIL12_FACT_SALES (
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_KEY,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
)
SELECT
    'TXN-1002',
    '2026-03-10',
    C.CUSTOMER_KEY,
    S.STORE_KEY,
    P.PRODUCT_KEY,
    2,
    P.UNIT_PRICE,
    2 * P.UNIT_PRICE
FROM RETAIL12_DIM_CUSTOMER_HYBRID C
JOIN RETAIL12_DIM_STORE S
    ON S.STORE_ID = 203
JOIN RETAIL12_DIM_PRODUCT P
    ON P.PRODUCT_ID = 502
WHERE C.CUSTOMER_ID = 103
  AND C.IS_CURRENT = TRUE;


-- Update Store Manager using Type 1

UPDATE RETAIL12_DIM_STORE
SET STORE_MANAGER = 'Suresh Menon'
WHERE STORE_ID = 201;


-- Expire Customer 101

UPDATE RETAIL12_DIM_CUSTOMER_HYBRID
SET
    EXPIRY_DATE = (
        SELECT EFFECTIVE_DATE - 1
        FROM RETAIL12_STG_CUSTOMER_UPDATES
        WHERE CUSTOMER_ID = 101
    ),
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 101
  AND IS_CURRENT = TRUE;


-- Expire Customer 103

UPDATE RETAIL12_DIM_CUSTOMER_HYBRID
SET
    EXPIRY_DATE = (
        SELECT EFFECTIVE_DATE - 1
        FROM RETAIL12_STG_CUSTOMER_UPDATES
        WHERE CUSTOMER_ID = 103
    ),
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 103
  AND IS_CURRENT = TRUE;


-- Expire Customer 104

UPDATE RETAIL12_DIM_CUSTOMER_HYBRID
SET
    EXPIRY_DATE = (
        SELECT EFFECTIVE_DATE - 1
        FROM RETAIL12_STG_CUSTOMER_UPDATES
        WHERE CUSTOMER_ID = 104
    ),
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 104
  AND IS_CURRENT = TRUE;


-- Insert new Customer versions

INSERT INTO RETAIL12_DIM_CUSTOMER_HYBRID (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    U.CUSTOMER_ID,
    U.CUSTOMER_NAME,
    U.CITY,
    OLD.CITY,
    U.STATE,
    U.MEMBERSHIP,
    OLD.CURRENT_MEMBERSHIP,
    U.MEMBERSHIP,
    U.SEGMENT,
    U.EFFECTIVE_DATE,
    '9999-12-31',
    TRUE
FROM RETAIL12_STG_CUSTOMER_UPDATES U
JOIN RETAIL12_DIM_CUSTOMER_HYBRID OLD
    ON OLD.CUSTOMER_ID = U.CUSTOMER_ID
   AND OLD.IS_CURRENT = FALSE
   AND OLD.EXPIRY_DATE = U.EFFECTIVE_DATE - 1;


-- Update Customer 101

UPDATE RETAIL12_DIM_CUSTOMER_HYBRID
SET
    CURRENT_MEMBERSHIP = (
        SELECT MEMBERSHIP
        FROM RETAIL12_STG_CUSTOMER_UPDATES
        WHERE CUSTOMER_ID = 101
    ),
    PREVIOUS_MEMBERSHIP = (
        SELECT MEMBERSHIP
        FROM RETAIL12_STG_CUSTOMERS_INITIAL
        WHERE CUSTOMER_ID = 101
    ),
    CITY = (
        SELECT CITY
        FROM RETAIL12_STG_CUSTOMER_UPDATES
        WHERE CUSTOMER_ID = 101
    ),
    STATE = (
        SELECT STATE
        FROM RETAIL12_STG_CUSTOMER_UPDATES
        WHERE CUSTOMER_ID = 101
    )
WHERE CUSTOMER_ID = 101;


-- Update Customer 103

UPDATE RETAIL12_DIM_CUSTOMER_HYBRID
SET
    CURRENT_MEMBERSHIP = (
        SELECT MEMBERSHIP
        FROM RETAIL12_STG_CUSTOMER_UPDATES
        WHERE CUSTOMER_ID = 103
    ),
    PREVIOUS_MEMBERSHIP = (
        SELECT MEMBERSHIP
        FROM RETAIL12_STG_CUSTOMERS_INITIAL
        WHERE CUSTOMER_ID = 103
    ),
    CITY = (
        SELECT CITY
        FROM RETAIL12_STG_CUSTOMER_UPDATES
        WHERE CUSTOMER_ID = 103
    ),
    STATE = (
        SELECT STATE
        FROM RETAIL12_STG_CUSTOMER_UPDATES
        WHERE CUSTOMER_ID = 103
    )
WHERE CUSTOMER_ID = 103;


-- Update Customer 104

UPDATE RETAIL12_DIM_CUSTOMER_HYBRID
SET
    CURRENT_MEMBERSHIP = (
        SELECT MEMBERSHIP
        FROM RETAIL12_STG_CUSTOMER_UPDATES
        WHERE CUSTOMER_ID = 104
    ),
    PREVIOUS_MEMBERSHIP = (
        SELECT MEMBERSHIP
        FROM RETAIL12_STG_CUSTOMERS_INITIAL
        WHERE CUSTOMER_ID = 104
    ),
    CITY = (
        SELECT CITY
        FROM RETAIL12_STG_CUSTOMER_UPDATES
        WHERE CUSTOMER_ID = 104
    ),
    STATE = (
        SELECT STATE
        FROM RETAIL12_STG_CUSTOMER_UPDATES
        WHERE CUSTOMER_ID = 104
    )
WHERE CUSTOMER_ID = 104;


-- Insert TXN-2001

INSERT INTO RETAIL12_FACT_SALES (
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_KEY,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
)
SELECT
    'TXN-2001',
    '2026-04-15',
    C.CUSTOMER_KEY,
    S.STORE_KEY,
    P.PRODUCT_KEY,
    1,
    P.UNIT_PRICE,
    1 * P.UNIT_PRICE
FROM RETAIL12_DIM_CUSTOMER_HYBRID C
JOIN RETAIL12_DIM_STORE S
    ON S.STORE_ID = 201
JOIN RETAIL12_DIM_PRODUCT P
    ON P.PRODUCT_ID = 503
WHERE C.CUSTOMER_ID = 101
  AND C.IS_CURRENT = TRUE;


-- Display complete Customer history

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM RETAIL12_DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;


-- Point-in-time POS analytics

SELECT
    F.TRANSACTION_ID,
    F.TRANSACTION_DATE,
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.CITY AS CURRENT_CITY,
    C.HISTORICAL_MEMBERSHIP AS MEMBERSHIP_AT_PURCHASE,
    C.SEGMENT AS SEGMENT_AT_PURCHASE,
    S.STORE_NAME,
    P.PRODUCT_NAME,
    F.TOTAL_AMOUNT
FROM RETAIL12_FACT_SALES F
JOIN RETAIL12_DIM_CUSTOMER_HYBRID C
    ON F.CUSTOMER_KEY = C.CUSTOMER_KEY
JOIN RETAIL12_DIM_STORE S
    ON F.STORE_KEY = S.STORE_KEY
JOIN RETAIL12_DIM_PRODUCT P
    ON F.PRODUCT_KEY = P.PRODUCT_KEY
WHERE C.CUSTOMER_ID = 101
ORDER BY F.TRANSACTION_DATE;


-- Validate warehouse record counts

SELECT
    'STORE DIMENSION RECORDS' AS METRIC,
    COUNT(*) AS VALUE
FROM RETAIL12_DIM_STORE

UNION ALL

SELECT
    'PRODUCT DIMENSION RECORDS',
    COUNT(*)
FROM RETAIL12_DIM_PRODUCT

UNION ALL

SELECT
    'TOTAL CUSTOMER DIMENSION RECORDS',
    COUNT(*)
FROM RETAIL12_DIM_CUSTOMER_HYBRID

UNION ALL

SELECT
    'CURRENT CUSTOMER RECORDS',
    COUNT(*)
FROM RETAIL12_DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = TRUE

UNION ALL

SELECT
    'HISTORICAL CUSTOMER RECORDS',
    COUNT(*)
FROM RETAIL12_DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = FALSE

UNION ALL

SELECT
    'FACT SALES TRANSACTIONS',
    COUNT(*)
FROM RETAIL12_FACT_SALES;