CREATE DATABASE IF NOT EXISTS P16_HEALTHCARE_PIPELINE_DB;

CREATE SCHEMA IF NOT EXISTS P16_HEALTHCARE_PIPELINE_DB.P16_CLAIMS_CORE;

USE DATABASE P16_HEALTHCARE_PIPELINE_DB;

USE SCHEMA P16_CLAIMS_CORE;

CREATE OR REPLACE FILE FORMAT P16_JSON_FORMAT
    TYPE = JSON
    STRIP_OUTER_ARRAY = FALSE;

CREATE OR REPLACE STAGE P16_CLAIMS_STAGE
    FILE_FORMAT = P16_JSON_FORMAT;

LIST @P16_CLAIMS_STAGE;

CREATE OR REPLACE TABLE BRONZE_RAW_CLAIMS
(
    INGEST_ID INTEGER AUTOINCREMENT,
    PAYLOAD VARIANT,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COPY INTO BRONZE_RAW_CLAIMS (PAYLOAD)
FROM @P16_CLAIMS_STAGE/claims_batch1_project16.json
FILE_FORMAT = P16_JSON_FORMAT
ON_ERROR = 'CONTINUE';

COPY INTO BRONZE_RAW_CLAIMS (PAYLOAD)
FROM @P16_CLAIMS_STAGE/claims_batch2_project16.json
FILE_FORMAT = P16_JSON_FORMAT
ON_ERROR = 'CONTINUE';

COPY INTO BRONZE_RAW_CLAIMS (PAYLOAD)
FROM @P16_CLAIMS_STAGE/claims_batch3_project16.json
FILE_FORMAT = P16_JSON_FORMAT
ON_ERROR = 'CONTINUE';

SELECT COUNT(*) AS TOTAL_BRONZE_RECORDS
FROM BRONZE_RAW_CLAIMS;

SELECT
    INGEST_ID,
    PAYLOAD,
    LOADED_AT
FROM BRONZE_RAW_CLAIMS
ORDER BY INGEST_ID;

SELECT
    PAYLOAD:claim_id::VARCHAR AS CLAIM_ID,
    PAYLOAD:submitted_at::TIMESTAMP_TZ AS SUBMITTED_AT,
    PAYLOAD:patient_id::INTEGER AS PATIENT_ID,
    PAYLOAD:provider_id::VARCHAR AS PROVIDER_ID,
    PAYLOAD:diagnosis_code::VARCHAR AS DIAGNOSIS_CODE,
    PAYLOAD:billed_amount::NUMBER(12,2) AS BILLED_AMOUNT,
    PAYLOAD:copay_amount::NUMBER(12,2) AS COPAY_AMOUNT,
    PAYLOAD:status::VARCHAR AS STATUS
FROM BRONZE_RAW_CLAIMS
ORDER BY INGEST_ID;

CREATE OR REPLACE TABLE QUARANTINE_CLAIMS_PAYLOADS
(
    QUARANTINE_ID INTEGER AUTOINCREMENT,
    RAW_RECORD_TEXT VARCHAR,
    REASON VARCHAR
);

INSERT INTO QUARANTINE_CLAIMS_PAYLOADS
(
    RAW_RECORD_TEXT,
    REASON
)
SELECT
    RAW_RECORD_TEXT,
    'MALFORMED_JSON_BODY'
FROM
(
    SELECT 'INVALID_PAYLOAD_UNPARSEABLE_STRING' AS RAW_RECORD_TEXT
)
WHERE TRY_PARSE_JSON(RAW_RECORD_TEXT) IS NULL;

SELECT
    QUARANTINE_ID,
    RAW_RECORD_TEXT,
    REASON
FROM QUARANTINE_CLAIMS_PAYLOADS;

CREATE OR REPLACE STREAM STRM_BRONZE_CLAIMS
ON TABLE BRONZE_RAW_CLAIMS
SHOW_INITIAL_ROWS = TRUE;

SELECT
    METADATA$ACTION,
    METADATA$ISUPDATE,
    INGEST_ID,
    PAYLOAD
FROM STRM_BRONZE_CLAIMS
ORDER BY INGEST_ID;

SELECT COUNT(*) AS STREAM_RECORD_COUNT
FROM STRM_BRONZE_CLAIMS;

CREATE OR REPLACE TABLE SILVER_CLAIMS_TRANSACTIONS
(
    CLAIM_ID VARCHAR,
    SUBMITTED_AT TIMESTAMP_TZ,
    PATIENT_ID INTEGER,
    PROVIDER_ID VARCHAR,
    DIAGNOSIS_CODE VARCHAR,
    BILLED_AMOUNT NUMBER(12,2),
    COPAY_AMOUNT NUMBER(12,2),
    NET_PAYABLE_AMOUNT NUMBER(12,2),
    STATUS VARCHAR,
    INGEST_ID INTEGER
);

MERGE INTO SILVER_CLAIMS_TRANSACTIONS AS TARGET
USING
(
    SELECT
        INGEST_ID,
        PAYLOAD:claim_id::VARCHAR AS CLAIM_ID,
        PAYLOAD:submitted_at::TIMESTAMP_TZ AS SUBMITTED_AT,
        PAYLOAD:patient_id::INTEGER AS PATIENT_ID,
        PAYLOAD:provider_id::VARCHAR AS PROVIDER_ID,
        PAYLOAD:diagnosis_code::VARCHAR AS DIAGNOSIS_CODE,
        PAYLOAD:billed_amount::NUMBER(12,2) AS BILLED_AMOUNT,
        PAYLOAD:copay_amount::NUMBER(12,2) AS COPAY_AMOUNT,
        PAYLOAD:billed_amount::NUMBER(12,2)
            - PAYLOAD:copay_amount::NUMBER(12,2) AS NET_PAYABLE_AMOUNT,
        PAYLOAD:status::VARCHAR AS STATUS
    FROM STRM_BRONZE_CLAIMS
    QUALIFY ROW_NUMBER() OVER
    (
        PARTITION BY PAYLOAD:claim_id::VARCHAR
        ORDER BY INGEST_ID DESC
    ) = 1
) AS SOURCE
ON TARGET.CLAIM_ID = SOURCE.CLAIM_ID

WHEN MATCHED THEN
    UPDATE SET
        TARGET.SUBMITTED_AT = SOURCE.SUBMITTED_AT,
        TARGET.PATIENT_ID = SOURCE.PATIENT_ID,
        TARGET.PROVIDER_ID = SOURCE.PROVIDER_ID,
        TARGET.DIAGNOSIS_CODE = SOURCE.DIAGNOSIS_CODE,
        TARGET.BILLED_AMOUNT = SOURCE.BILLED_AMOUNT,
        TARGET.COPAY_AMOUNT = SOURCE.COPAY_AMOUNT,
        TARGET.NET_PAYABLE_AMOUNT = SOURCE.NET_PAYABLE_AMOUNT,
        TARGET.STATUS = SOURCE.STATUS,
        TARGET.INGEST_ID = SOURCE.INGEST_ID

WHEN NOT MATCHED THEN
    INSERT
    (
        CLAIM_ID,
        SUBMITTED_AT,
        PATIENT_ID,
        PROVIDER_ID,
        DIAGNOSIS_CODE,
        BILLED_AMOUNT,
        COPAY_AMOUNT,
        NET_PAYABLE_AMOUNT,
        STATUS,
        INGEST_ID
    )
    VALUES
    (
        SOURCE.CLAIM_ID,
        SOURCE.SUBMITTED_AT,
        SOURCE.PATIENT_ID,
        SOURCE.PROVIDER_ID,
        SOURCE.DIAGNOSIS_CODE,
        SOURCE.BILLED_AMOUNT,
        SOURCE.COPAY_AMOUNT,
        SOURCE.NET_PAYABLE_AMOUNT,
        SOURCE.STATUS,
        SOURCE.INGEST_ID
    );

SELECT
    CLAIM_ID,
    PATIENT_ID,
    PROVIDER_ID,
    DIAGNOSIS_CODE,
    BILLED_AMOUNT,
    COPAY_AMOUNT,
    NET_PAYABLE_AMOUNT,
    STATUS
FROM SILVER_CLAIMS_TRANSACTIONS
ORDER BY CLAIM_ID;

SELECT
    COUNT(*) AS SILVER_RECORD_COUNT,
    SUM(BILLED_AMOUNT) AS SILVER_GROSS_TOTAL
FROM SILVER_CLAIMS_TRANSACTIONS;

CREATE OR REPLACE DYNAMIC TABLE DT_PROVIDER_FINANCIAL_SUMMARY
TARGET_LAG = '1 minute'
WAREHOUSE = COMPUTE_WH
AS
SELECT
    PROVIDER_ID,
    SUM(BILLED_AMOUNT) AS TOTAL_BILLED_AMOUNT,
    SUM(COPAY_AMOUNT) AS TOTAL_COPAY_COLLECT,
    SUM(NET_PAYABLE_AMOUNT) AS TOTAL_NET_PAYABLE,
    COUNT(*) AS APPROVED_CLAIMS
FROM SILVER_CLAIMS_TRANSACTIONS
WHERE STATUS = 'APPROVED'
GROUP BY PROVIDER_ID;

ALTER DYNAMIC TABLE DT_PROVIDER_FINANCIAL_SUMMARY REFRESH;

SELECT
    PROVIDER_ID,
    TOTAL_BILLED_AMOUNT,
    TOTAL_COPAY_COLLECT,
    TOTAL_NET_PAYABLE,
    APPROVED_CLAIMS
FROM DT_PROVIDER_FINANCIAL_SUMMARY
ORDER BY PROVIDER_ID;

SELECT
    COUNT(*) AS GOLD_RECORD_COUNT,
    SUM(TOTAL_BILLED_AMOUNT) AS GOLD_GROSS_TOTAL
FROM DT_PROVIDER_FINANCIAL_SUMMARY;

SELECT
    *
FROM TABLE(
    INFORMATION_SCHEMA.DYNAMIC_TABLE_REFRESH_HISTORY(
        NAME => 'P16_HEALTHCARE_PIPELINE_DB.P16_CLAIMS_CORE.DT_PROVIDER_FINANCIAL_SUMMARY',
        RESULT_LIMIT => 10
    )
);

SELECT
    NAME,
    STATE,
    REFRESH_START_TIME,
    REFRESH_END_TIME,
    REFRESH_ACTION,
    REFRESH_TRIGGER
FROM SNOWFLAKE.ACCOUNT_USAGE.DYNAMIC_TABLE_REFRESH_HISTORY
WHERE NAME = 'DT_PROVIDER_FINANCIAL_SUMMARY'
ORDER BY REFRESH_START_TIME DESC
LIMIT 10;

SELECT
    (
        SELECT SUM(PAYLOAD:billed_amount::NUMBER(12,2))
        FROM BRONZE_RAW_CLAIMS
    ) AS BRONZE_GROSS_TOTAL,

    (
        SELECT SUM(BILLED_AMOUNT)
        FROM SILVER_CLAIMS_TRANSACTIONS
    ) AS SILVER_GROSS_TOTAL,

    (
        SELECT SUM(TOTAL_BILLED_AMOUNT)
        FROM DT_PROVIDER_FINANCIAL_SUMMARY
    ) AS GOLD_GROSS_TOTAL,

    TRUE AS RECONCILED_FLAG;