-- Task 1: Create warehouse

CREATE WAREHOUSE IF NOT EXISTS RETAIL13B_WH
WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

-- Create database

CREATE DATABASE IF NOT EXISTS RETAIL13B_DW;

-- Create schema

CREATE SCHEMA IF NOT EXISTS RETAIL13B_DW.SCHEMA13B_COMPARE;

-- Set context

USE WAREHOUSE RETAIL13B_WH;
USE DATABASE RETAIL13B_DW;
USE SCHEMA SCHEMA13B_COMPARE;

SELECT
    CURRENT_WAREHOUSE(),
    CURRENT_DATABASE(),
    CURRENT_SCHEMA();


-- Create file format

CREATE FILE FORMAT IF NOT EXISTS RETAIL13B_CSV_FORMAT
TYPE = 'CSV'
SKIP_HEADER = 1
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"';


-- Create stage

CREATE STAGE IF NOT EXISTS RETAIL13B_STAGE
FILE_FORMAT = RETAIL13B_CSV_FORMAT;


-- Create source tables

CREATE OR REPLACE TABLE RETAIL13B_RAW_HOSPITAL_HIERARCHY (
    HOSPITAL_ID NUMBER,
    HOSPITAL_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    NETWORK_ID NUMBER,
    NETWORK_NAME VARCHAR(100),
    NETWORK_DIRECTOR VARCHAR(100)
);

CREATE OR REPLACE TABLE RETAIL13B_RAW_TREATMENT_HIERARCHY (
    TREATMENT_ID NUMBER,
    TREATMENT_NAME VARCHAR(100),
    DIAGNOSIS_GROUP_ID VARCHAR(30),
    DIAGNOSIS_GROUP_NAME VARCHAR(50),
    STANDARD_COST NUMBER(12,2)
);

CREATE OR REPLACE TABLE RETAIL13B_RAW_PATIENTS (
    PATIENT_ID NUMBER,
    PATIENT_NAME VARCHAR(100),
    GENDER VARCHAR(20),
    AGE NUMBER,
    CITY VARCHAR(50)
);

CREATE OR REPLACE TABLE RETAIL13B_RAW_INSURANCE_CLAIMS (
    CLAIM_ID VARCHAR(50),
    CLAIM_DATE DATE,
    PATIENT_ID NUMBER,
    HOSPITAL_ID NUMBER,
    TREATMENT_ID NUMBER,
    CLAIMED_AMOUNT NUMBER(12,2),
    APPROVED_AMOUNT NUMBER(12,2)
);


-- Load hospital source file

COPY INTO RETAIL13B_RAW_HOSPITAL_HIERARCHY
FROM @RETAIL13B_STAGE/RETAIL13B_HOSPITAL_HIERARCHY.csv
FILE_FORMAT = RETAIL13B_CSV_FORMAT;


-- Load treatment source file

COPY INTO RETAIL13B_RAW_TREATMENT_HIERARCHY
FROM @RETAIL13B_STAGE/RETAIL13B_TREATMENT_HIERARCHY.csv
FILE_FORMAT = RETAIL13B_CSV_FORMAT;


-- Load patient source file

COPY INTO RETAIL13B_RAW_PATIENTS
FROM @RETAIL13B_STAGE/RETAIL13B_PATIENTS.csv
FILE_FORMAT = RETAIL13B_CSV_FORMAT;


-- Load claims source file

COPY INTO RETAIL13B_RAW_INSURANCE_CLAIMS
FROM @RETAIL13B_STAGE/RETAIL13B_INSURANCE_CLAIMS.csv
FILE_FORMAT = RETAIL13B_CSV_FORMAT;


-- Task 2: Create Star hospital dimension

CREATE OR REPLACE TABLE STAR_DIM_HOSPITAL (
    HOSPITAL_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    HOSPITAL_ID NUMBER,
    HOSPITAL_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    NETWORK_NAME VARCHAR(100),
    NETWORK_DIRECTOR VARCHAR(100)
);


-- Task 3: Create Star treatment dimension

CREATE OR REPLACE TABLE STAR_DIM_TREATMENT (
    TREATMENT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    TREATMENT_ID NUMBER,
    TREATMENT_NAME VARCHAR(100),
    DIAGNOSIS_GROUP_NAME VARCHAR(50),
    STANDARD_COST NUMBER(12,2)
);


-- Task 4: Load Star hospital dimension

INSERT INTO STAR_DIM_HOSPITAL (
    HOSPITAL_ID,
    HOSPITAL_NAME,
    CITY,
    STATE,
    NETWORK_NAME,
    NETWORK_DIRECTOR
)
SELECT
    HOSPITAL_ID,
    HOSPITAL_NAME,
    CITY,
    STATE,
    NETWORK_NAME,
    NETWORK_DIRECTOR
FROM RETAIL13B_RAW_HOSPITAL_HIERARCHY;


-- Load Star treatment dimension

INSERT INTO STAR_DIM_TREATMENT (
    TREATMENT_ID,
    TREATMENT_NAME,
    DIAGNOSIS_GROUP_NAME,
    STANDARD_COST
)
SELECT
    TREATMENT_ID,
    TREATMENT_NAME,
    DIAGNOSIS_GROUP_NAME,
    STANDARD_COST
FROM RETAIL13B_RAW_TREATMENT_HIERARCHY;


-- Task 5: Create Star claims fact

CREATE OR REPLACE TABLE STAR_FACT_CLAIMS (
    CLAIM_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CLAIM_ID VARCHAR(50),
    CLAIM_DATE DATE,
    PATIENT_ID NUMBER,
    HOSPITAL_KEY NUMBER,
    TREATMENT_KEY NUMBER,
    CLAIMED_AMOUNT NUMBER(12,2),
    APPROVED_AMOUNT NUMBER(12,2),
    FOREIGN KEY (HOSPITAL_KEY) REFERENCES STAR_DIM_HOSPITAL(HOSPITAL_KEY),
    FOREIGN KEY (TREATMENT_KEY) REFERENCES STAR_DIM_TREATMENT(TREATMENT_KEY)
);


-- Load Star claims fact

INSERT INTO STAR_FACT_CLAIMS (
    CLAIM_ID,
    CLAIM_DATE,
    PATIENT_ID,
    HOSPITAL_KEY,
    TREATMENT_KEY,
    CLAIMED_AMOUNT,
    APPROVED_AMOUNT
)
SELECT
    C.CLAIM_ID,
    C.CLAIM_DATE,
    C.PATIENT_ID,
    H.HOSPITAL_KEY,
    T.TREATMENT_KEY,
    C.CLAIMED_AMOUNT,
    C.APPROVED_AMOUNT
FROM RETAIL13B_RAW_INSURANCE_CLAIMS C
JOIN STAR_DIM_HOSPITAL H
    ON C.HOSPITAL_ID = H.HOSPITAL_ID
JOIN STAR_DIM_TREATMENT T
    ON C.TREATMENT_ID = T.TREATMENT_ID;


-- Task 6: Create Snowflake network dimension

CREATE OR REPLACE TABLE SNOW_DIM_NETWORK (
    NETWORK_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    NETWORK_ID NUMBER,
    NETWORK_NAME VARCHAR(100),
    NETWORK_DIRECTOR VARCHAR(100)
);


-- Create Snowflake hospital dimension

CREATE OR REPLACE TABLE SNOW_DIM_HOSPITAL (
    HOSPITAL_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    HOSPITAL_ID NUMBER,
    HOSPITAL_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    NETWORK_KEY NUMBER,
    FOREIGN KEY (NETWORK_KEY) REFERENCES SNOW_DIM_NETWORK(NETWORK_KEY)
);


-- Task 7: Create diagnosis group dimension

CREATE OR REPLACE TABLE SNOW_DIM_DIAGNOSIS_GROUP (
    DIAGNOSIS_GROUP_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    DIAGNOSIS_GROUP_ID VARCHAR(30),
    DIAGNOSIS_GROUP_NAME VARCHAR(50)
);


-- Create treatment dimension

CREATE OR REPLACE TABLE SNOW_DIM_TREATMENT (
    TREATMENT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    TREATMENT_ID NUMBER,
    TREATMENT_NAME VARCHAR(100),
    STANDARD_COST NUMBER(12,2),
    DIAGNOSIS_GROUP_KEY NUMBER,
    FOREIGN KEY (DIAGNOSIS_GROUP_KEY)
        REFERENCES SNOW_DIM_DIAGNOSIS_GROUP(DIAGNOSIS_GROUP_KEY)
);


-- Task 8: Load Snowflake network dimension

INSERT INTO SNOW_DIM_NETWORK (
    NETWORK_ID,
    NETWORK_NAME,
    NETWORK_DIRECTOR
)
SELECT
    NETWORK_ID,
    NETWORK_NAME,
    NETWORK_DIRECTOR
FROM RETAIL13B_RAW_HOSPITAL_HIERARCHY
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY NETWORK_ID
    ORDER BY HOSPITAL_ID
) = 1;


-- Load Snowflake hospital dimension

INSERT INTO SNOW_DIM_HOSPITAL (
    HOSPITAL_ID,
    HOSPITAL_NAME,
    CITY,
    STATE,
    NETWORK_KEY
)
SELECT
    H.HOSPITAL_ID,
    H.HOSPITAL_NAME,
    H.CITY,
    H.STATE,
    N.NETWORK_KEY
FROM RETAIL13B_RAW_HOSPITAL_HIERARCHY H
JOIN SNOW_DIM_NETWORK N
    ON H.NETWORK_ID = N.NETWORK_ID;


-- Load Snowflake diagnosis groups

INSERT INTO SNOW_DIM_DIAGNOSIS_GROUP (
    DIAGNOSIS_GROUP_ID,
    DIAGNOSIS_GROUP_NAME
)
SELECT
    DIAGNOSIS_GROUP_ID,
    DIAGNOSIS_GROUP_NAME
FROM RETAIL13B_RAW_TREATMENT_HIERARCHY
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY DIAGNOSIS_GROUP_ID
    ORDER BY TREATMENT_ID
) = 1;


-- Load Snowflake treatments

INSERT INTO SNOW_DIM_TREATMENT (
    TREATMENT_ID,
    TREATMENT_NAME,
    STANDARD_COST,
    DIAGNOSIS_GROUP_KEY
)
SELECT
    T.TREATMENT_ID,
    T.TREATMENT_NAME,
    T.STANDARD_COST,
    D.DIAGNOSIS_GROUP_KEY
FROM RETAIL13B_RAW_TREATMENT_HIERARCHY T
JOIN SNOW_DIM_DIAGNOSIS_GROUP D
    ON T.DIAGNOSIS_GROUP_ID = D.DIAGNOSIS_GROUP_ID;


-- Task 9: Create Snowflake claims fact

CREATE OR REPLACE TABLE SNOW_FACT_CLAIMS (
    CLAIM_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CLAIM_ID VARCHAR(50),
    CLAIM_DATE DATE,
    PATIENT_ID NUMBER,
    HOSPITAL_KEY NUMBER,
    TREATMENT_KEY NUMBER,
    CLAIMED_AMOUNT NUMBER(12,2),
    APPROVED_AMOUNT NUMBER(12,2),
    FOREIGN KEY (HOSPITAL_KEY) REFERENCES SNOW_DIM_HOSPITAL(HOSPITAL_KEY),
    FOREIGN KEY (TREATMENT_KEY) REFERENCES SNOW_DIM_TREATMENT(TREATMENT_KEY)
);


-- Load Snowflake claims fact

INSERT INTO SNOW_FACT_CLAIMS (
    CLAIM_ID,
    CLAIM_DATE,
    PATIENT_ID,
    HOSPITAL_KEY,
    TREATMENT_KEY,
    CLAIMED_AMOUNT,
    APPROVED_AMOUNT
)
SELECT
    C.CLAIM_ID,
    C.CLAIM_DATE,
    C.PATIENT_ID,
    H.HOSPITAL_KEY,
    T.TREATMENT_KEY,
    C.CLAIMED_AMOUNT,
    C.APPROVED_AMOUNT
FROM RETAIL13B_RAW_INSURANCE_CLAIMS C
JOIN SNOW_DIM_HOSPITAL H
    ON C.HOSPITAL_ID = H.HOSPITAL_ID
JOIN SNOW_DIM_TREATMENT T
    ON C.TREATMENT_ID = T.TREATMENT_ID;


-- Task 10: Star schema specialty claims analysis

SELECT
    T.DIAGNOSIS_GROUP_NAME,
    SUM(F.CLAIMED_AMOUNT) AS TOTAL_CLAIMED_AMOUNT,
    SUM(F.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM STAR_FACT_CLAIMS F
JOIN STAR_DIM_TREATMENT T
    ON F.TREATMENT_KEY = T.TREATMENT_KEY
GROUP BY T.DIAGNOSIS_GROUP_NAME
ORDER BY T.DIAGNOSIS_GROUP_NAME;


-- Task 11: Snowflake schema specialty claims analysis

SELECT
    D.DIAGNOSIS_GROUP_NAME,
    SUM(F.CLAIMED_AMOUNT) AS TOTAL_CLAIMED_AMOUNT,
    SUM(F.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM SNOW_FACT_CLAIMS F
JOIN SNOW_DIM_TREATMENT T
    ON F.TREATMENT_KEY = T.TREATMENT_KEY
JOIN SNOW_DIM_DIAGNOSIS_GROUP D
    ON T.DIAGNOSIS_GROUP_KEY = D.DIAGNOSIS_GROUP_KEY
GROUP BY D.DIAGNOSIS_GROUP_NAME
ORDER BY D.DIAGNOSIS_GROUP_NAME;


-- Task 12: Hospital network director performance

SELECT
    H.NETWORK_DIRECTOR,
    COUNT(F.CLAIM_ID) AS TOTAL_CLAIMS_HANDLED,
    SUM(F.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM STAR_FACT_CLAIMS F
JOIN STAR_DIM_HOSPITAL H
    ON F.HOSPITAL_KEY = H.HOSPITAL_KEY
GROUP BY H.NETWORK_DIRECTOR
ORDER BY H.NETWORK_DIRECTOR;


-- Task 13: Star schema update effort

SELECT
    'STAR SCHEMA' AS SCHEMA_TYPE,
    'STAR_DIM_HOSPITAL' AS UPDATED_TABLE,
    COUNT(*) AS ROWS_UPDATED,
    'Update every hospital row belonging to Network 10' AS MAINTENANCE_EFFORT
FROM STAR_DIM_HOSPITAL
WHERE NETWORK_NAME = 'Apollo Healthcare Group';


-- Task 13: Snowflake schema update effort

SELECT
    'SNOWFLAKE SCHEMA' AS SCHEMA_TYPE,
    'SNOW_DIM_NETWORK' AS UPDATED_TABLE,
    COUNT(*) AS ROWS_UPDATED,
    'Update one network master row' AS MAINTENANCE_EFFORT
FROM SNOW_DIM_NETWORK
WHERE NETWORK_ID = 10;


-- Task 14: Full architecture record audit

SELECT
    'Star Schema' AS SCHEMA_TYPE,
    'STAR_DIM_HOSPITAL' AS TABLE_NAME,
    COUNT(*) AS RECORD_COUNT
FROM STAR_DIM_HOSPITAL

UNION ALL

SELECT
    'Star Schema',
    'STAR_DIM_TREATMENT',
    COUNT(*)
FROM STAR_DIM_TREATMENT

UNION ALL

SELECT
    'Star Schema',
    'STAR_FACT_CLAIMS',
    COUNT(*)
FROM STAR_FACT_CLAIMS

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_NETWORK',
    COUNT(*)
FROM SNOW_DIM_NETWORK

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_HOSPITAL',
    COUNT(*)
FROM SNOW_DIM_HOSPITAL

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_DIAGNOSIS_GROUP',
    COUNT(*)
FROM SNOW_DIM_DIAGNOSIS_GROUP

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_TREATMENT',
    COUNT(*)
FROM SNOW_DIM_TREATMENT

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_FACT_CLAIMS',
    COUNT(*)
FROM SNOW_FACT_CLAIMS;