CREATE OR REPLACE DATABASE LOGISTICS_LAKEHOUSE_DB;

CREATE OR REPLACE SCHEMA LOGISTICS_LAKEHOUSE_DB.FLEET_CORE;

USE DATABASE LOGISTICS_LAKEHOUSE_DB;

USE SCHEMA FLEET_CORE;

CREATE OR REPLACE FILE FORMAT PROJECT15_RAW_FILE_FORMAT
TYPE = CSV
FIELD_DELIMITER = '|'
SKIP_HEADER = 0;

CREATE OR REPLACE STAGE PROJECT15_IOT_STAGE
FILE_FORMAT = PROJECT15_RAW_FILE_FORMAT;

CREATE OR REPLACE TABLE PROJECT15_RAW_IOT_LANDING (
    RAW_RECORD_TEXT VARCHAR
);

COPY INTO PROJECT15_RAW_IOT_LANDING
FROM @PROJECT15_IOT_STAGE/PROJECT15_IOT_STREAMS.json
FILE_FORMAT = (FORMAT_NAME = PROJECT15_RAW_FILE_FORMAT)
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE BRONZE_IOT_STREAMS (
    INGEST_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    RAW_PAYLOAD VARIANT,
    RECORDED_AT TIMESTAMP_NTZ
);

INSERT INTO BRONZE_IOT_STREAMS (
    RAW_PAYLOAD,
    RECORDED_AT
)
SELECT
    TRY_PARSE_JSON(RAW_RECORD_TEXT),
    CURRENT_TIMESTAMP()
FROM PROJECT15_RAW_IOT_LANDING
WHERE TRY_PARSE_JSON(RAW_RECORD_TEXT) IS NOT NULL;

SELECT COUNT(*) AS TOTAL_BRONZE_RECORDS
FROM BRONZE_IOT_STREAMS;

SELECT
    RAW_PAYLOAD:payload_id::VARCHAR AS PAYLOAD_ID,
    RAW_PAYLOAD:payload_type::VARCHAR AS PAYLOAD_TYPE,
    RAW_PAYLOAD:timestamp::TIMESTAMP_NTZ AS EVENT_TIME,
    RAW_PAYLOAD:data:vehicle_id::VARCHAR AS VEHICLE_ID,
    RAW_PAYLOAD:data:shipment_id::VARCHAR AS SHIPMENT_ID,
    RAW_PAYLOAD:data:declared_value::NUMBER(12,2) AS DECLARED_VALUE
FROM BRONZE_IOT_STREAMS
ORDER BY EVENT_TIME;

CREATE OR REPLACE TABLE QUARANTINE_IOT_PAYLOADS (
    QUARANTINE_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    RAW_RECORD_TEXT VARCHAR,
    REASON VARCHAR(100)
);

INSERT INTO QUARANTINE_IOT_PAYLOADS (
    RAW_RECORD_TEXT,
    REASON
)
SELECT
    RAW_RECORD_TEXT,
    'MALFORMED_JSON_BODY'
FROM PROJECT15_RAW_IOT_LANDING
WHERE TRY_PARSE_JSON(RAW_RECORD_TEXT) IS NULL;

SELECT
    QUARANTINE_ID,
    RAW_RECORD_TEXT,
    REASON
FROM QUARANTINE_IOT_PAYLOADS;

CREATE OR REPLACE TABLE SILVER_CUSTOMS_CLEARANCE (
    SHIPMENT_ID VARCHAR(50),
    PAYLOAD_ID VARCHAR(50),
    VEHICLE_ID VARCHAR(50),
    DESTINATION_COUNTRY VARCHAR(10),
    DECLARED_VALUE NUMBER(12,2),
    DUTY_PCT NUMBER(5,2),
    DUTY_AMOUNT_DUE NUMBER(12,2),
    BORDER_CODE VARCHAR(100),
    CLEARANCE_STATUS VARCHAR(50)
);

INSERT INTO SILVER_CUSTOMS_CLEARANCE (
    SHIPMENT_ID,
    PAYLOAD_ID,
    VEHICLE_ID,
    DESTINATION_COUNTRY,
    DECLARED_VALUE,
    DUTY_PCT,
    DUTY_AMOUNT_DUE,
    BORDER_CODE,
    CLEARANCE_STATUS
)
SELECT
    RAW_PAYLOAD:data:shipment_id::VARCHAR,
    RAW_PAYLOAD:payload_id::VARCHAR,
    RAW_PAYLOAD:data:vehicle_id::VARCHAR,
    RAW_PAYLOAD:data:destination_country::VARCHAR,
    RAW_PAYLOAD:data:declared_value::NUMBER(12,2),
    RAW_PAYLOAD:data:duty_pct::NUMBER(5,2),
    (
        RAW_PAYLOAD:data:declared_value::NUMBER(12,2)
        * RAW_PAYLOAD:data:duty_pct::NUMBER(5,2) / 100
    )::NUMBER(12,2),
    RAW_PAYLOAD:data:border_clearance_code::VARCHAR,
    RAW_PAYLOAD:data:clearance_status::VARCHAR
FROM BRONZE_IOT_STREAMS
WHERE RAW_PAYLOAD:payload_type::VARCHAR = 'CUSTOMS';

SELECT
    SHIPMENT_ID,
    VEHICLE_ID,
    DESTINATION_COUNTRY AS DEST_COUNTRY,
    DECLARED_VALUE,
    DUTY_PCT,
    DUTY_AMOUNT_DUE,
    BORDER_CODE,
    CLEARANCE_STATUS
FROM SILVER_CUSTOMS_CLEARANCE
ORDER BY SHIPMENT_ID;

CREATE OR REPLACE TABLE GOLD_COUNTRY_DUTY_SUMMARY AS
SELECT
    DESTINATION_COUNTRY AS DEST_COUNTRY,
    SUM(DECLARED_VALUE)::NUMBER(12,2) AS TOTAL_CLEARED_VAL,
    SUM(DUTY_AMOUNT_DUE)::NUMBER(12,2) AS TOTAL_DUTIES_COLLECTED,
    ROUND(AVG(DUTY_PCT), 2) AS AVG_DUTY_RATE_PCT,
    COUNT(*) AS CLEARED_SHIPMENTS
FROM SILVER_CUSTOMS_CLEARANCE
WHERE CLEARANCE_STATUS = 'CLEARED'
GROUP BY DESTINATION_COUNTRY;

SELECT
    DEST_COUNTRY,
    TOTAL_CLEARED_VAL,
    TOTAL_DUTIES_COLLECTED,
    AVG_DUTY_RATE_PCT,
    CLEARED_SHIPMENTS
FROM GOLD_COUNTRY_DUTY_SUMMARY
ORDER BY DEST_COUNTRY;

UPDATE SILVER_CUSTOMS_CLEARANCE
SET CLEARANCE_STATUS = 'REJECTED'
WHERE DESTINATION_COUNTRY = 'CAN';

SET CORRUPTION_QUERY_ID = LAST_QUERY_ID();

SELECT
    SHIPMENT_ID,
    VEHICLE_ID,
    DECLARED_VALUE,
    CLEARANCE_STATUS
FROM SILVER_CUSTOMS_CLEARANCE
BEFORE (STATEMENT => $CORRUPTION_QUERY_ID)
WHERE DESTINATION_COUNTRY = 'CAN'
ORDER BY SHIPMENT_ID;

UPDATE SILVER_CUSTOMS_CLEARANCE AS CURRENT_DATA
SET CLEARANCE_STATUS = HISTORICAL_DATA.CLEARANCE_STATUS
FROM (
    SELECT
        SHIPMENT_ID,
        CLEARANCE_STATUS
    FROM SILVER_CUSTOMS_CLEARANCE
    BEFORE (STATEMENT => $CORRUPTION_QUERY_ID)
) AS HISTORICAL_DATA
WHERE CURRENT_DATA.SHIPMENT_ID = HISTORICAL_DATA.SHIPMENT_ID;

SELECT
    DESTINATION_COUNTRY,
    COUNT_IF(CLEARANCE_STATUS = 'CLEARED') AS CLEARED_COUNT,
    COUNT_IF(CLEARANCE_STATUS = 'REJECTED') AS REJECTED_COUNT
FROM SILVER_CUSTOMS_CLEARANCE
GROUP BY DESTINATION_COUNTRY
ORDER BY DESTINATION_COUNTRY;

WITH BRONZE_TOTAL AS (
    SELECT
        SUM(
            RAW_PAYLOAD:data:declared_value::NUMBER(12,2)
        )::NUMBER(12,2) AS BRONZE_GROSS_TOTAL
    FROM BRONZE_IOT_STREAMS
    WHERE RAW_PAYLOAD:payload_type::VARCHAR = 'CUSTOMS'
),
SILVER_TOTAL AS (
    SELECT
        SUM(DECLARED_VALUE)::NUMBER(12,2) AS SILVER_GROSS_TOTAL
    FROM SILVER_CUSTOMS_CLEARANCE
),
GOLD_TOTAL AS (
    SELECT
        SUM(TOTAL_CLEARED_VAL)::NUMBER(12,2) AS GOLD_GROSS_TOTAL
    FROM GOLD_COUNTRY_DUTY_SUMMARY
)
SELECT
    BRONZE_TOTAL.BRONZE_GROSS_TOTAL,
    SILVER_TOTAL.SILVER_GROSS_TOTAL,
    GOLD_TOTAL.GOLD_GROSS_TOTAL,
    (
        BRONZE_TOTAL.BRONZE_GROSS_TOTAL = SILVER_TOTAL.SILVER_GROSS_TOTAL
        AND GOLD_TOTAL.GOLD_GROSS_TOTAL = (
            SELECT
                SUM(DECLARED_VALUE)::NUMBER(12,2)
            FROM SILVER_CUSTOMS_CLEARANCE
            WHERE CLEARANCE_STATUS = 'CLEARED'
        )
    ) AS RECONCILED_FLAG
FROM BRONZE_TOTAL
CROSS JOIN SILVER_TOTAL
CROSS JOIN GOLD_TOTAL;