-- Create warehouse
CREATE WAREHOUSE IF NOT EXISTS RETAIL7_WH
WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

-- Create database
CREATE DATABASE IF NOT EXISTS RETAIL7_DB;

-- Create schema
CREATE SCHEMA IF NOT EXISTS RETAIL7_DB.SALES_SCHEMA;

-- Select warehouse
USE WAREHOUSE RETAIL7_WH;

-- Select database
USE DATABASE RETAIL7_DB;

-- Select schema
USE SCHEMA SALES_SCHEMA;

-- Verify environment
SELECT
    CURRENT_WAREHOUSE(),
    CURRENT_DATABASE(),
    CURRENT_SCHEMA();

-- Create CSV file format
CREATE FILE FORMAT IF NOT EXISTS RETAIL7_CSV_FORMAT
TYPE = 'CSV'
SKIP_HEADER = 1
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

-- Create internal stage
CREATE STAGE IF NOT EXISTS RETAIL7_STAGE
FILE_FORMAT = RETAIL7_CSV_FORMAT;

-- Check uploaded files
LIST @RETAIL7_STAGE;

-- Create raw patient table
CREATE TABLE IF NOT EXISTS RAW_PATIENTS (
    patient_id VARCHAR(20),
    patient_name VARCHAR(100),
    gender VARCHAR(20),
    city VARCHAR(100),
    state VARCHAR(100)
);

-- Create raw doctor table
CREATE TABLE IF NOT EXISTS RAW_DOCTORS (
    doctor_id VARCHAR(20),
    doctor_name VARCHAR(100),
    specialization VARCHAR(100)
);

-- Create raw hospital table
CREATE TABLE IF NOT EXISTS RAW_HOSPITALS (
    hospital_id VARCHAR(20),
    hospital_name VARCHAR(100),
    city VARCHAR(100),
    state VARCHAR(100),
    region VARCHAR(50)
);

-- Create raw department table
CREATE TABLE IF NOT EXISTS RAW_DEPARTMENTS (
    department_id VARCHAR(20),
    department_name VARCHAR(100)
);

-- Create raw treatment table
CREATE TABLE IF NOT EXISTS RAW_TREATMENTS (
    treatment_id VARCHAR(20),
    treatment_name VARCHAR(100),
    treatment_category VARCHAR(100)
);

-- Create raw admissions table
CREATE TABLE IF NOT EXISTS RAW_ADMISSIONS (
    admission_id VARCHAR(20),
    patient_id VARCHAR(20),
    doctor_id VARCHAR(20),
    hospital_id VARCHAR(20),
    department_id VARCHAR(20),
    admission_date DATE,
    discharge_date DATE
);

-- Create raw billing table based exactly on supplied billing CSV
CREATE TABLE IF NOT EXISTS RAW_BILLING (
    admission_id VARCHAR(20),
    patient_id VARCHAR(20),
    doctor_id VARCHAR(20),
    hospital_id VARCHAR(20),
    department_id VARCHAR(20),
    admission_date DATE,
    discharge_date DATE
);

-- Load patients
COPY INTO RAW_PATIENTS
FROM @RETAIL7_STAGE/patients.csv
FILE_FORMAT = RETAIL7_CSV_FORMAT;

-- Load doctors
COPY INTO RAW_DOCTORS
FROM @RETAIL7_STAGE/doctors.csv
FILE_FORMAT = RETAIL7_CSV_FORMAT;

-- Load hospitals
COPY INTO RAW_HOSPITALS
FROM @RETAIL7_STAGE/hospitals.csv
FILE_FORMAT = RETAIL7_CSV_FORMAT;

-- Load departments
COPY INTO RAW_DEPARTMENTS
FROM @RETAIL7_STAGE/departments.csv
FILE_FORMAT = RETAIL7_CSV_FORMAT;

-- Load treatments
COPY INTO RAW_TREATMENTS
FROM @RETAIL7_STAGE/treatments.csv
FILE_FORMAT = RETAIL7_CSV_FORMAT;

-- Load admissions
COPY INTO RAW_ADMISSIONS
FROM @RETAIL7_STAGE/admissions.csv
FILE_FORMAT = RETAIL7_CSV_FORMAT;

-- Load billing source exactly as supplied
COPY INTO RAW_BILLING
FROM @RETAIL7_STAGE/billing.csv
FILE_FORMAT = RETAIL7_CSV_FORMAT;

-- Verify patient records
SELECT COUNT(*) AS PATIENTS_LOADED
FROM RAW_PATIENTS;

-- Verify doctor records
SELECT COUNT(*) AS DOCTORS_LOADED
FROM RAW_DOCTORS;

-- Verify hospital records
SELECT COUNT(*) AS HOSPITALS_LOADED
FROM RAW_HOSPITALS;

-- Verify department records
SELECT COUNT(*) AS DEPARTMENTS_LOADED
FROM RAW_DEPARTMENTS;

-- Verify treatment records
SELECT COUNT(*) AS TREATMENTS_LOADED
FROM RAW_TREATMENTS;

-- Create patient dimension
CREATE OR REPLACE TABLE DIM_PATIENT (
    PATIENT_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    PATIENT_ID VARCHAR(20),
    PATIENT_NAME VARCHAR(100),
    GENDER VARCHAR(20),
    CITY VARCHAR(100),
    STATE VARCHAR(100)
);

-- Create doctor dimension
CREATE OR REPLACE TABLE DIM_DOCTOR (
    DOCTOR_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    DOCTOR_ID VARCHAR(20),
    DOCTOR_NAME VARCHAR(100),
    SPECIALIZATION VARCHAR(100)
);

-- Create hospital dimension
CREATE OR REPLACE TABLE DIM_HOSPITAL (
    HOSPITAL_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    HOSPITAL_ID VARCHAR(20),
    HOSPITAL_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    REGION VARCHAR(50)
);

-- Create department dimension
CREATE OR REPLACE TABLE DIM_DEPARTMENT (
    DEPARTMENT_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    DEPARTMENT_ID VARCHAR(20),
    DEPARTMENT_NAME VARCHAR(100)
);

-- Create treatment dimension
CREATE OR REPLACE TABLE DIM_TREATMENT (
    TREATMENT_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    TREATMENT_ID VARCHAR(20),
    TREATMENT_NAME VARCHAR(100),
    TREATMENT_CATEGORY VARCHAR(100)
);

-- Create date dimension
CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY INTEGER PRIMARY KEY,
    FULL_DATE DATE,
    DAY INTEGER,
    DAY_NAME VARCHAR(20),
    WEEK_NO INTEGER,
    MONTH INTEGER,
    MONTH_NAME VARCHAR(20),
    QUARTER VARCHAR(10),
    YEAR INTEGER
);

-- Load patient dimension
INSERT INTO DIM_PATIENT (
    PATIENT_ID,
    PATIENT_NAME,
    GENDER,
    CITY,
    STATE
)
SELECT
    PATIENT_ID,
    PATIENT_NAME,
    GENDER,
    CITY,
    STATE
FROM RAW_PATIENTS;

-- Load doctor dimension
INSERT INTO DIM_DOCTOR (
    DOCTOR_ID,
    DOCTOR_NAME,
    SPECIALIZATION
)
SELECT
    DOCTOR_ID,
    DOCTOR_NAME,
    SPECIALIZATION
FROM RAW_DOCTORS;

-- Load hospital dimension
INSERT INTO DIM_HOSPITAL (
    HOSPITAL_ID,
    HOSPITAL_NAME,
    CITY,
    STATE,
    REGION
)
SELECT
    HOSPITAL_ID,
    HOSPITAL_NAME,
    CITY,
    STATE,
    REGION
FROM RAW_HOSPITALS;

-- Load department dimension
INSERT INTO DIM_DEPARTMENT (
    DEPARTMENT_ID,
    DEPARTMENT_NAME
)
SELECT
    DEPARTMENT_ID,
    DEPARTMENT_NAME
FROM RAW_DEPARTMENTS;

-- Load treatment dimension
INSERT INTO DIM_TREATMENT (
    TREATMENT_ID,
    TREATMENT_NAME,
    TREATMENT_CATEGORY
)
SELECT
    TREATMENT_ID,
    TREATMENT_NAME,
    TREATMENT_CATEGORY
FROM RAW_TREATMENTS;

-- Generate date dimension
INSERT INTO DIM_DATE (
    DATE_KEY,
    FULL_DATE,
    DAY,
    DAY_NAME,
    WEEK_NO,
    MONTH,
    MONTH_NAME,
    QUARTER,
    YEAR
)
SELECT
    TO_NUMBER(TO_CHAR(DATE_VALUE, 'YYYYMMDD')),
    DATE_VALUE,
    DAY(DATE_VALUE),
    DAYNAME(DATE_VALUE),
    WEEKOFYEAR(DATE_VALUE),
    MONTH(DATE_VALUE),
    MONTHNAME(DATE_VALUE),
    'Q' || QUARTER(DATE_VALUE),
    YEAR(DATE_VALUE)
FROM (
    SELECT DATEADD(
        DAY,
        SEQ4(),
        '2026-01-01'::DATE
    ) AS DATE_VALUE
    FROM TABLE(GENERATOR(ROWCOUNT => 90))
);

-- Verify dimensions
SELECT COUNT(*) AS PATIENT_DIMENSION_ROWS
FROM DIM_PATIENT;

SELECT COUNT(*) AS DOCTOR_DIMENSION_ROWS
FROM DIM_DOCTOR;

SELECT COUNT(*) AS HOSPITAL_DIMENSION_ROWS
FROM DIM_HOSPITAL;

SELECT COUNT(*) AS DEPARTMENT_DIMENSION_ROWS
FROM DIM_DEPARTMENT;

SELECT COUNT(*) AS TREATMENT_DIMENSION_ROWS
FROM DIM_TREATMENT;

SELECT COUNT(*) AS DATE_DIMENSION_ROWS
FROM DIM_DATE;

-- Create admission fact
CREATE OR REPLACE TABLE FACT_ADMISSION (
    ADMISSION_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    PATIENT_KEY INTEGER,
    DOCTOR_KEY INTEGER,
    HOSPITAL_KEY INTEGER,
    DEPARTMENT_KEY INTEGER,
    DATE_KEY INTEGER,
    ADMISSION_COUNT INTEGER,
    LENGTH_OF_STAY INTEGER
);

-- Load admission fact
INSERT INTO FACT_ADMISSION (
    PATIENT_KEY,
    DOCTOR_KEY,
    HOSPITAL_KEY,
    DEPARTMENT_KEY,
    DATE_KEY,
    ADMISSION_COUNT,
    LENGTH_OF_STAY
)
SELECT
    P.PATIENT_KEY,
    D.DOCTOR_KEY,
    H.HOSPITAL_KEY,
    DP.DEPARTMENT_KEY,
    DD.DATE_KEY,
    1,
    DATEDIFF(DAY, A.ADMISSION_DATE, A.DISCHARGE_DATE)
FROM RAW_ADMISSIONS A
JOIN DIM_PATIENT P
    ON A.PATIENT_ID = P.PATIENT_ID
JOIN DIM_DOCTOR D
    ON A.DOCTOR_ID = D.DOCTOR_ID
JOIN DIM_HOSPITAL H
    ON A.HOSPITAL_ID = H.HOSPITAL_ID
JOIN DIM_DEPARTMENT DP
    ON A.DEPARTMENT_ID = DP.DEPARTMENT_ID
JOIN DIM_DATE DD
    ON A.ADMISSION_DATE = DD.FULL_DATE;

-- Verify admission fact
SELECT *
FROM FACT_ADMISSION;

-- Admission count by hospital
SELECT
    H.HOSPITAL_NAME,
    SUM(F.ADMISSION_COUNT) AS TOTAL_ADMISSIONS
FROM FACT_ADMISSION F
JOIN DIM_HOSPITAL H
    ON F.HOSPITAL_KEY = H.HOSPITAL_KEY
GROUP BY H.HOSPITAL_NAME
ORDER BY TOTAL_ADMISSIONS DESC;

-- Admission count by department
SELECT
    D.DEPARTMENT_NAME,
    SUM(F.ADMISSION_COUNT) AS TOTAL_ADMISSIONS
FROM FACT_ADMISSION F
JOIN DIM_DEPARTMENT D
    ON F.DEPARTMENT_KEY = D.DEPARTMENT_KEY
GROUP BY D.DEPARTMENT_NAME
ORDER BY TOTAL_ADMISSIONS DESC;

-- Admission count by doctor
SELECT
    D.DOCTOR_NAME,
    SUM(F.ADMISSION_COUNT) AS TOTAL_ADMISSIONS
FROM FACT_ADMISSION F
JOIN DIM_DOCTOR D
    ON F.DOCTOR_KEY = D.DOCTOR_KEY
GROUP BY D.DOCTOR_NAME
ORDER BY TOTAL_ADMISSIONS DESC;

-- Monthly admissions
SELECT
    D.YEAR,
    D.MONTH,
    D.MONTH_NAME,
    SUM(F.ADMISSION_COUNT) AS TOTAL_ADMISSIONS
FROM FACT_ADMISSION F
JOIN DIM_DATE D
    ON F.DATE_KEY = D.DATE_KEY
GROUP BY
    D.YEAR,
    D.MONTH,
    D.MONTH_NAME
ORDER BY
    D.YEAR,
    D.MONTH;

-- Average length of stay
SELECT
    AVG(LENGTH_OF_STAY) AS AVERAGE_LENGTH_OF_STAY
FROM FACT_ADMISSION;

-- Total length of stay by hospital
SELECT
    H.HOSPITAL_NAME,
    SUM(F.LENGTH_OF_STAY) AS TOTAL_LENGTH_OF_STAY
FROM FACT_ADMISSION F
JOIN DIM_HOSPITAL H
    ON F.HOSPITAL_KEY = H.HOSPITAL_KEY
GROUP BY H.HOSPITAL_NAME
ORDER BY TOTAL_LENGTH_OF_STAY DESC;

-- Create billing fact structure
CREATE OR REPLACE TABLE FACT_BILLING (
    BILLING_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    PATIENT_KEY INTEGER,
    DOCTOR_KEY INTEGER,
    HOSPITAL_KEY INTEGER,
    DEPARTMENT_KEY INTEGER,
    TREATMENT_KEY INTEGER,
    DATE_KEY INTEGER,
    QUANTITY INTEGER,
    TREATMENT_AMOUNT NUMBER(12,2),
    DISCOUNT NUMBER(12,2),
    NET_AMOUNT NUMBER(12,2)
);

-- Check supplied billing source before loading billing fact
SELECT *
FROM RAW_BILLING;

-- Show billing source problem
SELECT
    COLUMN_NAME,
    DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'RAW_BILLING'
ORDER BY ORDINAL_POSITION;

-- Count supplied billing records
SELECT COUNT(*) AS BILLING_SOURCE_ROWS
FROM RAW_BILLING;

-- Show conformed dimensions
SELECT 'DIM_PATIENT' AS DIMENSION_NAME, 'FACT_ADMISSION + FACT_BILLING' AS USED_BY
UNION ALL
SELECT 'DIM_DOCTOR', 'FACT_ADMISSION + FACT_BILLING'
UNION ALL
SELECT 'DIM_HOSPITAL', 'FACT_ADMISSION + FACT_BILLING'
UNION ALL
SELECT 'DIM_DEPARTMENT', 'FACT_ADMISSION + FACT_BILLING'
UNION ALL
SELECT 'DIM_DATE', 'FACT_ADMISSION + FACT_BILLING'
UNION ALL
SELECT 'DIM_TREATMENT', 'FACT_BILLING ONLY';

-- Drill-across admissions by hospital
WITH ADMISSIONS AS (
    SELECT
        HOSPITAL_KEY,
        SUM(ADMISSION_COUNT) AS TOTAL_ADMISSIONS
    FROM FACT_ADMISSION
    GROUP BY HOSPITAL_KEY
),
BILLING AS (
    SELECT
        HOSPITAL_KEY,
        SUM(NET_AMOUNT) AS TOTAL_REVENUE
    FROM FACT_BILLING
    GROUP BY HOSPITAL_KEY
)
SELECT
    H.HOSPITAL_NAME,
    A.TOTAL_ADMISSIONS,
    B.TOTAL_REVENUE
FROM DIM_HOSPITAL H
LEFT JOIN ADMISSIONS A
    ON H.HOSPITAL_KEY = A.HOSPITAL_KEY
LEFT JOIN BILLING B
    ON H.HOSPITAL_KEY = B.HOSPITAL_KEY
ORDER BY H.HOSPITAL_NAME;

-- Display bus matrix
SELECT
    'DIM_PATIENT' AS DIMENSION,
    'YES' AS FACT_ADMISSION,
    'YES' AS FACT_BILLING
UNION ALL
SELECT 'DIM_DOCTOR', 'YES', 'YES'
UNION ALL
SELECT 'DIM_HOSPITAL', 'YES', 'YES'
UNION ALL
SELECT 'DIM_DEPARTMENT', 'YES', 'YES'
UNION ALL
SELECT 'DIM_DATE', 'YES', 'YES'
UNION ALL
SELECT 'DIM_TREATMENT', 'NO', 'YES';