-- Project 19B: Healthcare Patient Journeys & Promotion Coverage Factless Models
-- Week 3 - Day 11
-- Topics: M1-M5


-- Task 1: Create database and schema

CREATE DATABASE IF NOT EXISTS P19B_HEALTHCARE_DB;

CREATE SCHEMA IF NOT EXISTS P19B_HEALTHCARE_DB.HEALTHCARE_SCHEMA;


-- Task 2: Create warehouse

CREATE WAREHOUSE IF NOT EXISTS P19B_WH
WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE P19B_WH;

USE DATABASE P19B_HEALTHCARE_DB;

USE SCHEMA HEALTHCARE_SCHEMA;


-- Task 3: Create CSV file format

CREATE FILE FORMAT IF NOT EXISTS P19B_CSV_FORMAT
TYPE = 'CSV'
SKIP_HEADER = 1
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL', '');


-- Task 4: Create internal stage

CREATE STAGE IF NOT EXISTS P19B_STAGE
FILE_FORMAT = P19B_CSV_FORMAT;


-- Check uploaded files

LIST @P19B_STAGE;


-- Task 5: Create raw doctor roster table

CREATE OR REPLACE TABLE P19B_RAW_DOCTOR_ROSTER (
    SHIFT_DATE DATE,
    DOCTOR_ID VARCHAR(20),
    DEPARTMENT_ID VARCHAR(20),
    SHIFT_TYPE VARCHAR(20)
);


-- Task 6: Create raw patient journey table

CREATE OR REPLACE TABLE P19B_RAW_PATIENT_JOURNEY (
    ENCOUNTER_ID VARCHAR(20),
    PATIENT_ID VARCHAR(20),
    TRIAGE_DATE DATE,
    ADMISSION_DATE DATE,
    DISCHARGE_DATE DATE
);


-- Task 7: Create raw treatment billing table

CREATE OR REPLACE TABLE P19B_RAW_TREATMENT_BILLS (
    CLAIM_ID VARCHAR(20),
    ENCOUNTER_ID VARCHAR(20),
    PATIENT_ID VARCHAR(20),
    PROCEDURE_COST NUMBER(12,2),
    INSURANCE_DISCOUNT_PCT NUMBER(5,2),
    COPAY_AMOUNT NUMBER(12,2)
);


-- Task 8: Load doctor roster data

COPY INTO P19B_RAW_DOCTOR_ROSTER
FROM @P19B_STAGE/P19B_raw_doctor_roster.csv
FILE_FORMAT = P19B_CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';


-- Task 9: Load patient journey data

COPY INTO P19B_RAW_PATIENT_JOURNEY
FROM @P19B_STAGE/P19B_raw_patient_journey.csv
FILE_FORMAT = P19B_CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';


-- Task 10: Load treatment billing data

COPY INTO P19B_RAW_TREATMENT_BILLS
FROM @P19B_STAGE/P19B_raw_treatment_bills.csv
FILE_FORMAT = P19B_CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';


-- Verify raw doctor roster

SELECT *
FROM P19B_RAW_DOCTOR_ROSTER
ORDER BY SHIFT_DATE, DEPARTMENT_ID, DOCTOR_ID;


-- Verify raw patient journeys

SELECT *
FROM P19B_RAW_PATIENT_JOURNEY
ORDER BY ENCOUNTER_ID;


-- Verify raw treatment bills

SELECT *
FROM P19B_RAW_TREATMENT_BILLS
ORDER BY CLAIM_ID;


-- Task 11: Create Factless Staff Coverage Table

CREATE OR REPLACE TABLE P19B_FACTLESS_STAFF_COVERAGE (
    SHIFT_DATE DATE,
    DOCTOR_ID VARCHAR(20),
    DEPARTMENT_ID VARCHAR(20),
    SHIFT_TYPE VARCHAR(20)
);


-- Task 12: Populate Factless Staff Coverage Table

INSERT INTO P19B_FACTLESS_STAFF_COVERAGE (
    SHIFT_DATE,
    DOCTOR_ID,
    DEPARTMENT_ID,
    SHIFT_TYPE
)
SELECT
    SHIFT_DATE,
    DOCTOR_ID,
    DEPARTMENT_ID,
    SHIFT_TYPE
FROM P19B_RAW_DOCTOR_ROSTER;


-- Verify Factless Coverage Table

SELECT
    COUNT(*) AS TOTAL_ROSTER_ROWS
FROM P19B_FACTLESS_STAFF_COVERAGE;


-- Task 13: Analyze departments with zero night shifts

SELECT
    D.DEPARTMENT_ID,
    COUNT(
        CASE
            WHEN N.SHIFT_TYPE = 'NIGHT'
            THEN N.DOCTOR_ID
        END
    ) AS NIGHT_SHIFT_COUNT
FROM (
    SELECT DISTINCT
        DEPARTMENT_ID
    FROM P19B_FACTLESS_STAFF_COVERAGE
    WHERE SHIFT_DATE = '2026-08-20'
) D
LEFT JOIN P19B_FACTLESS_STAFF_COVERAGE N
    ON D.DEPARTMENT_ID = N.DEPARTMENT_ID
    AND N.SHIFT_DATE = '2026-08-20'
    AND N.SHIFT_TYPE = 'NIGHT'
GROUP BY D.DEPARTMENT_ID
HAVING COUNT(
    CASE
        WHEN N.SHIFT_TYPE = 'NIGHT'
        THEN N.DOCTOR_ID
    END
) = 0
ORDER BY D.DEPARTMENT_ID;


-- Task 14: Create Patient Admission Accumulating Snapshot

CREATE OR REPLACE TABLE P19B_FACT_PATIENT_ADMISSION_LIFECYCLE (
    ENCOUNTER_ID VARCHAR(20),
    PATIENT_ID VARCHAR(20),
    TRIAGE_DATE DATE,
    ADMISSION_DATE DATE,
    DISCHARGE_DATE DATE,
    TRIAGE_TO_ADMIT_DAYS INTEGER,
    LENGTH_OF_STAY_DAYS INTEGER
);


-- Task 15: Populate Patient Admission Accumulating Snapshot

INSERT INTO P19B_FACT_PATIENT_ADMISSION_LIFECYCLE (
    ENCOUNTER_ID,
    PATIENT_ID,
    TRIAGE_DATE,
    ADMISSION_DATE,
    DISCHARGE_DATE,
    TRIAGE_TO_ADMIT_DAYS,
    LENGTH_OF_STAY_DAYS
)
SELECT
    ENCOUNTER_ID,
    PATIENT_ID,
    TRIAGE_DATE,
    ADMISSION_DATE,
    DISCHARGE_DATE,

    CASE
        WHEN ADMISSION_DATE IS NOT NULL
        THEN DATEDIFF(
            'day',
            TRIAGE_DATE,
            ADMISSION_DATE
        )
    END AS TRIAGE_TO_ADMIT_DAYS,

    CASE
        WHEN DISCHARGE_DATE IS NOT NULL
        THEN DATEDIFF(
            'day',
            ADMISSION_DATE,
            DISCHARGE_DATE
        )
    END AS LENGTH_OF_STAY_DAYS

FROM P19B_RAW_PATIENT_JOURNEY;


-- Verify completed patient lifecycles

SELECT
    ENCOUNTER_ID,
    PATIENT_ID,
    TRIAGE_TO_ADMIT_DAYS,
    LENGTH_OF_STAY_DAYS
FROM P19B_FACT_PATIENT_ADMISSION_LIFECYCLE
WHERE LENGTH_OF_STAY_DAYS IS NOT NULL
ORDER BY ENCOUNTER_ID;


-- Task 16: Create Treatment Billing Transaction Fact

CREATE OR REPLACE TABLE P19B_FACT_TREATMENT_BILLING (
    CLAIM_ID VARCHAR(20),
    ENCOUNTER_ID VARCHAR(20),
    PATIENT_ID VARCHAR(20),
    PROCEDURE_COST NUMBER(12,2),
    INSURANCE_DISCOUNT_PCT NUMBER(5,2),
    COPAY_AMOUNT NUMBER(12,2),
    NET_CHARGE NUMBER(12,2)
);


-- Task 17: Populate Treatment Billing Fact

INSERT INTO P19B_FACT_TREATMENT_BILLING (
    CLAIM_ID,
    ENCOUNTER_ID,
    PATIENT_ID,
    PROCEDURE_COST,
    INSURANCE_DISCOUNT_PCT,
    COPAY_AMOUNT,
    NET_CHARGE
)
SELECT
    CLAIM_ID,
    ENCOUNTER_ID,
    PATIENT_ID,
    PROCEDURE_COST,
    INSURANCE_DISCOUNT_PCT,
    COPAY_AMOUNT,

    (
        PROCEDURE_COST * (1 - INSURANCE_DISCOUNT_PCT)
    ) - COPAY_AMOUNT AS NET_CHARGE

FROM P19B_RAW_TREATMENT_BILLS;


-- Verify Treatment Billing Fact

SELECT
    CLAIM_ID,
    ENCOUNTER_ID,
    PROCEDURE_COST,
    COPAY_AMOUNT,
    NET_CHARGE
FROM P19B_FACT_TREATMENT_BILLING
ORDER BY CLAIM_ID;


-- Task 18: Patient Billing Aggregation

SELECT
    ENCOUNTER_ID,
    SUM(NET_CHARGE) AS TOTAL_NET_CHARGES,
    AVG(PROCEDURE_COST) AS AVG_PROCEDURE_COST
FROM P19B_FACT_TREATMENT_BILLING
GROUP BY ENCOUNTER_ID
ORDER BY ENCOUNTER_ID;


-- Task 19: Audit Untreated / Non-Billed Encounters

SELECT
    L.ENCOUNTER_ID,
    L.PATIENT_ID,
    'NO_CLAIMS_ISSUED' AS UNBILLED_STATUS
FROM P19B_FACT_PATIENT_ADMISSION_LIFECYCLE L
LEFT JOIN P19B_FACT_TREATMENT_BILLING B
    ON L.ENCOUNTER_ID = B.ENCOUNTER_ID
WHERE B.CLAIM_ID IS NULL
ORDER BY L.ENCOUNTER_ID;


-- Task 20: Final validation - row counts

SELECT
    COUNT(*) AS RAW_DOCTOR_ROSTER_COUNT
FROM P19B_RAW_DOCTOR_ROSTER;


SELECT
    COUNT(*) AS RAW_PATIENT_JOURNEY_COUNT
FROM P19B_RAW_PATIENT_JOURNEY;


SELECT
    COUNT(*) AS RAW_TREATMENT_BILL_COUNT
FROM P19B_RAW_TREATMENT_BILLS;


SELECT
    COUNT(*) AS FACTLESS_COVERAGE_COUNT
FROM P19B_FACTLESS_STAFF_COVERAGE;


SELECT
    COUNT(*) AS PATIENT_LIFECYCLE_COUNT
FROM P19B_FACT_PATIENT_ADMISSION_LIFECYCLE;


SELECT
    COUNT(*) AS TREATMENT_BILLING_COUNT
FROM P19B_FACT_TREATMENT_BILLING;