-- Project 20A: Healthcare Lakehouse Engine

-- Task 0: Create database, warehouse and schema

CREATE DATABASE IF NOT EXISTS P20A_HEALTHCARE_DB;

CREATE WAREHOUSE IF NOT EXISTS P20A_HEALTHCARE_WH
WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE SCHEMA IF NOT EXISTS P20A_HEALTHCARE_DB.HEALTHCARE_SCHEMA;

USE WAREHOUSE P20A_HEALTHCARE_WH;

USE DATABASE P20A_HEALTHCARE_DB;

USE SCHEMA HEALTHCARE_SCHEMA;


-- Task 0: Create JSON file format

CREATE FILE FORMAT IF NOT EXISTS P20A_JSON_FORMAT
TYPE = 'JSON';


-- Task 0: Create internal stage

CREATE STAGE IF NOT EXISTS P20A_STAGE
FILE_FORMAT = P20A_JSON_FORMAT;


-- Check uploaded files

LIST @P20A_STAGE;


-- Task 0: Create raw tables

CREATE OR REPLACE TABLE P20A_RAW_DIM_DATE (
    RAW_DATA VARIANT
);

CREATE OR REPLACE TABLE P20A_RAW_DIM_DIAGNOSIS (
    RAW_DATA VARIANT
);

CREATE OR REPLACE TABLE P20A_RAW_ENCOUNTERS (
    RAW_DATA VARIANT
);

CREATE OR REPLACE TABLE P20A_RAW_BRIDGE_DOCTORS (
    RAW_DATA VARIANT
);


-- Task 0: Load JSON files

COPY INTO P20A_RAW_DIM_DATE
FROM @P20A_STAGE/P20A_dim_date_kv.json
FILE_FORMAT = P20A_JSON_FORMAT;

COPY INTO P20A_RAW_DIM_DIAGNOSIS
FROM @P20A_STAGE/P20A_dim_diagnosis_kv.json
FILE_FORMAT = P20A_JSON_FORMAT;

COPY INTO P20A_RAW_ENCOUNTERS
FROM @P20A_STAGE/P20A_raw_encounters_kv.json
FILE_FORMAT = P20A_JSON_FORMAT;

COPY INTO P20A_RAW_BRIDGE_DOCTORS
FROM @P20A_STAGE/P20A_bridge_doctors_kv.json
FILE_FORMAT = P20A_JSON_FORMAT;


-- Task 0: Verify raw data

SELECT COUNT(*) AS DATE_ROWS
FROM P20A_RAW_DIM_DATE;

SELECT COUNT(*) AS DIAGNOSIS_ROWS
FROM P20A_RAW_DIM_DIAGNOSIS;

SELECT COUNT(*) AS ENCOUNTER_ROWS
FROM P20A_RAW_ENCOUNTERS;

SELECT COUNT(*) AS BRIDGE_ROWS
FROM P20A_RAW_BRIDGE_DOCTORS;


-- Task 1: Create date dimension

CREATE OR REPLACE TABLE P20A_DIM_DATE (
    DATE_KEY NUMBER(8,0) PRIMARY KEY,
    FULL_DATE DATE,
    YEAR NUMBER(4,0),
    QUARTER VARCHAR(5),
    MONTH_NAME VARCHAR(20)
);


-- Load date dimension

INSERT INTO P20A_DIM_DATE (
    DATE_KEY,
    FULL_DATE,
    YEAR,
    QUARTER,
    MONTH_NAME
)
SELECT
    RAW_DATA:date_key::NUMBER(8,0),
    RAW_DATA:full_date::DATE,
    RAW_DATA:year::NUMBER(4,0),
    RAW_DATA:quarter::VARCHAR,
    RAW_DATA:month_name::VARCHAR
FROM P20A_RAW_DIM_DATE;


-- Verify date dimension

SELECT *
FROM P20A_DIM_DATE
ORDER BY DATE_KEY;


-- Task 1: Create diagnosis dimension

CREATE OR REPLACE TABLE P20A_DIM_DIAGNOSIS (
    DIAGNOSIS_ID VARCHAR(20) PRIMARY KEY,
    DIAGNOSIS_NAME VARCHAR(100),
    PARENT_DIAGNOSIS_ID VARCHAR(20),
    CATEGORY_LEVEL NUMBER(2,0)
);


-- Load diagnosis dimension

INSERT INTO P20A_DIM_DIAGNOSIS (
    DIAGNOSIS_ID,
    DIAGNOSIS_NAME,
    PARENT_DIAGNOSIS_ID,
    CATEGORY_LEVEL
)
SELECT
    RAW_DATA:diagnosis_id::VARCHAR,
    RAW_DATA:diagnosis_name::VARCHAR,
    RAW_DATA:parent_diagnosis_id::VARCHAR,
    RAW_DATA:category_level::NUMBER(2,0)
FROM P20A_RAW_DIM_DIAGNOSIS;


-- Verify diagnosis dimension

SELECT *
FROM P20A_DIM_DIAGNOSIS
ORDER BY CATEGORY_LEVEL, DIAGNOSIS_ID;


-- Task 1: Create patient encounter fact table

CREATE OR REPLACE TABLE P20A_FACT_PATIENT_ENCOUNTERS (
    ENCOUNTER_ID VARCHAR(20) PRIMARY KEY,
    PATIENT_ID VARCHAR(20),
    ADMIT_DATE_KEY NUMBER(8,0),
    DISCHARGE_DATE_KEY NUMBER(8,0),
    BILLING_DATE_KEY NUMBER(8,0),
    PRIMARY_DIAG_ID VARCHAR(20),
    TOTAL_COST NUMBER(12,2)
);


-- Load encounter fact table

INSERT INTO P20A_FACT_PATIENT_ENCOUNTERS (
    ENCOUNTER_ID,
    PATIENT_ID,
    ADMIT_DATE_KEY,
    DISCHARGE_DATE_KEY,
    BILLING_DATE_KEY,
    PRIMARY_DIAG_ID,
    TOTAL_COST
)
SELECT
    RAW_DATA:encounter_id::VARCHAR,
    RAW_DATA:patient_id::VARCHAR,
    RAW_DATA:admit_date_key::NUMBER(8,0),
    RAW_DATA:discharge_date_key::NUMBER(8,0),
    RAW_DATA:billing_date_key::NUMBER(8,0),
    RAW_DATA:primary_diag_id::VARCHAR,
    RAW_DATA:total_cost::NUMBER(12,2)
FROM P20A_RAW_ENCOUNTERS;


-- Task 1: Validate target table creation

SELECT
    TABLE_NAME,
    CASE
        WHEN COUNT(*) = 1 THEN 'TABLE_CREATED'
        ELSE 'TABLE_NOT_FOUND'
    END AS STATUS
FROM P20A_HEALTHCARE_DB.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'HEALTHCARE_SCHEMA'
  AND TABLE_NAME = 'P20A_FACT_PATIENT_ENCOUNTERS'
GROUP BY TABLE_NAME;


-- Task 2: Create role-playing Admit Date view

CREATE OR REPLACE VIEW P20A_VW_ADMIT_DATE AS
SELECT
    DATE_KEY AS ADMIT_DATE_KEY,
    FULL_DATE AS ADMIT_DATE,
    YEAR AS ADMIT_YEAR,
    QUARTER AS ADMIT_QUARTER,
    MONTH_NAME AS ADMIT_MONTH
FROM P20A_DIM_DATE;


-- Task 2: Create role-playing Discharge Date view

CREATE OR REPLACE VIEW P20A_VW_DISCHARGE_DATE AS
SELECT
    DATE_KEY AS DISCHARGE_DATE_KEY,
    FULL_DATE AS DISCHARGE_DATE,
    YEAR AS DISCHARGE_YEAR,
    QUARTER AS DISCHARGE_QUARTER,
    MONTH_NAME AS DISCHARGE_MONTH
FROM P20A_DIM_DATE;


-- Task 2: Create role-playing Billing Date view

CREATE OR REPLACE VIEW P20A_VW_BILLING_DATE AS
SELECT
    DATE_KEY AS BILLING_DATE_KEY,
    FULL_DATE AS BILLING_DATE,
    YEAR AS BILLING_YEAR,
    QUARTER AS BILLING_QUARTER,
    MONTH_NAME AS BILLING_MONTH
FROM P20A_DIM_DATE;


-- Task 2: Demonstrate all three date roles

SELECT
    f.ENCOUNTER_ID,
    a.ADMIT_DATE,
    d.DISCHARGE_DATE,
    b.BILLING_DATE
FROM P20A_FACT_PATIENT_ENCOUNTERS f
LEFT JOIN P20A_VW_ADMIT_DATE a
    ON f.ADMIT_DATE_KEY = a.ADMIT_DATE_KEY
LEFT JOIN P20A_VW_DISCHARGE_DATE d
    ON f.DISCHARGE_DATE_KEY = d.DISCHARGE_DATE_KEY
LEFT JOIN P20A_VW_BILLING_DATE b
    ON f.BILLING_DATE_KEY = b.BILLING_DATE_KEY
ORDER BY f.ENCOUNTER_ID
LIMIT 3;


-- Task 3: Create bridge table

CREATE OR REPLACE TABLE P20A_BRIDGE_DOCTORS (
    ENCOUNTER_ID VARCHAR(20),
    DOCTOR_ID VARCHAR(20),
    WEIGHT_FACTOR NUMBER(5,2),
    PRIMARY KEY (ENCOUNTER_ID, DOCTOR_ID)
);


-- Load bridge table

INSERT INTO P20A_BRIDGE_DOCTORS (
    ENCOUNTER_ID,
    DOCTOR_ID,
    WEIGHT_FACTOR
)
SELECT
    RAW_DATA:encounter_id::VARCHAR,
    RAW_DATA:doctor_id::VARCHAR,
    RAW_DATA:weight_factor::NUMBER(5,2)
FROM P20A_RAW_BRIDGE_DOCTORS;


-- Task 3: Calculate weighted doctor attribution

SELECT
    f.ENCOUNTER_ID,
    b.DOCTOR_ID,
    b.WEIGHT_FACTOR,
    f.TOTAL_COST * b.WEIGHT_FACTOR AS ATTRIBUTED_COST
FROM P20A_FACT_PATIENT_ENCOUNTERS f
JOIN P20A_BRIDGE_DOCTORS b
    ON f.ENCOUNTER_ID = b.ENCOUNTER_ID
WHERE f.ENCOUNTER_ID IN ('ENC-801', 'ENC-802')
ORDER BY f.ENCOUNTER_ID, b.DOCTOR_ID;


-- Task 3: Validate weight allocation

SELECT
    ENCOUNTER_ID,
    SUM(WEIGHT_FACTOR) AS TOTAL_WEIGHT
FROM P20A_BRIDGE_DOCTORS
GROUP BY ENCOUNTER_ID
ORDER BY ENCOUNTER_ID;


-- Task 4: Recursive parent-child hierarchy

WITH RECURSIVE DIAGNOSIS_HIERARCHY AS (

    SELECT
        DIAGNOSIS_ID,
        DIAGNOSIS_NAME,
        PARENT_DIAGNOSIS_ID,
        CATEGORY_LEVEL,
        DIAGNOSIS_NAME AS ROOT_CATEGORY_NAME
    FROM P20A_DIM_DIAGNOSIS
    WHERE PARENT_DIAGNOSIS_ID IS NULL

    UNION ALL

    SELECT
        child.DIAGNOSIS_ID,
        child.DIAGNOSIS_NAME,
        child.PARENT_DIAGNOSIS_ID,
        child.CATEGORY_LEVEL,
        parent.ROOT_CATEGORY_NAME
    FROM P20A_DIM_DIAGNOSIS child
    JOIN DIAGNOSIS_HIERARCHY parent
        ON child.PARENT_DIAGNOSIS_ID = parent.DIAGNOSIS_ID
)

SELECT
    DIAGNOSIS_ID,
    DIAGNOSIS_NAME,
    ROOT_CATEGORY_NAME
FROM DIAGNOSIS_HIERARCHY
WHERE DIAGNOSIS_ID IN (
    'ICD-1100',
    'ICD-1110',
    'ICD-2110',
    'ICD-3110'
)
ORDER BY DIAGNOSIS_ID;


-- Task 5: Prepare MERGE source

CREATE OR REPLACE TEMPORARY TABLE P20A_MERGE_SOURCE (
    ENCOUNTER_ID VARCHAR(20),
    TOTAL_COST NUMBER(12,2)
);


-- Existing record ENC-801 receives a new cost.
-- ENC-821 has no business attributes supplied by the problem.

INSERT INTO P20A_MERGE_SOURCE (
    ENCOUNTER_ID,
    TOTAL_COST
)
VALUES
    ('ENC-801', 5000.00),
    ('ENC-821', NULL);


-- Task 5: MERGE existing and new encounter

MERGE INTO P20A_FACT_PATIENT_ENCOUNTERS AS target
USING P20A_MERGE_SOURCE AS source
ON target.ENCOUNTER_ID = source.ENCOUNTER_ID

WHEN MATCHED THEN
    UPDATE SET
        target.TOTAL_COST = source.TOTAL_COST

WHEN NOT MATCHED THEN
    INSERT (
        ENCOUNTER_ID,
        TOTAL_COST
    )
    VALUES (
        source.ENCOUNTER_ID,
        source.TOTAL_COST
    );


-- Save the MERGE query ID for Time Travel

SET P20A_MERGE_QUERY_ID = LAST_QUERY_ID();


-- Task 5: Validate MERGE counts

SELECT
    "number of rows inserted" AS ROWS_INSERTED,
    "number of rows updated" AS ROWS_UPDATED
FROM TABLE(RESULT_SCAN($P20A_MERGE_QUERY_ID));


-- Verify updated ENC-801

SELECT
    ENCOUNTER_ID,
    TOTAL_COST
FROM P20A_FACT_PATIENT_ENCOUNTERS
WHERE ENCOUNTER_ID = 'ENC-801';


-- Verify inserted ENC-821

SELECT
    ENCOUNTER_ID,
    TOTAL_COST
FROM P20A_FACT_PATIENT_ENCOUNTERS
WHERE ENCOUNTER_ID = 'ENC-821';


-- Task 6: Time Travel audit

SELECT
    ENCOUNTER_ID,
    TOTAL_COST
FROM P20A_FACT_PATIENT_ENCOUNTERS
BEFORE(STATEMENT => $P20A_MERGE_QUERY_ID)
WHERE ENCOUNTER_ID = 'ENC-801';


-- Task 7: Schema evolution

ALTER TABLE P20A_FACT_PATIENT_ENCOUNTERS
ADD COLUMN PATIENT_FEEDBACK_SCORE NUMBER(3,1);


-- Task 7: Verify new column

SELECT
    ENCOUNTER_ID,
    TOTAL_COST,
    PATIENT_FEEDBACK_SCORE
FROM P20A_FACT_PATIENT_ENCOUNTERS
WHERE ENCOUNTER_ID = 'ENC-801';


-- Task 8: Apply Snowflake clustering

ALTER TABLE P20A_FACT_PATIENT_ENCOUNTERS
CLUSTER BY (PATIENT_ID, PRIMARY_DIAG_ID);


-- Task 8: Verify clustering configuration

SELECT
    TABLE_NAME,
    CLUSTERING_KEY
FROM P20A_HEALTHCARE_DB.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'HEALTHCARE_SCHEMA'
  AND TABLE_NAME = 'P20A_FACT_PATIENT_ENCOUNTERS';


-- Task 8: Optimization validation

SELECT
    CASE
        WHEN CLUSTERING_KEY IS NOT NULL THEN 'SUCCESS'
        ELSE 'NOT_APPLIED'
    END AS OPTIMIZATION_STATUS
FROM P20A_HEALTHCARE_DB.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'HEALTHCARE_SCHEMA'
  AND TABLE_NAME = 'P20A_FACT_PATIENT_ENCOUNTERS';


-- Final validation: encounter count

SELECT
    COUNT(*) AS ENCOUNTER_COUNT
FROM P20A_FACT_PATIENT_ENCOUNTERS;


-- Final validation: bridge row count

SELECT
    COUNT(*) AS BRIDGE_ROW_COUNT
FROM P20A_BRIDGE_DOCTORS;


-- Final validation: diagnosis count

SELECT
    COUNT(*) AS DIAGNOSIS_COUNT
FROM P20A_DIM_DIAGNOSIS;


-- Final validation: date count

SELECT
    COUNT(*) AS DATE_COUNT
FROM P20A_DIM_DATE;