-- Task 1: Create database and schema

CREATE WAREHOUSE IF NOT EXISTS RETAIL11_WH
WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS RETAIL11_DB;

CREATE SCHEMA IF NOT EXISTS RETAIL11_DB.SALES_SCHEMA;

USE WAREHOUSE RETAIL11_WH;

USE DATABASE RETAIL11_DB;

USE SCHEMA SALES_SCHEMA;

SELECT
    CURRENT_WAREHOUSE(),
    CURRENT_DATABASE(),
    CURRENT_SCHEMA();


-- Task 2: Create hybrid dimension table

CREATE OR REPLACE TABLE DIM_CUSTOMER_HYBRID (
    CUSTOMER_KEY INTEGER AUTOINCREMENT,
    CUSTOMER_ID INTEGER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    PREVIOUS_CITY VARCHAR(50),
    STATE VARCHAR(50),
    CURRENT_MEMBERSHIP VARCHAR(30),
    PREVIOUS_MEMBERSHIP VARCHAR(30),
    HISTORICAL_MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);


-- Task 3: Create CSV file format

CREATE OR REPLACE FILE FORMAT RETAIL11_CSV_FORMAT
TYPE = 'CSV'
SKIP_HEADER = 1
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"';


-- Task 3: Create stage

CREATE OR REPLACE STAGE RETAIL11_STAGE
FILE_FORMAT = RETAIL11_CSV_FORMAT;


-- Task 3: Load initial customer data

COPY INTO DIM_CUSTOMER_HYBRID
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
FROM (
    SELECT
        $1::INTEGER,
        $2::VARCHAR,
        $3::VARCHAR,
        NULL,
        $4::VARCHAR,
        $5::VARCHAR,
        NULL,
        $5::VARCHAR,
        $6::VARCHAR,
        '2026-01-01'::DATE,
        '9999-12-31'::DATE,
        TRUE
    FROM @RETAIL11_STAGE/customers_initial_project11.csv
)
FILE_FORMAT = RETAIL11_CSV_FORMAT;


-- Task 3: Validate initial records

SELECT
    COUNT(*) AS TOTAL_RECORDS,
    COUNT_IF(IS_CURRENT = TRUE) AS CURRENT_RECORDS
FROM DIM_CUSTOMER_HYBRID;


-- Task 4: Display initial dimension

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID;


-- Task 5: Create update table

CREATE OR REPLACE TABLE CUSTOMER_UPDATES (
    CUSTOMER_ID INTEGER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE
);


-- Task 5: Load customer updates

COPY INTO CUSTOMER_UPDATES
FROM @RETAIL11_STAGE/customer_updates_project11.csv
FILE_FORMAT = RETAIL11_CSV_FORMAT;


-- Task 5: Expire Customer 101

UPDATE DIM_CUSTOMER_HYBRID
SET
    EXPIRY_DATE = '2026-03-31',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 101
  AND IS_CURRENT = TRUE;


-- Task 5: Expire Customer 103

UPDATE DIM_CUSTOMER_HYBRID
SET
    EXPIRY_DATE = '2026-04-04',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 103
  AND IS_CURRENT = TRUE;


-- Task 5: Expire Customer 104

UPDATE DIM_CUSTOMER_HYBRID
SET
    EXPIRY_DATE = '2026-04-09',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 104
  AND IS_CURRENT = TRUE;


-- Task 5: Insert new active versions

INSERT INTO DIM_CUSTOMER_HYBRID
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    u.CUSTOMER_ID,
    u.CUSTOMER_NAME,
    u.CITY,
    CASE
        WHEN u.CUSTOMER_ID = 101 THEN 'Hyderabad'
        WHEN u.CUSTOMER_ID = 103 THEN 'Vijayawada'
        WHEN u.CUSTOMER_ID = 104 THEN NULL
    END,
    u.STATE,
    u.MEMBERSHIP,
    CASE
        WHEN u.CUSTOMER_ID IN (101, 103) THEN 'Silver'
        WHEN u.CUSTOMER_ID = 104 THEN 'Gold'
    END,
    u.MEMBERSHIP,
    u.SEGMENT,
    u.EFFECTIVE_DATE,
    '9999-12-31'::DATE,
    TRUE
FROM CUSTOMER_UPDATES u;


-- Task 5: Synchronize Customer 101

UPDATE DIM_CUSTOMER_HYBRID
SET
    CITY = 'Bengaluru',
    PREVIOUS_CITY = 'Hyderabad',
    STATE = 'Karnataka',
    CURRENT_MEMBERSHIP = 'Gold',
    PREVIOUS_MEMBERSHIP = 'Silver'
WHERE CUSTOMER_ID = 101;


-- Task 5: Synchronize Customer 103

UPDATE DIM_CUSTOMER_HYBRID
SET
    CITY = 'Chennai',
    PREVIOUS_CITY = 'Vijayawada',
    STATE = 'Tamil Nadu',
    CURRENT_MEMBERSHIP = 'Gold',
    PREVIOUS_MEMBERSHIP = 'Silver'
WHERE CUSTOMER_ID = 103;


-- Task 5: Synchronize Customer 104

UPDATE DIM_CUSTOMER_HYBRID
SET
    CITY = 'Hyderabad',
    PREVIOUS_CITY = NULL,
    STATE = 'Telangana',
    CURRENT_MEMBERSHIP = 'Platinum',
    PREVIOUS_MEMBERSHIP = 'Gold'
WHERE CUSTOMER_ID = 104;


-- Task 5: Validate hybrid update

SELECT
    COUNT(*) AS TOTAL_RECORDS,
    COUNT_IF(IS_CURRENT = TRUE) AS CURRENT_RECORDS,
    COUNT_IF(IS_CURRENT = FALSE) AS HISTORICAL_RECORDS
FROM DIM_CUSTOMER_HYBRID;


-- Task 6: Display complete dimension history

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;


-- Task 7: Display active customer report

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;


-- Task 8: Point-in-time historical query

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER_HYBRID
WHERE CUSTOMER_ID = 101
  AND '2026-03-15'::DATE
      BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;


-- Task 9: Metric validation

SELECT
    COUNT(*) AS TOTAL_RECORD_COUNT,
    COUNT_IF(IS_CURRENT = TRUE) AS CURRENT_RECORD_COUNT,
    COUNT_IF(IS_CURRENT = FALSE) AS HISTORICAL_RECORD_COUNT
FROM DIM_CUSTOMER_HYBRID;