CREATE DATABASE IF NOT EXISTS P17_FINANCIAL_GOVERNANCE_DB;

CREATE SCHEMA IF NOT EXISTS P17_FINANCIAL_GOVERNANCE_DB.P17_WEALTH_CORE;

USE DATABASE P17_FINANCIAL_GOVERNANCE_DB;

USE SCHEMA P17_WEALTH_CORE;

CREATE WAREHOUSE IF NOT EXISTS P17_COMPUTE_WH
WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE FILE FORMAT IF NOT EXISTS P17_JSON_FORMAT
TYPE = JSON
STRIP_OUTER_ARRAY = FALSE;

CREATE FILE FORMAT IF NOT EXISTS P17_TEXT_FORMAT
TYPE = CSV
FIELD_DELIMITER = NONE
RECORD_DELIMITER = '\n';

CREATE STAGE IF NOT EXISTS P17_WEALTH_STAGE
FILE_FORMAT = P17_JSON_FORMAT;

CREATE OR REPLACE TABLE BRONZE_BANK_PAYLOADS (
    INGEST_ID INTEGER AUTOINCREMENT,
    PAYLOAD VARIANT,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE QUARANTINE_GOVERNANCE_PAYLOADS (
    QUARANTINE_ID INTEGER AUTOINCREMENT,
    RAW_RECORD_TEXT STRING,
    REASON STRING
);

LIST @P17_WEALTH_STAGE;

COPY INTO BRONZE_BANK_PAYLOADS (PAYLOAD)
FROM @P17_WEALTH_STAGE
FILE_FORMAT = P17_JSON_FORMAT
ON_ERROR = 'CONTINUE';

SELECT COUNT(*) AS TOTAL_BRONZE_RECORDS
FROM BRONZE_BANK_PAYLOADS;

INSERT INTO QUARANTINE_GOVERNANCE_PAYLOADS (
    RAW_RECORD_TEXT,
    REASON
)
SELECT
    $1::STRING,
    'MALFORMED_JSON_BODY'
FROM @P17_WEALTH_STAGE
(
    FILE_FORMAT => P17_TEXT_FORMAT
)
WHERE TRY_PARSE_JSON($1::STRING) IS NULL;

SELECT
    QUARANTINE_ID,
    RAW_RECORD_TEXT,
    REASON
FROM QUARANTINE_GOVERNANCE_PAYLOADS
ORDER BY QUARANTINE_ID;

CREATE OR REPLACE TABLE SILVER_BANK_TRANSACTIONS (
    TXN_ID STRING,
    CLIENT_ID INTEGER,
    CLIENT_SSN STRING,
    REGION STRING,
    ACCOUNT_NO STRING,
    AMOUNT NUMBER(18,2),
    STATUS STRING,
    AML_RISK_SCORE STRING
);

INSERT INTO SILVER_BANK_TRANSACTIONS
SELECT
    PAYLOAD:txn_id::STRING,
    PAYLOAD:client_id::INTEGER,
    PAYLOAD:client_ssn::STRING,
    PAYLOAD:region::STRING,
    PAYLOAD:account_no::STRING,
    PAYLOAD:amount::NUMBER(18,2),
    PAYLOAD:status::STRING,
    PAYLOAD:aml_risk_score::STRING
FROM BRONZE_BANK_PAYLOADS;

SELECT COUNT(*) AS TOTAL_SILVER_RECORDS
FROM SILVER_BANK_TRANSACTIONS;

SELECT
    TXN_ID,
    CLIENT_ID,
    CLIENT_SSN,
    REGION,
    ACCOUNT_NO,
    AMOUNT,
    STATUS,
    AML_RISK_SCORE
FROM SILVER_BANK_TRANSACTIONS
ORDER BY TXN_ID;

CREATE ROLE IF NOT EXISTS P17_COMPLIANCE_OFFICER;

CREATE ROLE IF NOT EXISTS P17_NA_ANALYST;

CREATE ROLE IF NOT EXISTS P17_EU_ANALYST;

GRANT USAGE ON WAREHOUSE P17_COMPUTE_WH
TO ROLE P17_COMPLIANCE_OFFICER;

GRANT USAGE ON WAREHOUSE P17_COMPUTE_WH
TO ROLE P17_NA_ANALYST;

GRANT USAGE ON WAREHOUSE P17_COMPUTE_WH
TO ROLE P17_EU_ANALYST;

GRANT USAGE ON DATABASE P17_FINANCIAL_GOVERNANCE_DB
TO ROLE P17_COMPLIANCE_OFFICER;

GRANT USAGE ON DATABASE P17_FINANCIAL_GOVERNANCE_DB
TO ROLE P17_NA_ANALYST;

GRANT USAGE ON DATABASE P17_FINANCIAL_GOVERNANCE_DB
TO ROLE P17_EU_ANALYST;

GRANT USAGE ON SCHEMA P17_FINANCIAL_GOVERNANCE_DB.P17_WEALTH_CORE
TO ROLE P17_COMPLIANCE_OFFICER;

GRANT USAGE ON SCHEMA P17_FINANCIAL_GOVERNANCE_DB.P17_WEALTH_CORE
TO ROLE P17_NA_ANALYST;

GRANT USAGE ON SCHEMA P17_FINANCIAL_GOVERNANCE_DB.P17_WEALTH_CORE
TO ROLE P17_EU_ANALYST;

GRANT SELECT ON TABLE SILVER_BANK_TRANSACTIONS
TO ROLE P17_COMPLIANCE_OFFICER;

GRANT SELECT ON TABLE SILVER_BANK_TRANSACTIONS
TO ROLE P17_NA_ANALYST;

GRANT SELECT ON TABLE SILVER_BANK_TRANSACTIONS
TO ROLE P17_EU_ANALYST;

CREATE OR REPLACE MASKING POLICY MASK_SSN
AS (VAL STRING)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() = 'P17_COMPLIANCE_OFFICER'
            THEN VAL
        ELSE '***-**-' || RIGHT(VAL, 4)
    END;

CREATE OR REPLACE MASKING POLICY MASK_ACCOUNT
AS (VAL STRING)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() = 'P17_COMPLIANCE_OFFICER'
            THEN VAL
        ELSE 'ACT-****'
    END;

ALTER TABLE SILVER_BANK_TRANSACTIONS
MODIFY COLUMN CLIENT_SSN
SET MASKING POLICY MASK_SSN;

ALTER TABLE SILVER_BANK_TRANSACTIONS
MODIFY COLUMN ACCOUNT_NO
SET MASKING POLICY MASK_ACCOUNT;

CREATE OR REPLACE ROW ACCESS POLICY RAP_REGION_POLICY
AS (REGION_VALUE STRING)
RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() = 'P17_COMPLIANCE_OFFICER'
            THEN TRUE
        WHEN CURRENT_ROLE() = 'P17_NA_ANALYST'
            THEN REGION_VALUE = 'NA'
        WHEN CURRENT_ROLE() = 'P17_EU_ANALYST'
            THEN REGION_VALUE = 'EU'
        ELSE FALSE
    END;

ALTER TABLE SILVER_BANK_TRANSACTIONS
ADD ROW ACCESS POLICY RAP_REGION_POLICY
ON (REGION);

CREATE OR REPLACE SECURE VIEW SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY AS
SELECT
    REGION,
    SUM(AMOUNT) AS TOTAL_SETTLED_VAL,
    COUNT(*) AS SETTLED_TXN_COUNT,
    AVG(AMOUNT) AS AVG_SETTLED_AMOUNT
FROM SILVER_BANK_TRANSACTIONS
WHERE STATUS = 'SETTLED'
GROUP BY REGION;

GRANT SELECT ON VIEW SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY
TO ROLE P17_COMPLIANCE_OFFICER;

SELECT
    REGION,
    TOTAL_SETTLED_VAL,
    SETTLED_TXN_COUNT,
    ROUND(AVG_SETTLED_AMOUNT, 2) AS AVG_SETTLED_AMOUNT
FROM SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY
ORDER BY REGION;

SELECT
    SUM(PAYLOAD:amount::NUMBER(18,2)) AS BRONZE_GROSS_TOTAL,
    (
        SELECT SUM(AMOUNT)
        FROM SILVER_BANK_TRANSACTIONS
    ) AS SILVER_GROSS_TOTAL,
    (
        SELECT SUM(AMOUNT)
        FROM SILVER_BANK_TRANSACTIONS
        WHERE STATUS = 'SETTLED'
    ) AS GOLD_GROSS_TOTAL,
    CASE
        WHEN
            SUM(PAYLOAD:amount::NUMBER(18,2)) =
            (
                SELECT SUM(AMOUNT)
                FROM SILVER_BANK_TRANSACTIONS
            )
            AND
            (
                SELECT SUM(AMOUNT)
                FROM SILVER_BANK_TRANSACTIONS
                WHERE STATUS = 'SETTLED'
            ) = 1765000.00
        THEN TRUE
        ELSE FALSE
    END AS RECONCILED_FLAG
FROM BRONZE_BANK_PAYLOADS;