CREATE OR REPLACE DATABASE FINANCIAL_GOVERNANCE_DB;

CREATE OR REPLACE SCHEMA FINANCIAL_GOVERNANCE_DB.WEALTH_CORE;

USE DATABASE FINANCIAL_GOVERNANCE_DB;

USE SCHEMA WEALTH_CORE;

CREATE OR REPLACE TABLE BRONZE_BANK_PAYLOADS (
    INGEST_ID INTEGER AUTOINCREMENT,
    PAYLOAD VARIANT,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE QUARANTINE_GOVERNANCE_PAYLOADS (
    INGEST_ID INTEGER AUTOINCREMENT,
    RAW_PAYLOAD VARCHAR,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO BRONZE_BANK_PAYLOADS (PAYLOAD)
SELECT PARSE_JSON('{"txn_id":"TXN-7001","timestamp":"2026-08-15T09:00:00Z","client_id":101,"client_ssn":"999-12-3456","region":"NA","account_no":"ACT-5544","amount":250000.00,"status":"SETTLED"}')
UNION ALL
SELECT PARSE_JSON('{"txn_id":"TXN-7002","timestamp":"2026-08-15T09:15:00Z","client_id":102,"client_ssn":"888-98-7654","region":"EU","account_no":"ACT-7711","amount":120000.00,"status":"SETTLED"}')
UNION ALL
SELECT PARSE_JSON('{"txn_id":"TXN-7003","timestamp":"2026-08-15T09:30:00Z","client_id":103,"client_ssn":"777-45-6789","region":"NA","account_no":"ACT-3322","amount":450000.00,"status":"PENDING"}')
UNION ALL
SELECT PARSE_JSON('{"txn_id":"TXN-7004","timestamp":"2026-08-15T10:00:00Z","client_id":104,"client_ssn":"666-23-8901","region":"EU","account_no":"ACT-9988","amount":85000.00,"status":"SETTLED"}')
UNION ALL
SELECT PARSE_JSON('{"txn_id":"TXN-7005","timestamp":"2026-08-15T10:30:00Z","client_id":105,"client_ssn":"555-67-1234","region":"NA","account_no":"ACT-1144","amount":1000000.00,"status":"SETTLED","aml_risk_score":"LOW"}')
UNION ALL
SELECT PARSE_JSON('{"txn_id":"TXN-7006","timestamp":"2026-08-15T11:00:00Z","client_id":106,"client_ssn":"444-89-4321","region":"EU","account_no":"ACT-6633","amount":310000.00,"status":"SETTLED","aml_risk_score":"MEDIUM"}')
UNION ALL
SELECT PARSE_JSON('{"txn_id":"TXN-7007","timestamp":"2026-08-15T11:30:00Z","client_id":107,"client_ssn":"333-11-2222","region":"NA","account_no":"ACT-2211","amount":0.00,"status":"FAILED","aml_risk_score":"HIGH"}');

INSERT INTO QUARANTINE_GOVERNANCE_PAYLOADS (RAW_PAYLOAD)
VALUES
('{"INVALID_RAW_WIRE_PAYLOAD_UNPARSEABLE"}');

SELECT COUNT(*) AS TOTAL_BRONZE_RECORDS
FROM BRONZE_BANK_PAYLOADS;

SELECT COUNT(*) AS TOTAL_QUARANTINED_RECORDS
FROM QUARANTINE_GOVERNANCE_PAYLOADS;

CREATE OR REPLACE TABLE SILVER_BANK_TRANSACTIONS (
    TXN_ID VARCHAR,
    CLIENT_ID INTEGER,
    CLIENT_SSN VARCHAR,
    REGION VARCHAR,
    ACCOUNT_NO VARCHAR,
    AMOUNT NUMBER(18,2),
    STATUS VARCHAR,
    AML_RISK_SCORE VARCHAR
);

INSERT INTO SILVER_BANK_TRANSACTIONS
SELECT
    PAYLOAD:txn_id::VARCHAR,
    PAYLOAD:client_id::INTEGER,
    PAYLOAD:client_ssn::VARCHAR,
    PAYLOAD:region::VARCHAR,
    PAYLOAD:account_no::VARCHAR,
    PAYLOAD:amount::NUMBER(18,2),
    PAYLOAD:status::VARCHAR,
    PAYLOAD:aml_risk_score::VARCHAR
FROM BRONZE_BANK_PAYLOADS;

SELECT COUNT(*) AS TOTAL_SILVER_RECORDS
FROM SILVER_BANK_TRANSACTIONS;

CREATE ROLE IF NOT EXISTS COMPLIANCE_OFFICER;

CREATE ROLE IF NOT EXISTS NA_ANALYST;

CREATE ROLE IF NOT EXISTS EU_ANALYST;

GRANT USAGE ON DATABASE FINANCIAL_GOVERNANCE_DB
TO ROLE COMPLIANCE_OFFICER;

GRANT USAGE ON SCHEMA FINANCIAL_GOVERNANCE_DB.WEALTH_CORE
TO ROLE COMPLIANCE_OFFICER;

GRANT USAGE ON DATABASE FINANCIAL_GOVERNANCE_DB
TO ROLE NA_ANALYST;

GRANT USAGE ON SCHEMA FINANCIAL_GOVERNANCE_DB.WEALTH_CORE
TO ROLE NA_ANALYST;

GRANT USAGE ON DATABASE FINANCIAL_GOVERNANCE_DB
TO ROLE EU_ANALYST;

GRANT USAGE ON SCHEMA FINANCIAL_GOVERNANCE_DB.WEALTH_CORE
TO ROLE EU_ANALYST;

CREATE OR REPLACE SECURE VIEW COMPLIANCE_BANK_TRANSACTIONS AS
SELECT
    TXN_ID,
    CLIENT_ID,
    CLIENT_SSN,
    REGION,
    ACCOUNT_NO,
    AMOUNT,
    STATUS,
    AML_RISK_SCORE
FROM SILVER_BANK_TRANSACTIONS
WHERE CURRENT_ROLE() = 'COMPLIANCE_OFFICER';

CREATE OR REPLACE SECURE VIEW NA_BANK_TRANSACTIONS AS
SELECT
    TXN_ID,
    CLIENT_ID,
    CASE
        WHEN CURRENT_ROLE() = 'NA_ANALYST'
        THEN '***-**-' || RIGHT(CLIENT_SSN, 4)
        ELSE NULL
    END AS CLIENT_SSN,
    REGION,
    CASE
        WHEN CURRENT_ROLE() = 'NA_ANALYST'
        THEN 'ACT-****'
        ELSE NULL
    END AS ACCOUNT_NO,
    AMOUNT,
    STATUS,
    AML_RISK_SCORE
FROM SILVER_BANK_TRANSACTIONS
WHERE CURRENT_ROLE() = 'NA_ANALYST'
AND REGION = 'NA';

CREATE OR REPLACE SECURE VIEW EU_BANK_TRANSACTIONS AS
SELECT
    TXN_ID,
    CLIENT_ID,
    CASE
        WHEN CURRENT_ROLE() = 'EU_ANALYST'
        THEN '***-**-' || RIGHT(CLIENT_SSN, 4)
        ELSE NULL
    END AS CLIENT_SSN,
    REGION,
    CASE
        WHEN CURRENT_ROLE() = 'EU_ANALYST'
        THEN 'ACT-****'
        ELSE NULL
    END AS ACCOUNT_NO,
    AMOUNT,
    STATUS,
    AML_RISK_SCORE
FROM SILVER_BANK_TRANSACTIONS
WHERE CURRENT_ROLE() = 'EU_ANALYST'
AND REGION = 'EU';

GRANT SELECT ON VIEW COMPLIANCE_BANK_TRANSACTIONS
TO ROLE COMPLIANCE_OFFICER;

GRANT SELECT ON VIEW NA_BANK_TRANSACTIONS
TO ROLE NA_ANALYST;

GRANT SELECT ON VIEW EU_BANK_TRANSACTIONS
TO ROLE EU_ANALYST;

CREATE OR REPLACE SECURE VIEW SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY AS
SELECT
    REGION,
    SUM(AMOUNT) AS TOTAL_SETTLED_VAL,
    COUNT(*) AS SETTLED_TXN_COUNT,
    ROUND(AVG(AMOUNT), 2) AS AVG_SETTLED_AMOUNT
FROM SILVER_BANK_TRANSACTIONS
WHERE STATUS = 'SETTLED'
GROUP BY REGION;

SELECT
    REGION,
    TOTAL_SETTLED_VAL,
    SETTLED_TXN_COUNT,
    AVG_SETTLED_AMOUNT
FROM SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY
ORDER BY REGION;

SELECT
    SUM(AMOUNT) AS BRONZE_GROSS_TOTAL
FROM SILVER_BANK_TRANSACTIONS;

SELECT
    SUM(AMOUNT) AS SILVER_GROSS_TOTAL
FROM SILVER_BANK_TRANSACTIONS;

SELECT
    SUM(TOTAL_SETTLED_VAL) AS GOLD_GROSS_TOTAL
FROM SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY;

SELECT
    b.BRONZE_GROSS_TOTAL,
    s.SILVER_GROSS_TOTAL,
    g.GOLD_GROSS_TOTAL,
    CASE
        WHEN b.BRONZE_GROSS_TOTAL = s.SILVER_GROSS_TOTAL
        THEN TRUE
        ELSE FALSE
    END AS RECONCILED_FLAG
FROM
(
    SELECT SUM(AMOUNT) AS BRONZE_GROSS_TOTAL
    FROM SILVER_BANK_TRANSACTIONS
) b
CROSS JOIN
(
    SELECT SUM(AMOUNT) AS SILVER_GROSS_TOTAL
    FROM SILVER_BANK_TRANSACTIONS
) s
CROSS JOIN
(
    SELECT SUM(TOTAL_SETTLED_VAL) AS GOLD_GROSS_TOTAL
    FROM SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY
) g;

SHOW GRANTS ON VIEW COMPLIANCE_BANK_TRANSACTIONS;

SHOW GRANTS ON VIEW NA_BANK_TRANSACTIONS;

SHOW GRANTS ON VIEW EU_BANK_TRANSACTIONS;

SHOW GRANTS ON VIEW SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY;