/*
Problem Description:
The restaurant operations division wants to find out which food items are the primary revenue drivers within each menu section. 
Write a read-only SQL query that constructs a derived table to compute the total revenue generated by each food item 
(filtered only for orders that have been successfully 'Delivered'). 
Combine this with a correlated subquery to filter and return the food item name, category, and total revenue for the food items 
that have achieved the absolute highest revenue within their respective menu category.

case=1
output=
food_item_name	category	total_revenue
Masala Dosa	Breakfast	360.00
Chicken Biryani	Main Course	300.00
Dal Tadka	Main Course	300.00
Samosa	Snacks	270.00
Butter Naan	Breads	240.00
Mango Lassi	Beverages	180.00
Gulab Jamun	Desserts	150.00



*/
USE fs;

select
    t.food_item_name,
    t.category,
    t.total_revenue
from
(
    select 
        f.food_id,
        f.name as food_item_name,
        f.category,
        sum(o.total_amount) as total_revenue
    from FoodItems f
    join Orders o
    on f.food_id=o.food_id
    where o.status='Delivered'
    group by 
        f.food_id,
        f.name,
        f.category
)as t
where t.total_revenue=
(
    select 
        max(t2.total_revenue)
        from
        (
            select
                f.food_id,
                f.category,
                sum(o.total_amount) as total_revenue
                from FoodItems f
                join Orders o
                on f.food_id=o.food_id
                where o.status='Delivered'
                group by
                    f.food_id,
                    f.category
        )as t2
        where t2.category=t.category
)order by total_revenue desc