CREATE WAREHOUSE IF NOT EXISTS P20B_FINANCIAL_RISK_WH
WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS P20B_FINANCIAL_RISK_DB;

CREATE SCHEMA IF NOT EXISTS P20B_FINANCIAL_RISK_DB.FINANCIAL_RISK_SCHEMA;

USE WAREHOUSE P20B_FINANCIAL_RISK_WH;
USE DATABASE P20B_FINANCIAL_RISK_DB;
USE SCHEMA FINANCIAL_RISK_SCHEMA;

CREATE OR REPLACE FILE FORMAT P20B_JSON_FORMAT
    TYPE = JSON;

CREATE OR REPLACE STAGE P20B_FINANCIAL_RISK_STAGE
    FILE_FORMAT = P20B_JSON_FORMAT;

CREATE OR REPLACE TABLE RAW_RATINGS (
    RAW_DATA VARIANT
);

CREATE OR REPLACE TABLE RAW_BRANCHES (
    RAW_DATA VARIANT
);

CREATE OR REPLACE TABLE RAW_CUSTOMERS (
    RAW_DATA VARIANT
);

CREATE OR REPLACE TABLE RAW_FACILITIES (
    RAW_DATA VARIANT
);

CREATE OR REPLACE TABLE RAW_LOAN_APPLICATIONS (
    RAW_DATA VARIANT
);

CREATE OR REPLACE TABLE RAW_LOAN_UPDATES (
    RAW_DATA VARIANT
);

COPY INTO RAW_RATINGS
FROM @P20B_FINANCIAL_RISK_STAGE
PATTERN = '.*P20B_raw_ratings_kv.*';

COPY INTO RAW_BRANCHES
FROM @P20B_FINANCIAL_RISK_STAGE
PATTERN = '.*P20B_raw_branches_kv.*';

COPY INTO RAW_CUSTOMERS
FROM @P20B_FINANCIAL_RISK_STAGE
PATTERN = '.*P20B_raw_customers_kv.*';

COPY INTO RAW_FACILITIES
FROM @P20B_FINANCIAL_RISK_STAGE
PATTERN = '.*P20B_raw_facilities_kv.*';

COPY INTO RAW_LOAN_APPLICATIONS
FROM @P20B_FINANCIAL_RISK_STAGE
PATTERN = '.*P20B_raw_loan_applications_kv.*';

COPY INTO RAW_LOAN_UPDATES
FROM @P20B_FINANCIAL_RISK_STAGE
PATTERN = '.*P20B_cdc_loan_updates_kv.*';

CREATE OR REPLACE TABLE STG_RATINGS (
    RATING_ID VARCHAR(20),
    AGENCY VARCHAR(50),
    CREDIT_SCORE_BAND VARCHAR(20),
    RISK_TIER VARCHAR(50)
);

INSERT INTO STG_RATINGS
SELECT
    RAW_DATA:rating_id::VARCHAR,
    RAW_DATA:agency::VARCHAR,
    RAW_DATA:credit_score_band::VARCHAR,
    RAW_DATA:risk_tier::VARCHAR
FROM RAW_RATINGS;

CREATE OR REPLACE TABLE STG_BRANCHES (
    BRANCH_ID VARCHAR(20),
    BRANCH_NAME VARCHAR(100),
    REGION VARCHAR(50)
);

INSERT INTO STG_BRANCHES
SELECT
    RAW_DATA:branch_id::VARCHAR,
    RAW_DATA:branch_name::VARCHAR,
    RAW_DATA:region::VARCHAR
FROM RAW_BRANCHES;

CREATE OR REPLACE TABLE STG_CUSTOMERS (
    CUSTOMER_ID VARCHAR(30),
    CUSTOMER_NAME VARCHAR(100),
    RATING_ID VARCHAR(20),
    BRANCH_ID VARCHAR(20)
);

INSERT INTO STG_CUSTOMERS
SELECT
    RAW_DATA:customer_id::VARCHAR,
    RAW_DATA:customer_name::VARCHAR,
    RAW_DATA:rating_id::VARCHAR,
    RAW_DATA:branch_id::VARCHAR
FROM RAW_CUSTOMERS;

CREATE OR REPLACE TABLE STG_FACILITIES (
    CUSTOMER_ID VARCHAR(30),
    FACILITY_ID VARCHAR(30),
    ELIGIBILITY_FLAG BOOLEAN
);

INSERT INTO STG_FACILITIES
SELECT
    RAW_DATA:customer_id::VARCHAR,
    RAW_DATA:facility_id::VARCHAR,
    RAW_DATA:eligibility_flag::BOOLEAN
FROM RAW_FACILITIES;

CREATE OR REPLACE TABLE STG_LOAN_APPLICATIONS (
    APP_ID VARCHAR(30),
    CUSTOMER_ID VARCHAR(30),
    SUBMITTED_DATE DATE,
    UNDERWRITTEN_DATE DATE,
    APPROVED_DATE DATE,
    DISBURSED_DATE DATE,
    LOAN_AMOUNT NUMBER(18,2)
);

INSERT INTO STG_LOAN_APPLICATIONS
SELECT
    RAW_DATA:app_id::VARCHAR,
    RAW_DATA:customer_id::VARCHAR,
    RAW_DATA:submitted_date::DATE,
    RAW_DATA:underwritten_date::DATE,
    RAW_DATA:approved_date::DATE,
    RAW_DATA:disbursed_date::DATE,
    RAW_DATA:loan_amount::NUMBER(18,2)
FROM RAW_LOAN_APPLICATIONS;

CREATE OR REPLACE TABLE STG_LOAN_UPDATES (
    APP_ID VARCHAR(30),
    APPROVED_DATE DATE,
    DISBURSED_DATE DATE
);

INSERT INTO STG_LOAN_UPDATES
SELECT
    RAW_DATA:app_id::VARCHAR,
    RAW_DATA:approved_date::DATE,
    RAW_DATA:disbursed_date::DATE
FROM RAW_LOAN_UPDATES;

CREATE OR REPLACE TABLE DIM_OUTRIGGER_RATING (
    RATING_ID VARCHAR(20) PRIMARY KEY,
    AGENCY VARCHAR(50),
    CREDIT_SCORE_BAND VARCHAR(20),
    RISK_TIER VARCHAR(50)
);

INSERT INTO DIM_OUTRIGGER_RATING
SELECT *
FROM STG_RATINGS;

CREATE OR REPLACE TABLE DIM_BRANCH (
    BRANCH_ID VARCHAR(20) PRIMARY KEY,
    BRANCH_NAME VARCHAR(100),
    REGION VARCHAR(50)
);

INSERT INTO DIM_BRANCH
SELECT *
FROM STG_BRANCHES;

CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_ID VARCHAR(30) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100),
    RATING_ID VARCHAR(20),
    BRANCH_ID VARCHAR(20)
);

INSERT INTO DIM_CUSTOMER
SELECT *
FROM STG_CUSTOMERS;

CREATE OR REPLACE TABLE FACT_CUSTOMER_FACILITY_ELIGIBILITY (
    CUSTOMER_ID VARCHAR(30),
    FACILITY_ID VARCHAR(30),
    ELIGIBILITY_FLAG BOOLEAN
);

INSERT INTO FACT_CUSTOMER_FACILITY_ELIGIBILITY
SELECT *
FROM STG_FACILITIES;

CREATE OR REPLACE TABLE FACT_LOAN_APPLICATION_SNAPSHOT (
    APP_ID VARCHAR(30) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(30),
    SUBMITTED_DATE DATE,
    UNDERWRITTEN_DATE DATE,
    APPROVED_DATE DATE,
    DISBURSED_DATE DATE,
    LOAN_AMOUNT NUMBER(18,2),
    SUBMISSION_TO_UNDERWRITING_DAYS NUMBER,
    UNDERWRITING_TO_APPROVAL_DAYS NUMBER,
    APPROVAL_TO_DISBURSEMENT_DAYS NUMBER,

    CONSTRAINT CK_SUBMITTED_UNDERWRITTEN
        CHECK (
            UNDERWRITTEN_DATE IS NULL
            OR SUBMITTED_DATE <= UNDERWRITTEN_DATE
        ),

    CONSTRAINT CK_UNDERWRITTEN_APPROVED
        CHECK (
            APPROVED_DATE IS NULL
            OR UNDERWRITTEN_DATE <= APPROVED_DATE
        ),

    CONSTRAINT CK_APPROVED_DISBURSED
        CHECK (
            DISBURSED_DATE IS NULL
            OR APPROVED_DATE <= DISBURSED_DATE
        )
);

INSERT INTO FACT_LOAN_APPLICATION_SNAPSHOT (
    APP_ID,
    CUSTOMER_ID,
    SUBMITTED_DATE,
    UNDERWRITTEN_DATE,
    APPROVED_DATE,
    DISBURSED_DATE,
    LOAN_AMOUNT,
    SUBMISSION_TO_UNDERWRITING_DAYS,
    UNDERWRITING_TO_APPROVAL_DAYS,
    APPROVAL_TO_DISBURSEMENT_DAYS
)
SELECT
    APP_ID,
    CUSTOMER_ID,
    SUBMITTED_DATE,
    UNDERWRITTEN_DATE,
    APPROVED_DATE,
    DISBURSED_DATE,
    LOAN_AMOUNT,

    DATEDIFF(
        'day',
        SUBMITTED_DATE,
        UNDERWRITTEN_DATE
    ),

    CASE
        WHEN APPROVED_DATE IS NOT NULL
        THEN DATEDIFF(
            'day',
            UNDERWRITTEN_DATE,
            APPROVED_DATE
        )
    END,

    CASE
        WHEN DISBURSED_DATE IS NOT NULL
        THEN DATEDIFF(
            'day',
            APPROVED_DATE,
            DISBURSED_DATE
        )
    END

FROM STG_LOAN_APPLICATIONS;

SET P20B_PRE_MERGE_TIMESTAMP = CURRENT_TIMESTAMP();

MERGE INTO FACT_LOAN_APPLICATION_SNAPSHOT T
USING STG_LOAN_UPDATES S
    ON T.APP_ID = S.APP_ID

WHEN MATCHED THEN
UPDATE SET
    T.APPROVED_DATE = S.APPROVED_DATE,
    T.DISBURSED_DATE = S.DISBURSED_DATE,

    T.UNDERWRITING_TO_APPROVAL_DAYS =
        CASE
            WHEN S.APPROVED_DATE IS NOT NULL
            THEN DATEDIFF(
                'day',
                T.UNDERWRITTEN_DATE,
                S.APPROVED_DATE
            )
        END,

    T.APPROVAL_TO_DISBURSEMENT_DAYS =
        CASE
            WHEN S.DISBURSED_DATE IS NOT NULL
                 AND S.APPROVED_DATE IS NOT NULL
            THEN DATEDIFF(
                'day',
                S.APPROVED_DATE,
                S.DISBURSED_DATE
            )
        END;

SELECT
    F.APP_ID,
    C.CUSTOMER_NAME,
    B.BRANCH_NAME,
    R.CREDIT_SCORE_BAND,
    R.RISK_TIER,
    F.LOAN_AMOUNT
FROM FACT_LOAN_APPLICATION_SNAPSHOT F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
JOIN DIM_BRANCH B
    ON C.BRANCH_ID = B.BRANCH_ID
JOIN DIM_OUTRIGGER_RATING R
    ON C.RATING_ID = R.RATING_ID
ORDER BY F.APP_ID;

SELECT
    'DATE_SEQUENCE_CHK' AS CHECK_NAME,

    COUNT_IF(
        (UNDERWRITTEN_DATE IS NOT NULL
         AND SUBMITTED_DATE > UNDERWRITTEN_DATE)

        OR

        (APPROVED_DATE IS NOT NULL
         AND UNDERWRITTEN_DATE > APPROVED_DATE)

        OR

        (DISBURSED_DATE IS NOT NULL
         AND APPROVED_DATE > DISBURSED_DATE)
    ) AS INVALID_SEQUENCES,

    CASE
        WHEN COUNT_IF(
            (UNDERWRITTEN_DATE IS NOT NULL
             AND SUBMITTED_DATE > UNDERWRITTEN_DATE)

            OR

            (APPROVED_DATE IS NOT NULL
             AND UNDERWRITTEN_DATE > APPROVED_DATE)

            OR

            (DISBURSED_DATE IS NOT NULL
             AND APPROVED_DATE > DISBURSED_DATE)
        ) = 0
        THEN 'PASSED'
        ELSE 'FAILED'
    END AS STATUS

FROM FACT_LOAN_APPLICATION_SNAPSHOT;

SELECT
    APP_ID,
    APPROVED_DATE,
    DISBURSED_DATE
FROM FACT_LOAN_APPLICATION_SNAPSHOT
AT(TIMESTAMP => $P20B_PRE_MERGE_TIMESTAMP)
WHERE APP_ID = 'APP-9001';

ALTER TABLE FACT_CUSTOMER_FACILITY_ELIGIBILITY
CLUSTER BY (CUSTOMER_ID, FACILITY_ID);

SELECT
    'FACT_CUSTOMER_FACILITY_ELIGIBILITY' AS TARGET_TABLE,
    CASE
        WHEN CLUSTERING_KEY IS NOT NULL
        THEN 'OPTIMIZED'
        ELSE 'NOT OPTIMIZED'
    END AS CLUSTERING_STATUS
FROM P20B_FINANCIAL_RISK_DB.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'FINANCIAL_RISK_SCHEMA'
  AND TABLE_NAME = 'FACT_CUSTOMER_FACILITY_ELIGIBILITY';